### ISSUE TITLE
TS2741: Property 'manager' is missing in type '{ children: Element; }' but required in type 'ProviderProps'.

### ISSUE THREAD

**Issue by christophehurpeau** [coinbase/rest-hooks#1]
I started to follow the installation guide: https://github.com/coinbase/rest-hooks/blob/master/docs/getting-started/installation.md

At step 1, we need to add a RestProvider without props. Typescript asks to add a prop `manager`:

![screenshot 2019-02-26 at 17 00 11](https://user-images.githubusercontent.com/302891/53426904-2c4dc180-39e8-11e9-978b-76d9078a75d6.png)

Also, when I run typescript check, I have these errors:

![screenshot 2019-02-26 at 17 02 03](https://user-images.githubusercontent.com/302891/53426947-41c2eb80-39e8-11e9-9cf5-7d76697dc003.png)

This is a new create-react-app project with typescript.

package.json:

```json
{
  "dependencies": {
    "rest-hooks": "^0.7.3",
  },
  "devDependencies": {
    "typescript": "^3.3.3333"
  }
}
```

tsconfig.json:

```json
{
  "extends": "./tsconfig.paths",
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "preserve"
  },
  "include": [
    "src"
  ]
}
```

**Comment by ntucker** [comment]
Thanks for the report. Will get on this! :)

**Comment by ntucker** [comment]
Should be fixed in #b335faddc9f7c4e9fc0e7191dcba1934ebb0bd34

**Comment by ntucker** [comment]
Fix released in https://github.com/coinbase/rest-hooks/releases/tag/0.8.0

**Comment by christophehurpeau** [comment]
Thank you :)
