### ISSUE TITLE
Hooks not firing in plain js react projects

### ISSUE THREAD

**Issue by rahulballal** [coinbase/rest-hooks#110]
**React version** (e.g., 16.8.5)
`^16.8.6`
**Concurrent mode** yes/no
`no`

**Describe the bug**

I have created a project using CRA 3.0.1

**To Reproduce**
1. Create a project using CRA 3.0.1
2. Ensure the dependencies look like this
```
    "core-js": "^3.1.4",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-loader-spinner": "^2.3.0",
    "react-scripts": "3.0.1",
    "rest-hooks": "^2.0.2"
```
3. Replace the `App.js` file to be
```javascript
import React, { Suspense } from "react";
import { NetworkErrorBoundary, useResource } from "rest-hooks";
import { Resource } from "rest-hooks";

class CommentResource extends Resource {
  id = null;
  name = "";
  email = "";
  body = "";
  postId = null;

  pk() {
    return this.id;
  }

  static urlRoot = "http://jsonplaceholder.typicode.com/comments";
}

function CommentList() {
  const comments = useResource(CommentResource.listShape(), {});
  return (
    <section>
      {
        comments ? JSON.stringify(comments): ''
      }
    </section>
  );
}

const Waitr = () => <p>Waiting for data ...</p>
const App = () => (
  <div>
    <h1>Main Title</h1>
    <Suspense fallback={<Waitr />}>
      <NetworkErrorBoundary>
        <CommentList />
      </NetworkErrorBoundary>
    </Suspense>
  </div>
);

export default App;
```

The api call is stuck in pending state

![image](https://user-images.githubusercontent.com/1627280/61753388-84032400-adf2-11e9-8d57-09ed6c71ffe3.png)

**Expected behavior**

The `CommentList` component prints out the response stringified. The api is `http://jsonplaceholder.typicode.com/comments`

**Comment by ntucker** [comment]
Thanks for the error report! To help track down this issue, can you tell me if you see any console errors and also report on what the networking tab shows?

**Comment by rahulballal** [comment]
The http request never gets made

![image](https://user-images.githubusercontent.com/1627280/61757946-0a753100-ae06-11e9-87b2-815248c1a750.png)

**Comment by ntucker** [comment]
Ah, found your problem. You never added the [CacheProvider](https://resthooks.io/docs/getting-started/installation#add-provider-at-top-level-component). I actually added a [console warning ](https://github.com/coinbase/rest-hooks/commit/fd68b3a19cac37b70922fb3a8ddb43a93f865199) in this case recently but haven't pushed out a new release with that feature yet.

**Comment by ntucker** [comment]
Decided to release 2.0.3 so people can benefit from that warning

**Comment by ntucker** [comment]
Feel free to reopen if you have more issues

**Comment by rahulballal** [comment]
Thanks @ntucker ! I love what you have done. I will open issue if I notice something else.

**Comment by rahulballal** [comment]
I can confirm that adding the `<CacheProvider/>` works. I was mislead by the name. I thought you need it only if you need to cache the response.
