### ISSUE TITLE
Custom shapes with different getFetchKey

### ISSUE THREAD

**Issue by stevewillard** [coinbase/rest-hooks#114]
I'm trying to upgrade from 1.x to 2.x, where previously I had some custom requests (now shapes), which had different a different `url` (now `getFetchKey`). I can't seem to change the `url` as part of my new shapes. Maybe this is a bug in version 2?

```
export class ExampleResource extends BaseResource {
  static urlRoot = 'v1/examples/';

  static customShape() {
    return {
      ...super.createShape(),
      getFetchKey: () => 'v1/examples/custom/',
    };
  }
}
```

Previously this code was:
```
export class ExampleResource extends BaseResource {
  static urlRoot = 'v1/examples/';

  static customRequest() {
    return {
      ...super.createRequest(),
      getUrl: () => 'v1/examples/custom/',
    };
  }
}
```

**Comment by ntucker** [comment]
You'll need to also override the fetch function of FetchShape. https://resthooks.io/docs/guides/endpoints#custom-get is a good example. I didn't outline this in the migration blog post so I'll add that soon. Riding home now so I'll have more details then.

**Comment by stevewillard** [comment]
Ah ok. That seems to be working now. Thanks! Feel free to close.

**Comment by stbn694** [comment]
Hi, isn't there a more direct approach to achieve this? Seems a little unnecessary and ugly to repeat the URL, even more if you have to take params into account, like this:

```javascript
static searchShape() {
  return {
    ...super.listShape(),
    getFetchKey: params =>
      `${this.urlRoot}/find?${new URLSearchParams(params).toString()}`,
    fetch: (params, body) =>
      this.fetch(
        'get',
        `${this.urlRoot}/find?${new URLSearchParams(params).toString()}`,
        body
      )
  };
}
```
