### ISSUE TITLE
best way to conditionally query a resource? maybe adding a `skip` boolean to `useRetrieve`? 

### ISSUE THREAD

**Issue by ken-zhong** [coinbase/rest-hooks#115]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to conditionally query a resource. Often I can move the hook farther down the render tree and just conditionally render the component that calls it, but sometimes it'd be a whole lot easier just to be able to skip a network request.

**Describe the solution you'd like**
Apollo react hooks have a `skip` argument that can be passed in. Something similar could work here. The `useRetrieve` hook could take in optional parameters that skips the `fetch` call.

**Comment by ntucker** [comment]
Try passing a falsy value like null as params

**Comment by ntucker** [comment]
Added an explanation of this behavior in the docs: https://github.com/coinbase/rest-hooks/commit/2b18db7b232274e189b846a9e9988bb722c3115e

**Comment by ken-zhong** [comment]
@ntucker Thanks for the quick response + the doc updates!
