### ISSUE TITLE
Function from useFetcher() should have params first

### ISSUE THREAD

**Issue by ntucker** [coinbase/rest-hooks#117]
**Is your feature request related to a problem? Please describe.**
The ordering of params and body for useFetcher() is inconsistent with the rest of Rest Hooks library. Having params first seems to also match the general outside world.

**Describe the solution you'd like**
```typescript
create({}, { title: 'hi', body: 'this content is great' });
update({ id }, { title: 'ho', body: 'this content is mediocre' });
fetchList({});
fetchDetail({ id });
```
Switch ordering and now body is optional so we don't have awkward undefined being passed.

**Comment by stevewillard** [comment]
Totally agree. I think `params` should come before `body`.

**Comment by elsangedy** [comment]
agree
