### ISSUE TITLE
Maintain same object reference for subscription if contents match

### ISSUE THREAD

**Issue by rhlgs** [coinbase/rest-hooks#1200]
**Is your feature request related to a problem? Please describe.**

A useSubscription causes unnecessary rerenders even if the key value pairs in the object are the same. This is because the object reference changes.

Can get around this by comparing JSON of objects, but ideally would like a lower level solution

**Describe the solution you'd like**

```jsx

const useWrappedResource = (...args) => {
  const valueRaw = useResource(...args);
  useSubscription(...args);

  const [value, setValue] = useState(valueRaw);

  useEffect(() => {
    const valueRawJson = JSON.stringify(valueRaw);
    const valueJson = JSON.stringify(value);

    if (valueRawJson !== valueJson) {
      setValue(valueRaw);
    }
  }, [value, valueRaw]);

  // value is stable across a subscription
  return value;
};

```

**Comment by ntucker** [comment]
Better way is probably to use [Entity.merge()](https://resthooks.io/docs/api/Entity#merge) this will short-circuit even earlier and only do the check once rather than any component that uses this hook.

This would simply add this behavior

```ts
static merge(existing, incoming) {
  if (deepEqual(incoming, existing)) return existing;
  return { ...existing, ...incoming };
}
```

And if you don't want to merge but just use newest value:


```ts
static merge(existing, incoming) {
  if (deepEqual(incoming, existing)) return existing;
  return incoming
}
```

**Comment by yunyu** [comment]
@ntucker deepEqual definitely makes more sense. It would be great if this were implemented at the useSubscription level (so the performance enhancement would be there by default).

**Comment by ntucker** [comment]
If you put this in a BaseResource, it will be there by 'default' as well. Are there cases where you'd want this on a subscription but not another use of a given resource?

**Comment by yunyu** [comment]
Not particularly – and that is a good suggestion for our codebase.

**Comment by ntucker** [comment]
Generally I err on the side of the more obvious action as default when there are several valid behaviors. deepEquals itself is not cheap, and thus if there is a low probability of the contents being the same this could be a major performance degradation instead of win.

This is a good opportunity to add a guide for this case tho! Happy to accept PRs with guides or I might get around to it myself

**Comment by rhlgs** [comment]
thanks @ntucker!, this clears it up

**Comment by yunyu** [comment]
I'd argue that deepEquals is probably way cheaper than a rerender, but I can understand the philosophy. We can definitely submit a PR highlighting merge (wasn't aware it existed) for a performance optimization.

**Comment by ntucker** [comment]
deepEquals is cheaper than re-render.

Case where data does not change: deep equal
Case where data does change: deep equal + rerender


So if data received more often changes data, you're just adding an extra computation without short-circuiting anything. In many cases, the cost of the deep equal is somewhat similar to rerender, so this doesn't need to happen often for it to slow things down. (after all react DOM is just doing a deep equal itself)

In fact there are cases where a deepequal could be *more* expensive than rerender. if the object is deeply complex, but the component rendered is very simply and only uses one attribute. In this case, react's rerender will do a very cheap diff for DOM updates, but the deep equal could have been worse.

**Comment by yunyu** [comment]
@ntucker You are completely right – I guess that's why this may make more sense for subscriptions because we'd expect the contents to match most of the time. IIRC the argument against memoizing everything is typically related to closure GC cost, which doesn't really apply here, but the value of a deepEqual is definitely more dubious outside of subscriptions.

**Comment by ntucker** [comment]
Ya, that makes sense that subscriptions would be more likely to hit this case of unchanging. Are there some resources you subscribe to and others you don't?

(At Coinbase we just subscribed to price so it always changed so this wasn't a factor for us.)
