### ISSUE TITLE
Way to do optimistic updates for custom fetch shapes?

### ISSUE THREAD

**Issue by binchik** [coinbase/rest-hooks#124]
**Is your feature request related to a problem? Please describe.**
I'm using API that has a sort patch endpoint. It sorts a list of objects and returns nothing. I successfully added a custom fetch shape for sorting. And I'd like it to be optimistically updated but haven't found a way to do that.

**Describe the solution you'd like**
I'd like some interface to be able to update resource cache item manually. Fetch could provide an object containing all resource specific data stored in cache and a function to update it. For example:

```
fetch: async ({collectionId}, body, cache) => {
    const cachedList = cache.getList();
    const optimisticList = body.order.map(itemId => cachedList.find(itemId));
    cache.updateList(optimisticList);

      return this.fetch(
        'patch',
        '/sort',
        body,
      );
    },
```

**Describe alternatives you've considered**
I've declared a state hook to store rendered items, and update it manually when either sort is called or useResource result is updated.

**Comment by ntucker** [comment]
Thanks for the report!

Let me try to see if I understand this correctly: when you send a patch request to /sort it will changes the sort order of future calls to GET /.

So what you want is to be able to know that this will change from the patch and update the rest hooks cache for all GET / requests to return the new sort order.

Can you confirm that this sounds like I understand your situation correctly? Thanks!

**Comment by binchik** [comment]
@ntucker Yes, that's what I want. And I want to update the cache optimistically.

**Comment by St1myL** [comment]
@ntucker, what if I want to call GET after each PATCH or simply call GET again on click?

**Comment by ntucker** [comment]
@St1myL I feel like I'm missing the first half of this conversation. With regard to what are you asking about this scenario?

**Comment by St1myL** [comment]
@ntucker, I thought my question is regarded to this issue. Should I create new issue?

**Comment by ntucker** [comment]
@St1myL I guess I'm just lost because if you're referring to this scenario, then the answer is in the setup:

"Let me try to see if I understand this correctly: when you send a patch request to /sort it will changes the sort order of future calls to GET /."

**Comment by St1myL** [comment]
@ntucker yep, I referred to this scenario

**Comment by ntucker** [comment]
If you do a GET after, it will have the correct results from the server so everything will work well. The purpose of optimistic updating is so you can have those correct results without having to do another request. Without it you can still make your application work by initiating subsequent fetches - however this is undesirable as it adds complexity and latency to the user experience. This is a reasonable workaround until this lands however.

Does that address your question @St1myL ?

**Comment by St1myL** [comment]
@ntucker yes, I finally get it. Thank you for the explanation, still new at this. My task was to update data on the page but I have a different approach to deal with it.

**Comment by ntucker** [comment]
Not sure about the specifics of your endpoint, but in [2.2](https://github.com/coinbase/rest-hooks/releases/tag/2.2.0) You can now add custom update functions like so:

```typescript
function mergeArticles(
  sortEndpointResponse: any,
  resultsFromCache: string[],
): string[] {
  const ret = [...resultsFromCache];
  ret.sort();
  return ret;
}

function useSortFetcher(params) {
  const sort= useFetcher(MyResource.sortShape());
  return useCallback(() => {
    return sort({}, params, [
      [MyResource.listShape(), {}, mergeArticles],
    ]);
  }, [sort]);
}
```

A few notes: resultsFromCache is going to be the `ResultType<typeof MyResource.listShape().schema>`. In other words, the normalized form of the actual response for list request with entities turned into their ids. Return value must match. I used the simple string[] as example but could very well be different for you.

I implemented a hook here that returns a function to call that will both do the fetch and automatically provide the proper sort as well. This is seen by using the new third parameter to the `fetch()` function returned from useFetcher() hook.

PS) We needed a lot of features internally so haven't fully documented these parts on the public docs site yet, but that will come later.

@St1myL @binchik Please tell me if this works for you! Using these functions are powerful and are strictly typed so you shouldn't have to worry if you're using typescript but if not you should be very careful as a messed up state will ruin the whole library.

**Comment by ntucker** [comment]
Docs updated https://resthooks.io/docs/api/useFetcher#updatefunction-sourceresults-destresults-destresults

Please tell me if this is clear!

**Comment by ntucker** [comment]
Gonna close this issue since it has landed. Feel free to open a new issue with any additional issues you may have!
