### ISSUE TITLE
How to deal with resources without pk?

### ISSUE THREAD

**Issue by mkaput** [coinbase/rest-hooks#125]
**Is your feature request related to a problem? Please describe.**

Say we want to represent some singleton-like resource, e.g. oauth service connection. Such things do not have any kind of primary key somewhere in them, there's just one instance of them anyway. How to model such things as a resource?

Currently I have end up this snippet, but this seems not to work with deleting, ending up with `Error: Resource not found GET /api/service/connect`:

```ts
export default class ServiceConnection extends Resource {
  readonly user: User | null = null;

  pk() {
    return 1;
  }

  static urlRoot = '/api/service/connect';

  static url() {
    return ServiceConnection .urlRoot;
  }
}
```

**Describe the solution you'd like**

Personally I expected this to work by intuition:

```ts
export default class ServiceConnection extends Resource {
  readonly user: User | null = null;

  pk() {
    return null;
  }

  static urlRoot = '/api/service/connect';
}
```

**Notes**

I could not find any information about this in the docs. Also I could not find what does `pk` returning null mean. Either this information looks to be quite hard to find in docs or is just absent :(

**Comment by mkaput** [comment]
`GET /api/service/connect` and `DELETE /api/service/connect` both return regular responses of format:

```js
{
  "user": /* something something or null */
}
```

**Comment by mkaput** [comment]
I made simple reproduction repo: https://github.com/mkaput/rest-hooks-issue125 :)

**Comment by mkaput** [comment]
> Ok, I cloned your repo and simulated a working backend via this code:

In `backend.js` there is a simple node server that simulates my app code. Basically, DELETE returns disconnected state object, `{ user: null }`.

> Doing this made the screen work until 'disconnect' was clicked - which deletes the current value in cache, so you get a 404 with the error you stated above.

Yup, this is the issue.

> If so you can simply use another fetch type https://resthooks.io/docs/api/FetchShape#type-read-mutate-delete as 'delete' is what results in the resource being removed.

Yes, this scenario is state mutation. So I understand that for this I must create custom fetch shapes?

**Comment by mkaput** [comment]
> Any suggestions you would have to make this more clear in the docs?

I am missing a section about what to do if the resource does not have a concept of the primary key and why `pk() { return null; }` does not work (because by my intuition `pk == null` means lack of pk and only one instance of the resource). How to cope with this, and some example.

The provided page only presents how to build fetch shape, but it is not clear from it, how to create a full resource model.

**Comment by ntucker** [comment]
Your provided resource should be fine. If you add the code I included above it should work. If you only have a single entity for a resource, returning null is fine. so is any other value.

Can you try adding the disconnectShape and tell me if it works for you?

**Comment by mkaput** [comment]
I added disconnectShape and it works as I expect now.

But setting `pk == null` still does not work and results in:

> Error: Missing usable resource key when normalizing response.
>
> This is likely due to a malformed response.
> Try inspecting the network response or fetch() return value.

This error does not appear when I leave `pk == 1`.

I pushed my code state to the repository: https://github.com/mkaput/rest-hooks-issue125/commit/be1d3abfe77f6107a561f37f55c5122232165d53

**Comment by ntucker** [comment]
Oh right, null is an allowable response from pk() in that it indicates it did not find a primary key. https://github.com/coinbase/rest-hooks/blob/master/src/resource/SimpleResource.ts#L18 is what threw that error.

Typically I name my singleton resources with a string for the pk like

```typescript
  pk() {
    return 'the_only_one';
  }
```

I find that makes it clear there's only supposed to be one entry in the cache, which makes debugging the cache a bit easier

![Screen Shot 2019-08-28 at 1 41 20 PM](https://user-images.githubusercontent.com/866147/64065698-a270f200-cbde-11e9-8df6-35a8ac2e83f4.png)

**Comment by ntucker** [comment]
Added some docs for singleton Resources https://github.com/coinbase/rest-hooks/commit/04d8e0c1889d9a180063170dd3485f4dd0fd4910

Tell me if you think that will be helpful!

**Comment by mkaput** [comment]
## Pk

> What led you to believe that null should be acceptable? I can try to clear up the docs to make this easier. Perhaps I should add a 'singleton' example as well.

I assumed this because in section: https://resthooks.io/docs/api/resource#pk-string-number-null

> `pk: () => string | number | null`
>
> PK stands for primary key and is intended to provide a standard means of retrieving a key identifier for any Resource. In many cases there will simply be an 'id' field member to return. In case of multicolumn you can simply join them together.

Typings say that pk can return null, but there is no metion here that this value means absence of such, which I understand now is an erroneous state in this lib:

> Oh right, null is an allowable response from pk() in that it indicates it did not find a primary key. 

I wonder whether it would result in more clean API if null would mean _this resource does not have any kind of pk_, while errors would be communicated via throwing errors, e.g.:

```js
class NoPkButImFine extends Resource {
  pk() { return null; }
}

class Ouch extends Resource {
  pk() { throw new Resource.MissingPkError(); }
}
```

## Docs

> What there is only ever once instance of a Resource for your entire application?

Looks like there is typo here. Maybe:

> What if there is only ever one instance of a Resource for your entire application?

**Comment by St1myL** [comment]
The same issue

**Comment by ntucker** [comment]
@St1myL does https://resthooks.io/docs/api/resource#singleton-resources not work for you?

**Comment by St1myL** [comment]
@ntucker , oups, just fixed, thank you!

**Comment by ntucker** [comment]
@mkaput Ok, fixed the typo and added a paragraph about null meaning https://resthooks.io/docs/api/resource#pk-string-number-null

Considering this closed for now, but feel free to open new issues for unresolved related things!
