### ISSUE TITLE
Provide a better way to mock in stories

### ISSUE THREAD

**Issue by christophehurpeau** [coinbase/rest-hooks#13]
This is in the readme: "📙 Storybook mocking"

We're using a component for now:

```ts
import React from 'react';
import { StateContext } from 'rest-hooks/lib/react-integration/context';

export interface MockResultsProps {
  results: Record<string, any>;
  children: React.ReactNode;
}

export default function MockResults({ results, children }: MockResultsProps) {
  const mockState = {
    entities: {},
    results,
    meta: {},
  };
  return <StateContext.Provider value={mockState}>{children}</StateContext.Provider>;
}
```

Usage:

```js
const mockResults = {
  'http://localhost:5001/api/thing/1': { id: 1 },
};

storiesOf('things', module).add('Thing', () => {
  return (
    <MockResults results={mockResults}>
      <Thing id={1} />
    </MockResults>
  );
});
```

**Comment by ntucker** [comment]
What about entities though?

**Comment by ntucker** [comment]
Thanks for sharing! Does this work for <Thing/> if it's trying to retrieve an entity?

My current thoughts on design for this would be to provide url->response as arguments and then they'd be transformed by rest-hooks into the context store.

**Comment by christophehurpeau** [comment]
Yes actually it was only an example and we do something more like this:

```
const mockResults = {
  'http://localhost:5001/api/thing/1': ThingResource.fromJS({ id: 1 }),
};
```

**Comment by ntucker** [comment]
Update from me: I'm in crunch mode for some product work at end of the quarter, so I haven't been able to build this yet.

However, I am curious what your ideas are for the perfect/ideal API to mock the data?

**Comment by christophehurpeau** [comment]
Without a lot of thinking, the ideal api to mock the data should:

- be able to mock a loading state
- be able to mock results easilly
- have an api to switch from loading to results and results to other results

Perhaps something like (but could have better names):

```
// render loading state
render(
<MockResults>
  <Component />
</MockResults>
);

// render results
render(
<MockResults initialValues={{ '/some-url': someValues }}>
  <Component onClick={onClick} />
</MockResults>
);

// render loading then change results
const initialValues = {};
const manager = new MockManager(initialValues);
render(
<MockResults manager={manager}>
  <Component />
</MockResults>
);
// do snapshot and then
manager.change({ '/some-url': someValues });
// do another snapshot
```

**Comment by christophehurpeau** [comment]
After some issues, our `MockResults` now looks like this:

```jsx
import React from 'react';
import { StateContext } from 'rest-hooks/lib/react-integration/context';
import reducer, { initialState } from 'rest-hooks/lib/state/reducer';
import { ReadShape } from 'rest-hooks';

export interface MockResultsProps {
  results: ({ request: ReadShape<any, any, any>; params?: object; result: any })[];
  children: React.ReactNode;
}

export default function MockResults({ results, children }: MockResultsProps) {
  const now = Date.now();
  const mockState = results.reduce((acc, { request, params, result }) => {
    const { schema, getUrl } = request;
    const url = getUrl(params);
    return reducer(acc, {
      type: 'receive',
      payload: result,
      meta: { schema, url, date: now, expiresAt: now * 2 },
    });
  }, initialState);
  return <StateContext.Provider value={mockState}>{children}</StateContext.Provider>;
}

```

Usage:

```jsx

const mockResults = [
  {
    request: SomeResource.listRequest(),
    params: { prop: 10 },
    result: someResourceResultMock,
  },
];


storiesOf('name', module).add('Name', () => {
  return (
    <MockResults results={mockResults}>
      <Component />
    </MockResults>
  );
});

```

**Comment by ntucker** [comment]
How do you set whether it's loading, just removing the result from the list?

**Comment by christophehurpeau** [comment]
@ntucker do you mean with our current MockResults implementation or ideally ?

**Comment by ntucker** [comment]
Originally thinking the former, but both would be helpful.

**Comment by ntucker** [comment]
I'm imagining a simple MockNetworkManager that uses data fixtures when intercepting any 'fetch' and then issues the appropriate 'receive' action. However, I wasn't really imagining handling loading states. I imagine you would maybe want to toggle it using a knob?

**Comment by ntucker** [comment]
Also, I noticed you only provide the StateContext - is DispatchContext still provided somehow?

PS) Got some new basic docs on managers: https://github.com/coinbase/rest-hooks/blob/master/docs/api/NetworkManager.md

**Comment by christophehurpeau** [comment]
with our current not providing the result work
we don't change the stories but write new ones instead, to catch all cases in [percy](https://percy.io/) snapshots
we don't provide DispatchContext as we don't use it, it works without

the new doc is so much more nice :) https://coinbase.github.io/rest-hooks/

**Comment by ntucker** [comment]
Glad you like the new docs :)

Feel free to add your project https://coinbase.github.io/rest-hooks/users.html -> 'add your company'

**Comment by ntucker** [comment]
Made some progress: https://github.com/coinbase/rest-hooks/tree/mock-utils Gotta add docs and figure out the export strategy.

**Comment by ntucker** [comment]
Can you see how https://github.com/coinbase/rest-hooks/releases/tag/1.5.0-beta.3 works for you?
