### ISSUE TITLE
Getting result after 400 <Bad Request> (POST)

### ISSUE THREAD

**Issue by St1myL** [coinbase/rest-hooks#130]
I have a simple password change form. When I submit request and, for example, one input value was incorrect, the request will be 400 Bad Request. After that I should get an error object like that:

```
{
  "status": "error",
  "error": {
    "type":" validation_error",
    "status_code":400, 
    "params": [
      {
        "code": "password_does_not_meet_requirements",
        "message": "Password does not meet requirements"
      }
    ]
  }
}
```

But I can't get the result. I tried like that using `.then()`:

```
const post = useFetcher(ChangePasswordResource.createShape());

<Form onSubmit={(values) => {
  return post(values, {}).then(data => console.log(data)
}} />
```
--------------------------------------------------
Based on this, should I create own custom Post and how?

**Comment by ntucker** [comment]
All network errors should cause the promise to reject. Try doing .catch instead of .then

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch

**Comment by St1myL** [comment]
@ntucker yes, I know about `.catch ()`, but in the catch I can not get the result from the server that I would like to receive. Is it possible?

**Comment by ntucker** [comment]
What shows up in the error is up to your fetch implementation. By default the body and all should still be there. If you're using the default fetch from `Resource` then the [superagent docs](http://visionmedia.github.io/superagent/#error-handling) should be helpful in understanding the error shape.

If you want to grab there error somewhere else besides the catch, you can always `useError()` and it will retrieve the same error that was thrown.

**Comment by St1myL** [comment]
@ntucker well, it clarified something for me. Last question, how to use hook that you mentioned? I did not find it in docs  ¯\_(ツ)_/¯

**Comment by ntucker** [comment]
Actually, useMeta() is probably better to use. just send in same params as a useResource:

```js
const { error } = useMeta(ChangePasswordResource.createShape(), {});
```

**Comment by St1myL** [comment]
@ntucker oh, ok. Bad that I can't grab error from body, thank you for explanation!

**Comment by ntucker** [comment]
I don't get what you mean by grab error from body. On error, the parameter will be error rather than body. So you'll grab body from error. Then you can grab your error member from that body.

```js
const post = useFetcher(ChangePasswordResource.createShape());

<Form onSubmit={(values) => {
  return post(values, {}).catch(error => console.log(error.response.body));
}} />
```

would output
```json
{
  "status": "error",
  "error": {
    "type":" validation_error",
    "status_code":400, 
    "params": [
      {
        "code": "password_does_not_meet_requirements",
        "message": "Password does not meet requirements"
      }
    ]
  }
}
```

**Comment by St1myL** [comment]
This is what I definitely wanted. Thank u very much !:)
