### ISSUE TITLE
Use of default <CacheProvider /> makes react-native apps crash

### ISSUE THREAD

**Issue by martinezleoml** [coinbase/rest-hooks#1306]
**React native version** : 0.63.4

**Concurrent mode** : no

**Rest Hooks version**  : 6.1.0

**Describe the bug**
Use of default `<CacheProvider />` makes React Native app crash.

```Text strings must be rendered within a <Text> component.```

**To Reproduce**
Simply follow the getting started guide : https://resthooks.io/docs/getting-started/installation#add-provider-at-top-level-component

**Comment by ntucker** [comment]
try [6.1.1](https://www.npmjs.com/package/rest-hooks/v/6.1.1)

**Comment by angelopedroso** [comment]
Im that error as well;

**Comment by ntucker** [comment]
> Im that error as well;
> 

What version was this?

**Comment by angelopedroso** [comment]
@data-client/react : 0.12.9, apparently is the new "rest hook"

**Comment by ntucker** [comment]
Thanks! Do you possibly have a stack trace? This would make it faster to get a fix out

**Comment by angelopedroso** [comment]
```
ERROR  Error: Text strings must be rendered within a <Text> component.

This error is located at:
    in span (created by Loading)
    in div (created by Loading)
    in Loading (created by CacheStore)
    in Suspense (created by CacheStore)
    in CacheStore (created by CacheProvider)
    in CacheProvider (created by Page)
    in RCTView (created by CssInterop.View)
    in CssInterop.View (created by Page)
    in Page
    in Unknown (created by Route(index))
    in Suspense (created by Route(index))
    in Route (created by Route(index))
    in Route(index) (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by QualifiedSlot)
    in QualifiedSlot (created by Slot)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by QualifiedNavigator)
    in QualifiedNavigator (created by Navigator)
    in Navigator (created by Slot)
    in Slot (created by Layout)
    in Layout
    in Unknown (created by Route())
    in Suspense (created by Route())
    in Route (created by Route())
    in Route() (created by ContextNavigator)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by wrapper)
    in wrapper (created by ContextNavigator)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by ContextNavigator)
    in ContextNavigator (created by ExpoRoot)
    in ExpoRoot (created by App)
    in App (created by ErrorOverlay)
    in ErrorToastContainer (created by ErrorOverlay)
    in ErrorOverlay (created by withDevTools(ErrorOverlay))
    in withDevTools(ErrorOverlay)
    in RCTView (created by CssInterop.View)
    in CssInterop.View (created by AppContainer)
    in RCTView (created by CssInterop.View)
    in CssInterop.View (created by AppContainer)
    in AppContainer
    in main(RootComponent), js engine: hermes
```

**Comment by ntucker** [comment]
@angelopedroso What build system are you using? It seems to not be picking up the .native extension https://github.com/reactive/data-client/blob/master/packages/react/src/components/BackupLoading.native.js and instead using https://github.com/reactive/data-client/blob/master/packages/react/src/components/BackupLoading.tsx

**Comment by angelopedroso** [comment]
I'm using expo, building in android assemble release

**Comment by ntucker** [comment]
@angelopedroso does that include metro? https://reactnative.dev/docs/platform-specific-code#native-specific-extensions-ie-sharing-code-with-nodejs-and-web I think it's supposed to be the default in expo but I haven't been able to setup a project myself to test.

**Comment by ntucker** [comment]
Let's continue discussion on #3079
