### ISSUE TITLE
[fix] Handling suspense properly in Hooks tests

### ISSUE THREAD

**Issue by Zizzamia** [coinbase/rest-hooks#131]
In Hooks tests, we're not handling suspense properly so react complains.
When upgrading test util we should be able to fix this as we'll suspense ourselves.

https://github.com/coinbase/rest-hooks/blob/f6f0a5339ef5068a0e49f4a45f5c49c2a6c3b3aa/src/react-integration/__tests__/hooks.tsx#L514

and

https://github.com/coinbase/rest-hooks/blob/f6f0a5339ef5068a0e49f4a45f5c49c2a6c3b3aa/src/react-integration/__tests__/hooks.tsx#L538

**Comment by ntucker** [comment]
Might be helpful to actually point to the TODO line in the code embed, rather than the line after.
