### ISSUE TITLE
Delete return symbol on useRessource

### ISSUE THREAD

**Issue by rtorrente** [coinbase/rest-hooks#1312]
**React version** 16.13.0

**Rest Hooks version** (e.g., 4.5.9) 6.1.1

**Describe the bug**

When you delete an entity on a resource that is actually used on a useResource list hooks, the value of the entity in useResource array is `Symbol(ENTITY WAS DELETED)` instead of being juste delete from array.

This lead to a component crash because component is waiting for a EntityType[] (like send by useResource hook) and it receive another type. There is no typescript error that can help to see bug before because the useResource hook register an EntityType[]

**To Reproduce**

1) Have a useResource var in a component like `const list = useResource(Entity.list(),{}) `

2) list is annouced by typescript to be Entity[]

3) Delete an entity with fetch on Entity.delete()

4) App is crashing because for exemple list[0].name is not available with "TypeError: Cannot read property 'name' of undefined" because in list array there is `Symbol(ENTITY WAS DELETED)` on list[0]

**Expected behavior**

Delete of the entity on the list array or param to get only valid Entity on useResource return

Like in the doc https://resthooks.io/docs/api/Delete#impact-on-useresource

**Comment by ntucker** [comment]
Can you check your yarn.lock or package-lock.json to see if you have multiple instances of @rest-hooks/normalizr installed?

**Comment by ntucker** [comment]
If you want to include your yarn.lock or package-lock.json I could analyze it for you as well.

**Comment by ntucker** [comment]
6.1.2 should throw an error instead if my theory is correct. otherwise we might need more information to understand what's going on like resource definition and package lock file

**Comment by rtorrente** [comment]
Hello @ntucker you was right ! Thank you very much for your quick assistance, you avoid me a big headache 

The package was not directly installed by me, but by other rest-hooks packages (In this example by @rest-hooks/test). When I follow the guide to upgrade from 5 to 6, it tell me to upgrade only "rest-hooks" to 6.

For suggestion, as an user, the new package separation brings a lot of packages and it look difficult to understand which version of packages goes with others. Upgrades are not very user friendly because other package (rest, test) have a permissive compatibility with other version but this can lead to different version of subpackage installed.

Maybe a page in documentation to explain this or a commun package numerotation could help ?

**Comment by ntucker** [comment]
@rtorrente Thanks for the update on what happened here. The idea of split packages is *supposed* to make it easier to upgrade as you can incrementally do each piece separately. I think the problem here may be due to weird package manager behavior. What package manager and version do you use? npm 7?

@rest-hooks/test shouldn't be installing any version of @rest-hooks/normalizr, since it is marked as a peerDep here: https://github.com/coinbase/rest-hooks/blob/master/packages/test/package.json#L97 If my theory is correct this is a bug in npm 7.

**Comment by ntucker** [comment]
Oh unless the version of @rest-hooks/test is so old it isn't compatible with rest hooks 6. What version of @rest-hooks/test did you run before?

**Comment by rtorrente** [comment]
Hello,

My package manager is effectively npm 7 and it resolve peerDev it seem


At the moment of the bug, I was on react-hook 5 and I upgrade to 6. 

Before upgrade I had on package.json

```
"@rest-hooks/rest": "^2.1.2",
"rest-hooks": "^5.1.0"
```


I did "npm install react-hook@6" but compilation failed. I checked documentation (https://resthooks.io/docs/getting-started/installation) and I saw that there is new packages that I don't use for the moment and I try to install @rest-hooks/test @rest-hooks/hooks

After, there is my package.json


```
 @rest-hooks/hooks": "^2.1.0",
    "@rest-hooks/rest": "^3.0.0",
    "@rest-hooks/test": "^7.1.0",
    "rest-hooks": "^6.1.1",
```

Bug appear at this moment

**Comment by ntucker** [comment]
Thanks for the details. I think this is due to the || in peerdeps as npm 7 bugs out around that forcing install based on its shoddy algorithm instead of finding existing versions installed. I'm updating the upgrade instructions to hopefully help others.

Were you able to deduplicate the @rest-hooks/normalizr package? I was thinking maybe if you uninstall everything then install at once it might work but not sure.

**Comment by ntucker** [comment]
I added package info at top of the instructions https://resthooks.io/docs/upgrade/upgrading-to-6 hopefully this makes it easier for everyone. Thanks again for reporting I'm sure many people will be happy this was resolved :)

**Comment by rtorrente** [comment]
Hello @ntucker 

Sorry for the slow answer, it's good with uninstall and install again, thanks for your updating of docs
