### ISSUE TITLE
Incorrect React Suspense fallback component is used

### ISSUE THREAD

**Issue by LentnerStefan** [coinbase/rest-hooks#14]
**Describe the bug**
Not sure if it's a bug or me misunderstanding something, but I'm having difficulties locally handling loading state with React's Suspense in my App. 
The top level Suspense fallback is used even if there is a closer use of Suspense .

My main App.js is : 

```jsx
    <RestProvider manager={manager}>
      <BrowserRouter>
          <NetworkErrorBoundary fallbackComponent={NetworkErrorPage}>
            <Suspense fallback={<Loader color='blue' />}>
              <AppRouter />
            </Suspense>
          </NetworkErrorBoundary>
      </BrowserRouter>
    </RestProvider>
```
One of the routes : 
```jsx
const myRouteExample = () => 
(
        <Suspense fallback={<Loader color='red'/>}>
          <AccountManagerSelect onSave={onSave} />
        </Suspense>
)
```

The account manager component : 
```jsx
const AccountManagerSelect = () => {
  const accountManagers = useResource(AccountManagerResource.listRequest(), {})
  return (
     <div>
        {accountManagers.map(am => <div>{am.firstname}</div>}
     </div>
  ) 
}
```

While the accountmanagers list is fetched, the Top level Loader is shown :/ ( blue color )

However, if I add a simple toggle to display the component after a button click : 

```jsx
const myRouteExample = () => {
  const [showAM, setShowAM] = useState(false);
return (
     {showAM ? (
        <Suspense fallback={<Loader />}>
          <AccountManagerSelect onSave={onSave} />
        </Suspense>
      ) : (
        <Button
          onClick={() => {
            setShowAM(true);
          }}
        >
          TEST
        </Button>
      )}
}
```
Upon clicking the test Button, the correct loader is displayed ( red color ) ! 

Is there something I'm not getting ? 
Thank you !

**Expected behavior**
The closest Suspense fallback should be used.

**Comment by ntucker** [comment]
Are you using react-router? My first instinct is that your route render might not be reapplying (https://reacttraining.com/react-router/web/guides/dealing-with-update-blocking). This seems to align with the button click part working.

**Comment by ntucker** [comment]
Also, are you using any optimizations that might be turning your react components into inline function calls?

**Comment by ntucker** [comment]
if you could setup a stackblitz demo like https://stackblitz.com/edit/rest-hooks then I could help look into your issue

**Comment by LentnerStefan** [comment]
I couldn't reproduce the bug in your demo, it was working as intended. 
So I've started looking for differences with my App and I have found the culprit.


My app is injected in the dom this way ( I followed your [documentation](https://github.com/coinbase/rest-hooks/blob/master/docs/getting-started/installation.md#2-add-provider-at-top-level-component) )  : 
```js
import { RestProvider } from 'rest-hooks';
import ReactDOM from 'react-dom';

declare module 'react-dom' {
  // eslint-disable-next-line @typescript-eslint/camelcase
  function unstable_createRoot(
    element: HTMLElement | null
  ): { render(reactElement: ReactElement): void };
}

ReactDOM.createRoot(document.body).render(
  <RestProvider>
    <App />
  </RestProvider>,
);
```

I've changed this to  : 
```js
import { RestProvider } from 'rest-hooks';
import { render } from 'react-dom';

render(<RestProvider><App /></RestProvider>, document.getElementById('root'));
```

And now the correct Suspense fallback is used !
I'm not sure what the implications are of using createRoot, but that did the trick !

Thanks for your time !

**Comment by ntucker** [comment]
Oops, that was my bad for accidentally suggesting new unstable things in the docs. This can cause issues with older APIs like old-context used in react-router v4.

I updated the installation docs you linked to with the recommended way of hooking up react dom.
