### ISSUE TITLE
Accessing context in fetch

### ISSUE THREAD

**Issue by yunyu** [coinbase/rest-hooks#142]
**Is your feature request related to a problem? Please describe.**
I want to make a base resource that causes the user to log out when a 401 is encountered. The authorization state is currently implemented as a top-level context provider, and there is currently no way to adjust it and trigger a rerender inside rest-hooks (unless I write a wrapper hook for all the exported hooks). 

**Describe the solution you'd like**
I actually don't know how to cleanly make this work with the current API.

**Describe alternatives you've considered**
Wrapping all the use* hooks with a useEffect that accesses the context.

**Comment by yunyu** [comment]
Going to close this issue, just realized I can make this work with a custom error boundary :)

**Comment by ntucker** [comment]
Alternatively you can hook directly into the dispatches via [Manager](https://resthooks.io/docs/api/Manager):

```
import { Manager } from 'rest-hooks';

class AuthManager implements Manager {
  cleanup() {}
  getMiddleware = memoize(function<T extends NetworkManager>(this: T) {
    return <R extends React.Reducer<any, any>>({
      dispatch,
    }: MiddlewareAPI<R>) => {
      return (next: React.Dispatch<React.ReducerAction<R>>) => (
        action: React.ReducerAction<R>,
      ) => {
        switch (action.type) {
          case 'rest-hooks/purge':
          case 'rest-hooks/rpc':
          case 'rest-hooks/receive':
            if (action.error && action.payload.status === 401) {
              // TODO: dispatch auth system
            }
          default:
            next(action);
            return;
        }
      };
    };
  });
}
```

This has the advantage of not causing double renders if your reaction to 401 would cause a render. This is because the hook throwing the network error can only do so after the commit stage (when DOM is updated). Manager middleware is run during render (before commit) so it can trigger other render updates to be in the same commit batch.

**Comment by yunyu** [comment]
@ntucker Good to know, thanks!

**Comment by St1myL** [comment]
@ntucker I can't import a MiddlewareAPI type to a file (TS2305: Module "../node_modules/rest-hooks/lib" has no exported member "MiddlewareAPI"). I have the latest version of rest-hooks.

**Comment by ntucker** [comment]
https://github.com/coinbase/rest-hooks/pull/139/files#diff-f41e9d04a45c83f3b6f6e630f10117feR107 coming soon. You can just copy the type from the code for now
