### ISSUE TITLE
Declarative way of forcing a refetch

### ISSUE THREAD

**Issue by yunyu** [coinbase/rest-hooks#143]
**Is your feature request related to a problem? Please describe.**
Currently, we are able to force a refetch with useFetcher (but the API is imperative, which kinda defeats the point). I would like to be able to trigger a refetch on mount with the useResource API for things that need to be up-to-date when displayed.

**Describe the solution you'd like**

Something similar to Apollo's fetchPolicy parameter: https://www.apollographql.com/docs/tutorial/queries/#customizing-the-fetch-policy

**Describe alternatives you've considered**
A custom hook wrapping useFetcher, presenting the same API as useResource.

**Comment by ntucker** [comment]
[dataExpiryLength](https://resthooks.io/docs/guides/resource-lifetime) customizes how often it refetches. I don't recommend anything less than 500ms for this.

If you want to never display 'stale' values, you can try [invalidIfStale](https://resthooks.io/docs/api/FetchShape#invalidifstale-boolean)

**Comment by yunyu** [comment]
@ntucker I'd like to retain the normal cache behavior for most resources, but have fetch-on-mount for a specific few. From the docs, it looks like that doing something like `useResource({...MyResource.detailShape(), options: { dataExpiryLength: 0}}, params)` would work?

**Comment by yunyu** [comment]
@ntucker That works for me, except there are situations where I may not want this behavior for all usages of a resource. Would it be possible for the params to be passed to getRequestOptions?

**Comment by ntucker** [comment]
Several ways you could do this depending on how special-case it is:

Custom endpoint:

```typescript
class MyResource extends Resource {
  static getRequestOptions() {
    return { dataExpiryLength: 100 };
  }
  static cachedDetailShape() {
    const shape = this.detailShape();
    return {
      ...shape,
     options: {
      ...shape.options,
      dataExpiryLength: 60000,
    }
  }
}
```

This can be useful if it's based on a particular fetch you might do, rather than the Resource you're fetching. It can also be useful if there's only two configurations for the same endpoint to avoid putting the specific numbers in your hook calls.

### FetchShape parameters

If you're configuration is really on a case-by-case basis. (Extremely rare) Then you can definitely take params to customize it.

```typescript
class MyResource extends Resource {
  static getRequestOptions() {
    return { dataExpiryLength: 100 };
  }
  static detailShape({ dataExpiryLength }) {
    const shape = super.detailShape();
    return {
      ...shape,
     options: {
      ...shape.options,
      dataExpiryLength,
    }
  }
}
```

**Comment by ntucker** [comment]
@yunyu did this work for you?

**Comment by yunyu** [comment]
@ntucker Yep, I'm going to close the issue. I still feel like the ergonomics could be improved, however.

**Comment by ntucker** [comment]
Have any ideas for ergonomic improvements? Or specific properties you find problematic with the current approach?
