### ISSUE TITLE
Windows error on build:lib command, rest-hooks package

### ISSUE THREAD

**Issue by rwest202** [coinbase/rest-hooks#1439]
https://github.com/coinbase/rest-hooks/blob/105a3f1060b9c08f9d5830f653df78f597d95eb4/packages/rest-hooks/package.json#L55

The `RESOLVER_ALIAS` environment variable is set to `'{\"^rest-hooks(.+)$\":\"./src/\\\\1.js\"}'` however this fails when run on windows.

`SyntaxError: [BABEL] C:\Users\ryanw\Documents\self\rest-hooks\packages\rest-hooks\src\index.ts: Unexpected token } in JSON at position 32 (While processing: "C:\\Users\\ryanw\\Documents\\self\\rest-hooks\\node_modules\\@anansi\\babel-preset\\index.js")`

Per the cross-env docs: https://www.npmjs.com/package/cross-env

![image](https://user-images.githubusercontent.com/7718824/138382260-fcad3628-e65f-41ea-bc6d-c8a7ad941f01.png)

Variable should be set to `{\\\"^rest-hooks(.+)$\\\":\\\"./src/\\\\1.js\\\"}` and it builds correctly on windows.

**Comment by ntucker** [comment]
Would love a PR that makes this work. My attempts failed. I develop exclusively on windows, but I use WSL. So if that's an option for you it should at least be a workaround. Otherwise I'd love to see how to make this work given the complexity of the commands needing to be issued.

**Comment by ntucker** [comment]
Since we're using yarn 3 (berry) now this should work fine.
