### ISSUE TITLE
Empty/Reset the cache on demand

### ISSUE THREAD

**Issue by blanchg** [coinbase/rest-hooks#145]
**Is your feature request related to a problem? Please describe.**
Some use cases require us to empty the entire cache e.g. impersonating another user currently it would require calling many invalidates and also setting the invalidIfStale flag.

**Describe the solution you'd like**
For the few instances where this is required I imagine there is a simple way to reset the entire cache with a single hook call.

**Describe alternatives you've considered**
Recreating the entire application context might be possible though it seems heavy handed :)

**Additional context**

**Comment by ntucker** [comment]
Sounds reasonable. Probably just another action type for the reducer called 'rest-hooks/reset'. Then you could trigger from a manager or hook depending on how you want to do use. Should be striaghtforward PR if you want to tackle it, otherwise I can probably get to it some time this week.

**Comment by blanchg** [comment]
Excellent, will see if I can get to it today.

**Comment by ntucker** [comment]
Available in [2.2.0-beta.0](https://www.npmjs.com/package/rest-hooks/v/2.2.0-beta.0)
