### ISSUE TITLE
Instructions for using NetworkErrorBoundary with custom fetch

### ISSUE THREAD

**Issue by yunyu** [coinbase/rest-hooks#158]
**Is your feature request related to a problem? Please describe.**
The example fetch implementation provided in the [docs](https://resthooks.io/docs/guides/custom-networking#fetch) does not support NetworkErrorBoundary. I added this code to my `fetch`:

```js
    if (!response.ok) {
      // eslint-disable-next-line no-throw-literal
      throw {
        status: response.status,
        response: {
          statusText: response.statusText,
          body: await response.json()
        }
      };
    }
```

This seems to work most of the time, but ~50% of the time (when the subtree containing NetworkErrorBoundary) rerenders, the error "escapes" the boundary:

<img width="989" alt="Screen Shot 2019-10-15 at 4 46 26 PM" src="https://user-images.githubusercontent.com/8008350/66868477-5ea63200-ef6b-11e9-9b2a-c4333616b8ce.png">

I'm going to assume this is a side effect of me not implementing `fetch` correctly, but it could be an issue with the NetworkErrorBoundary (although I can't quite see what's wrong with it). 

**Describe the solution you'd like**
A better example for supporting NetworkErrorBoundary for custom fetch implementations

**Comment by ntucker** [comment]
If the subtree containing the error boundary is being re-render is it also removing the error boundary? Unless a new fetch occurred which eliminated the error from the network, it will be throwing that error up again and need to be caught still. The error persists in the cache. So if you remove the error boundary it would 'escape'.

**Comment by yunyu** [comment]
No, but I did figure out the cause. It seems like the built-in react-overlay-error (inconsistently) pops up for things caught by a NetworkErrorBoundary: https://stackoverflow.com/a/52097626

This might be out of the project scope, but it might result in less panic if the default NetworkErrorBoundary included some styling to get rid of the error overlay in development mode.

**Comment by ntucker** [comment]
I'm pretty sure they render an iframe over everything with a super high z-index. Trying to fight they overlaying everything is a pointless battle. There might be a way to configure what errors it grabs, but the docs are non-existant. If we can figure out how to do configuration, then we could add a docs page to help others configure it properly. Otherwise, like you said, it's out of scope of rest hooks since this is going to happen for any errors.
