### ISSUE TITLE
[docs] SSR guide

### ISSUE THREAD

**Issue by ntucker** [coinbase/rest-hooks#172]
**Describe the solution you'd like**
Include multiple methods like:
- react-lightyear
- simply using the suspense fallback mechanism and not loading any data
- integration with things like after.js (using something similar to https://resthooks.io/docs/guides/no-suspense)

Ideally example code will have been tested.

**Comment by ntucker** [comment]
Will come soon but don't want lingering issues.

**Comment by lgodziejewski** [comment]
Hey, I'm trying to integrate `rest-hooks` with a Next.js app and obviously it crashes on:
> Error: ReactDOMServer does not yet support Suspense.

I guess I have to use the `useStatefulResource()` from the link above?

Perhaps I could assist with writing the SSR docs?

**Comment by ntucker** [comment]
There's a few ways to do this, and we'd be happy to accept contributions for the way that works best for you.

With next.js it expects pass getInitialProps() in. This can work, by reading those props if they exist, else fallback to the value from useStatefulResource(). This is probably the easiest way to integrate. However, it does have a downside (tho that's true of anything using getInitialProps()) - in that it doesn't prime the cache, so navigating back and forth it will have to fetch still, which brings us to the second way.

`<CacheProvider />` takes `initialState`, which means you if you serialize the cache from SSR, then on client you can deserialize and load it via `initialState`. https://resthooks.io/docs/next/api/CacheProvider This requires a bit more orchestration, but has the advantage of priming the cache. In this case, you can just ignore the initialProps stuff - but it's still important to fetch in there. To achieve this you will likely need to use a redux backend so the store can be external.

Lastly a note about suspense. If you use the experimental react release, it will actually work with suspense, and simply display the fallback at all times when doing SSR. This allows you to useResource() instead of useStatefulResource() - however it does mean you'll need to do a two pass render. This is the best future proofing methodology.

**Comment by lgodziejewski** [comment]
Thanks! I actually don't need fetching in ssr (not yet at least), so `useStatefulResource` or the 2nd way you've mentioned (experimental React) should be fine.

I'm also struggling to integrate with a json-api api (just a simple one actually, eg:
```
{
  data: {  <-- here could be either an object or an array of objects
    id: '123',
    attributes: { fieldA, fieldB, fiedC },
  }
}
```

I tried to manually set the schema but didn't succeed - K don't want to spam this issue so perhaps I should open a new one?

**Comment by ntucker** [comment]
https://resthooks.io/docs/next/api/Union should model two different possible data types showing up somewhere

**Comment by ntucker** [comment]
The latest version of NextJS supports React suspense, thus a [guide for SSR](https://resthooks.io/docs/guides/ssr) has been added. It includes NextJS as well as React 18 usage with express.

@lgodziejewski @localjo @arthruwelkin
