### ISSUE TITLE
StateContext entities only use string urlRoot and not the complete root url

### ISSUE THREAD

**Issue by christophehurpeau** [coinbase/rest-hooks#18]
**Describe the bug**

Our resource urls:

> /instructors/:id
> /instructors/:id/locations
> /instructors/:id/administrative-information

All have the same urlRoot:

```
  static urlRoot = `${process.env.REACT_APP_API_URL}/instructors`;
```
and the instructor id is set in the `url` or `listUrl`:

```tsx
export default class LocationResource extends Resource {
  static listUrl<T extends typeof Resource>(this: T, params: Readonly<ListUrlParams>) {
    return `${InstructorResource.urlRoot}${params.instructorId}/locations`;
  }
}
```

```tsx
export default class AdministrativeInformationResource extends Resource {
  static url<T extends typeof RestHooksResource>(this: T, params?: Readonly<any>): string {
    return `${AdministrativeInformationResource.urlRoot}/${
      params.instructorId
    }/administrative-information`;
  }
```

The problem is that the entities cache puts them in the same object as shown in the screenshot taken from the react tool: 
<img width="486" alt="Capture d’écran 2019-03-26 à 15 45 22" src="https://user-images.githubusercontent.com/302891/55008685-9eaec300-4fe1-11e9-8036-25cbcd1e0972.png">

We don't yet have conflicts on ids, but i'm guessing that when it will be the case it could be a problem ?

Should we "trick" the system by setting a different urlRoot or be able to set urlRoot as a function with params ?

Note: as you can see in the image, actually they doesnt all have the same urlRoot: the InstructorResource has instead: 

```
static urlRoot = `${process.env.REACT_APP_API_URL}/instructors/`;
```

**Comment by ntucker** [comment]
You'll need to override `getKey()`

https://github.com/coinbase/rest-hooks/blob/master/src/resource/Resource.ts#L115

Currently it just uses urlRoot, which means you need a unique urlRoot for each thing. However, if you want to keep the same url route, then simply overriding getKey() so its still unique should do the trick.


In the future I want to generate a unique symbol for each one so this is handled automatically, but I'm blocked on support from a third party library.

**Comment by christophehurpeau** [comment]
Thank you !

**Comment by ntucker** [comment]
Updated the docs since I forgot to include: https://github.com/coinbase/rest-hooks/commit/e542acd160ef629996572fc11215b94ce0129c7b

Thanks for bringing this to my attention :)
