### ISSUE TITLE
Move useStatefulResource into the library itself

### ISSUE THREAD

**Issue by yunyu** [coinbase/rest-hooks#180]
**Is your feature request related to a problem? Please describe.**
The useStatefulResource hook is not that big, can probably be tree-shaken, and feels like it belongs in rest-hooks itself (esp now that it relies on internals). The reason I'm asking this is that the types seem to break periodically, and importing my own implementation feels kind of weird.

(Don't worry: I'm actually using this for stuff that doesn't make too much sense with suspense, like showing loading states in tables)

**Describe the solution you'd like**
Make useStatefulResource an export from 'rest-hooks'

**Comment by ntucker** [comment]
What if this was released as another package like `@rest-hooks/legacy`

**Comment by yunyu** [comment]
Would be happy with that as well

**Comment by ntucker** [comment]
https://resthooks.io/docs/guides/no-suspense has been updated to refer to the new package [@rest-hooks/legacy](https://www.npmjs.com/package/@rest-hooks/legacy)
