### ISSUE TITLE
Type 'DenormalizeNullable<S>' is not assignable to type 'SchemaOfCore<S>'.ts(2345)

### ISSUE THREAD

**Issue by binary64** [coinbase/rest-hooks#181]
**React version** (e.g., 16.8.5)
16.12.0

**Concurrent mode** yes/no
not sure

**Describe the bug**
Your example 'Without suspense' doesnt compile on typescript 3.7.x

**To Reproduce**
1. copy your without suspense example
2. into a typescript 3.7.x project

**Expected behavior**
No ts errors

**Additional context**
```Type 'DenormalizeNullable<S>' is not assignable to type 'SchemaOfCore<S>'.ts(2345)```

**Comment by ntucker** [comment]
Will be publishing a fixed version under `@rest-hooks/legacy` soon

**Comment by ntucker** [comment]
https://resthooks.io/docs/guides/no-suspense should have updated version that works with rest-hooks v3 and above. (This will not work with v2)
