### ISSUE TITLE
[v3.0.0] schemaLegacy.d.ts missing in package

### ISSUE THREAD

**Issue by skoging** [coinbase/rest-hooks#192]
**React version** (e.g., 16.11.0)

**Concurrent mode** no

**Describe the bug**

It appears that `/src/resource/schemaLegacy.d.ts` is not copied to the output folder ([browse the package files on yarnpkg.com](https://yarnpkg.com/en/package/rest-hooks?files)), making TypeScript build fail since it's referenced in `/src/resource/types.ts`.

```
$ tsc
../../../../node_modules/rest-hooks/lib/resource/types.d.ts:2:84 - error TS2307: Cannot find module './schemaLegacy'.

2 import { SchemaList as SchemaListLegacy, SchemaDetail as SchemaDetailLegacy } from './schemaLegacy';
                                                                                     ~~~~~~~~~~~~~~~~
```

**To Reproduce**

**Expected behavior**
All necessary files should be present in published package, or the build will fail.

**Additional context**
The TypeScript compiler doesn't copy *d.ts files to the output filder by default: https://stackoverflow.com/questions/56018167/typescript-does-not-copy-d-ts-files-to-build

**Comment by skoging** [comment]
This appears to have happened do to the `normal.d.ts` rename to `schemaLegacy.d.ts` in #167.

The build script was not updated accordingly to copy the correct file: https://github.com/coinbase/rest-hooks/blob/ff156d3de23f22c9c6d616f8145d5c5bedfc3aa5/package.json#L25

**Comment by skoging** [comment]
I've got a fix on a branch here: https://github.com/skoging/rest-hooks/tree/bugfix/missing-type-file, and I'd make a pull request, but I there's no 3.0 maintenance branch I can target?

@ntucker Any chance you can fix this and get a patch release out? This is currently the only thing blocking us from upgrading to 3.0.

**Comment by ntucker** [comment]
I'll create a 3.0 branch shortly. Thanks for the work!

**Comment by ntucker** [comment]
https://github.com/coinbase/rest-hooks/tree/3-maintenance will be the branch

**Comment by skoging** [comment]
Fantastic! PR is up 👍

**Comment by ntucker** [comment]
https://www.npmjs.com/package/rest-hooks/v/3.0.1 released!
