### ISSUE TITLE
[docs] Typescript highlighting is broken

### ISSUE THREAD

**Issue by Semigradsky** [coinbase/rest-hooks#193]
https://resthooks.io/docs/guides/resource-types

![image](https://user-images.githubusercontent.com/1198848/70237463-4dfa8700-1778-11ea-8e29-4ed7f227b7c0.png)

Error in console:
```
inject.js:1 Uncaught TypeError: Cannot read property 'tokenizePlaceholders' of undefined
    at inject.js:1
    at Object.run (inject.js:1)
    at Object.highlight (inject.js:1)
    at Object.highlightElement (inject.js:1)
    at Object.highlightAllUnder (inject.js:1)
    at highlightAll (inject.js:1)
```

**Comment by ntucker** [comment]
Thanks for the report!

What exact browser & version are you running? I can't reproduce this myself.

**Comment by Semigradsky** [comment]
Oh sorry, this error was caused by installed extension...
