### ISSUE TITLE
Add missing PromiseifyMiddleware export

### ISSUE THREAD

**Issue by casey-chow** [coinbase/rest-hooks#196]
I was trying to combine rest-hooks with redux so that I could inspect the cache and persist it offline, and noticed that [the instructions](https://github.com/coinbase/rest-hooks/blob/3.0.1/docs/guides/redux.md#indextsx) called for a `PromiseifyMiddleware`, though I could only find this definition in the current source tree:

https://github.com/coinbase/rest-hooks/blob/dcb87c35f245d649202ab99419d729062cd0c338/src/test/providers.tsx#L19-L24

I presumed it was just old and tried to integrate Redux without it, but when I did so, it seems that I was left with my Suspense fallback left perpetually on the screen. Adding what I presumed was a stub `PromiseifyMiddleware` worked, so I presume it was just never properly exported from the root package?

**Comment by ntucker** [comment]
Which version of rest-hooks are you trying to use?

**Comment by casey-chow** [comment]
I am on 3.0.0.

**Comment by ntucker** [comment]
Fix coming out shortly. Thanks for the report!

**Comment by ntucker** [comment]
Released in https://github.com/coinbase/rest-hooks/releases/tag/3.0.2
