### ISSUE TITLE
How to create an url like `/articles/:articleId/comments` ?

### ISSUE THREAD

**Issue by christophehurpeau** [coinbase/rest-hooks#2]
Hello,

I'm struggling to understand the url builder.

It seems we can override the url when using singleRequest()
https://github.com/coinbase/rest-hooks/blob/master/src/resource/Resource.ts#L150
https://github.com/coinbase/rest-hooks/blob/master/src/resource/Resource.ts#L93-L99
 
But for listRequest, it's really limited:
https://github.com/coinbase/rest-hooks/blob/master/src/resource/Resource.ts#L167
https://github.com/coinbase/rest-hooks/blob/master/src/resource/Resource.ts#L111

Can you add a doc on how to build the url ?
Does a static method to build an url from params in the resource makes sense to you ?

Thank you,

**Comment by ntucker** [comment]
An example here: https://stackblitz.com/edit/rest-hooks?embed=1&file=resources/CommentResource.ts&hideExplorer=1&view=editor or a more complex case here https://stackblitz.com/edit/rest-hooks?embed=1&file=resources/IssueResource.ts&hideExplorer=1&view=editor

Basically you can use some of the members of searchParams to build the base url, and if you still want a querystring use the remaining to build that part of the url.

**Comment by christophehurpeau** [comment]
Thank you :)

**Comment by ntucker** [comment]
[New path template based Endpoints](https://resthooks.io/rest/api/RestEndpoint#usage)

[Rest v6 - TypeScript HTTP endpoints from url path templates](https://resthooks.io/blog/2022/10/23/Announcing-Rest-6)
