### ISSUE TITLE
Hydration mismatch when using with Next.js

### ISSUE THREAD

**Issue by nithiwatter** [coinbase/rest-hooks#2037]
**React version** (17.0.2)

**Package manager version** (npm 6)

**Node version** (14.19.1)

**Rest Hooks version** (6.3.4)

![image](https://user-images.githubusercontent.com/59894785/171558950-2425fa5a-93f2-4f38-a092-f532dab033ca.png)

**Describe the bug**
Using with Next.js produces a hydration mismatch error. Simply place `CacheProvider` in `pages/_app.js`:

![image](https://user-images.githubusercontent.com/59894785/171559200-2ff0417e-f543-436e-a481-d98913ff0e3f.png)

As recommended by Next to globally introduce providers or layouts. Then create a random page with some div:

![image](https://user-images.githubusercontent.com/59894785/171559468-dfe5ed66-b84b-499d-8d42-03baba759e0c.png)

**To Reproduce**
1. Install Next.js 12.1.5
2. Put `CacheProvider` in `pages/_app.js` as in the picture
3. Create any other page with some div ex. `pages/index.js`
4. Visit localhost to see the error (development environment - `npm run dev`). 

**Expected behavior**
No hydration mismatch as in the source code - I looked at the source and it seems like if we use React 16 or 17 and is on the server, the `Suspense` component is not injected - it is only injected via client - the problem seems to be that any page in Next refuses to be rendered as proper HTML on server, whereas it renders correctly as a div after hydration on client - hence the server html lacks a div.

**Additional context**
`Warning: Did not expect server HTML to contain a <div> in <div>. next-dev.js:25:25
    error next-dev.js:25
    React 18
    renderReactElement index.js:526
    doRender index.js:852
    _callee$ index.js:421
    Babel 8
    render index.js:412
    _callee$ index.js:407
    Babel 14
    hydrate index.js:291
    <anonymous> next-dev.js:45
    (Async: promise callback)
    <anonymous> next-dev.js:40
    NextJS 7
`

**Minimum reproducable example or test case**

**Comment by ntucker** [comment]
Suspense server side only starts working in react 18. In 17 they always render the fallback. This means you can still ssr but just nothing beyond a suspense boundary. Would it be possible to upgrade to 18 for you?

**Comment by nithiwatter** [comment]
Thank you for the reply! From what I understand, there is a check somewhere that says that if we are on version  17 and it is ssr, we will not render Suspense, so how is that a problem?

**Comment by nithiwatter** [comment]
Or are you saying that this library does not work with SSR if we are on React 17?

**Comment by ntucker** [comment]
I realize now this is an issue with a Suspense rendered inside CacheProvider itself, which prevents rendering of children in SSR in react 17/16. I will work on not rendering suspense if both conditions are detected: react < 18 & running in node. This should resolve the issue.

**Comment by ntucker** [comment]
Ahh, OK now I realize I had already done the above and the problem is the client is hydrating *with* a suspense boundary. So I somehow need to detect hydration and then not use the suspense boundary.

**Comment by ntucker** [comment]
@nithiwatter can you do me a huge favor and test this out with `@rest-hooks/core@3.2.5-beta.0` ? Without reproducable example I can't be 100% certain my change fixed this and would love your assistance here. Thanks!

**Comment by ntucker** [comment]
I tried setup myself and I'm still getting the warning even tho the SSR and client DOM 100% match.

I even altered the elements to be distinct as so:

### HTML Sent:

```html
<div id="__next" data-reactroot=""><span id="rest-hooks-SSR"><main class="Home_container__bCOhY">Hello</main></span></div>
```

### DOM:

```html
<div id="__next" data-reactroot=""><span id="rest-hooks-SSR"><main class="Home_container__bCOhY">Hello</main></span></div>
```


According to the stack trace next.js doesn't even think this is a hydration error.

**Comment by ntucker** [comment]
I realized that since suspense does not work in react < 18 and there's no mechanism in next.js to prime the cache it doesn't make sense to even render CacheProvider in the server side flow. It only makes to use it client-side. Thus I'm adding a warning in https://github.com/coinbase/rest-hooks/pull/2044 to help direct better usage patterns.

**Comment by ntucker** [comment]
The latest version of NextJS supports React suspense, thus a [guide for SSR](https://resthooks.io/docs/guides/ssr) has been added. It includes NextJS as well as React 18 usage with express.

@nithiwatter

**Comment by Frikki** [comment]
That’s all fine and dandy. However, NextJS has a new app router. Can we disregard the custom Document and App wrapper?

**Comment by ntucker** [comment]
@Frikki unfortunately the app router is not for apps with changing data; It's very confusing that they call it React as it is only for Server Side Generation (SSG), not SSR. In other words, it's like an HTML template, not a live application. The only way to do SSR is to use a system that is built for SSR, and that can be the Document wrapper for NextJS, or an alternative like [anansi](https://github.com/ntucker/anansi)
