### ISSUE TITLE
RestProvider throws on network error when trying to do a partialUpdateRequest

### ISSUE THREAD

**Issue by christophehurpeau** [coinbase/rest-hooks#21]
**Describe the bug**
```
const patchInstructor = useFetcher(InstructorResource.partialUpdateRequest());

const onSave = (values: Partial<InstructorResource>): Promise<any> => {
    return patchInstructor(values, { id: instructor.id }).catch((err) => {
      console.error(err);
    });
}
```

An invalid patch request produce this error:

```
 The above error occurred in the <RestProvider> component:
    in RestProvider (at App.tsx:22)
    in NetworkErrorBoundary (at App.tsx:21)
    in App (at src/index.tsx:6)
```

![Screenshot 2019-03-26 at 19 27 11](https://user-images.githubusercontent.com/302891/55023561-57cec680-4ffd-11e9-86a6-7d18ad47688b.png)

Result: the app crashes and we have a blank page

After using the debugger, I could see that [dispatch is called by NetworkManager](https://github.com/coinbase/rest-hooks/blob/f1e0e56cd88989121231ae284fd8288ea7e92464/src/state/NetworkManager.ts#L75) which triggers a render of react and ends up in [reducer.ts](https://github.com/coinbase/rest-hooks/blob/f1e0e56cd88989121231ae284fd8288ea7e92464/src/state/reducer.ts#L48) where it tries to normalize the error:

![Screenshot 2019-03-26 at 19 23 46](https://user-images.githubusercontent.com/302891/55023274-bba4bf80-4ffc-11e9-9b32-8b600086d4c4.png)

**Comment by ntucker** [comment]
Thanks for the very detailed report. I know what's going on and can quickly fix this. :)

**Comment by christophehurpeau** [comment]
Thank you :) When can we expect a release ?

**Comment by ntucker** [comment]
*poof* :)
