### ISSUE TITLE
ReferenceError: Can't find variable: endpoint after upgrading from 3.0.3 to 5.1.1

### ISSUE THREAD

**Issue by uxxman** [coinbase/rest-hooks#2178]
**React version** 18.0.0

**Package manager version** npm 8.19.2

**Node version** 16.13.2

**Rest Hooks version** 6.3.11

**Describe the bug**
I am upgrading @rest-hooks/rest from 3.0.3 to 5.1.1 for a React-Native (Expo) app and I get this error  **ReferenceError: Can't find variable: endpoint**. When I revert back to 3.0.3 the error goes away. Is there something new that needs to be installed or configured for v 5.1.1 to work? Thanks for the great work 👍🏻

**Comment by ntucker** [comment]
Can you check your lockfile to see if there are multiple versions of @rest-hooks/endpoint installed?

For reference, https://github.com/coinbase/rest-hooks/pull/2159 is intended to solve the problem of multiple endpoint packages installed.

**Comment by uxxman** [comment]
The lock file shows install version for @rest-hooks/endpoint is 2.3.1. 

Every other rest-hooks package that require @rest-hooks/endpoint also mention the same version 2.3.1 except for @rest-hooks/rest.

<img width="834" alt="Screenshot 2022-09-17 at 02 30 44" src="https://user-images.githubusercontent.com/3153380/190783503-73b12f50-9dd9-4a61-8acb-45cae33edf63.png">

**Comment by ntucker** [comment]
Hmm, so there's only one entry for @rest-hooks/endpoint?

Can you paste the full stack trace of the ReferenceError?

**Comment by ntucker** [comment]
Can you try @rest-hooks/rest@5.2.0-beta.0 and rest-hooks@6.4.0-beta.0

**Comment by uxxman** [comment]
> Hmm, so there's only one entry for @rest-hooks/endpoint?
> 
> Can you paste the full stack trace of the ReferenceError?

Yes. Stacktrace

![IMG_8924](https://user-images.githubusercontent.com/3153380/190847101-6d83e956-3076-4861-a08f-7020d678b04e.PNG)

![IMG_8925](https://user-images.githubusercontent.com/3153380/190847118-1734114c-7f07-4327-b091-818001abee05.PNG)

**Comment by uxxman** [comment]
> Can you try @rest-hooks/rest@5.2.0-beta.0 and rest-hooks@6.4.0-beta.0

same error

**Comment by uxxman** [comment]
More Info: I am also using the same code on web using react-native-web and it works there. Can the latest version be using any node api that is available on the web and not on the JavaScript engine used by react-native?

**Comment by ntucker** [comment]
Two new ideas:

1) @rest-hooks/rest has @rest-hooks/endpoint as peerdeps - perhaps it cannot find it - try adding @rest-hooks/endpoint  to root level?

2) react-native has its own javascript environment. Perhaps there is something odd there. Do you know where the docs are that detail what the environment supports?

**Comment by ntucker** [comment]
Just published beta.1; can you try that as well?

**Comment by uxxman** [comment]
> 1. @rest-hooks/rest has @rest-hooks/endpoint as peerdeps - perhaps it cannot find it - try adding @rest-hooks/endpoint  to root level?

same error



> Just published beta.1; can you try that as well?

same error



> 2\. react-native has its own javascript environment. Perhaps there is something odd there. Do you know where the docs are that detail what the environment supports?

Not sure if there is any source that mentions that, according to react-native docs https://reactnative.dev/docs/javascript-environment
There is also a new Hermes engine and I have tried it with too, same error persists. Can we see a source difference for rest-hooks/rest from 3.0.1 onwards?, I didn't see any tag for it github since its a monorepo

**Comment by ntucker** [comment]
https://github.com/coinbase/rest-hooks/blob/master/packages/rest/CHANGELOG.md is the changelog. Maybe try exactly version 5.0.0 in case this is related to the package exports field changes from https://github.com/coinbase/rest-hooks/pull/2099

**Comment by ntucker** [comment]
It might be easier to pair on this so if you're down feel free to book something on my calendar: https://calendly.com/ntucker1337/hour-meeting

**Comment by ntucker** [comment]
What I'm learning is that in Safari (and thus react native on ios), 'Can't find variable' is the same as 'Uncaught ReferenceError: a is not defined' - so in other words the scope is no aware of a declared variable of that name.

The only thing I can find related to this is sometimes there's weird scoping rules that happen like in : https://stackoverflow.com/questions/67771875/only-in-safari-referenceerror-cant-find-variable

However, the commonjs module has 'use strict' at the top so that specific problem doesn't seem to apply here. I am thinking maybe the RN pipeline is combining files in some way that maybe changes scoping in a weird way but not sure.

Just to double check: Can you maybe paste in what is showing up as the index.js where the error comes from just to verify its contents?

**Comment by ntucker** [comment]
https://stackoverflow.com/a/38686052/1046439 hmm maybe react native doesn't support require anymore? But then why is it loading the commonjs file?

We could validate this by finding in the @rest-hooks/rest package.json

```json
  "exports": {
    ".": {
      "module": "./lib/index.js",
      "import": "./node.mjs",
      "require": "./dist/index.js",
      "default": "./lib/index.js"
    },
    "./package.json": "./package.json"
  },
```

and changing it to

```json
  "exports": {
    ".": {
      "module": "./lib/index.js",
      "react-native": "./lib/index.js",
      "import": "./node.mjs",
      "require": "./dist/index.js",
      "default": "./lib/index.js"
    },
    "./package.json": "./package.json"
  },
```

This would tell newer react native to only use es6 module versions. I just don't have an environment myself to validate this with so I'm unsure.

**Comment by uxxman** [comment]
> and changing it to
> 
> ```json
>   "exports": {
>     ".": {
>       "module": "./lib/index.js",
>       "react-native": "./lib/index.js",
>       "import": "./node.mjs",
>       "require": "./dist/index.js",
>       "default": "./lib/index.js"
>     },
>     "./package.json": "./package.json"
>   },
> ```

Tried this but same error.




> Maybe try exactly version 5.0.0

Tried and same error. Then I tried with version 4.0.0 and these are the changes which introduce the error for the first time. So, up till 3.0.3 everything works as it is. But just upgrading to 4.0.0 of rest-hooks/rest, the error starts to appear. 


I created a demo repo => https://github.com/uxxman/rest-hooks-error. If you see the commit history, its simple;
=> first is project init commit https://docs.expo.dev/get-started/create-a-new-app/
=> second is for adding a basic example of rest-hooks with version 3.0.3

If you clone and run it (npm start) everything works, then just update rest-hooks/rest to v 4.0.0+ and the error starts to appear.

**Comment by ntucker** [comment]
Thanks for the demo repo. It's taking a bit for me to get it running on my machine. Installed android studio, and currently at `Error: spawn /mnt/c/Users/natma/AppData/Local/Android/Sdk/platform-tools/adb ENOENT`

**Comment by ntucker** [comment]
I setup a symbolic link to get adb.exe callable from adb. so i'm at:

```bash
Logs for your project will appear below. Press Ctrl+C to exit.
› Opening on Android...
› Opening exp://172.19.199.61:19000 on Pixel_6_Pro_API_33
› Press ? │ show all commands
Android Bundling complete 1253ms
```

But the android VM just shows a white screen with a white line. Is the app supposed to show anything when it's working?

**Comment by uxxman** [comment]
@ntucker you don't need android studio or anything if you have a smart phone....just install the Expo app, scan the QR-Code and the app will start running on your device. My apologies that you had to go through that hectic setup 😔

The app just displays the list of posts from https://jsonplaceholder.typicode.com/posts

**Comment by ntucker** [comment]
Ok, I think I figured out how to fix - validating this now!

**Comment by ntucker** [comment]
It worked for me so I'm gonna publish a non-beta version of this.

Try rest-hooks@6.4.0 and @rest-hooks/rest@5.2.0 @uxxman !

**Comment by uxxman** [comment]
@ntucker verified rest-hooks@6.4.0 and @rest-hooks/rest@5.2.0 works as expected. Thanks man. Great work and support as always. You are a star 🤩
