### ISSUE TITLE
bug: missing typing for body when using entity class

### ISSUE THREAD

**Issue by andreas-soroko** [coinbase/rest-hooks#2215]
**React version** (e.g., 18.2.0)
- 18.x

**TypeScript version (if used)** (e.g., 4.8.2)
- 4.8.2

**Rest Hooks version** (e.g., 6.3.11)
```
"rest-hooks": "6.4.1"
"@rest-hooks/hooks": "3.0.7"
"@rest-hooks/rest": "6.0.0"
```

**Package manager version** (e.g., yarn 2, npm 8)
8.15.0

**Node version** (e.g., 16.13.2)
v16.17.0

**Describe the bug**
Trying to create some endpoints for test purposes but it looks like that the body isn't correctly inherit? 
Or i am using it wrong ...

**To Reproduce**
see example below 

**Expected behavior**
body should be typed

**Minimum reproducable example or test case**

```ts
class TestEntity extends Entity {
  id = ''
  value1?: boolean
  value2?: Array<string> | null

  pk() {
    return this.id
  }
}

const getById = new RestEndpoint({
  urlPrefix: 'https://some.url',
  path: 'api/v2/data/:id',
  method: 'GET',
  schema: TestEntity,
})

const create = getById.extend({
  method: 'POST',
})
```

additional infos:
<img width="511" alt="image" src="https://user-images.githubusercontent.com/47380084/195668647-f0545829-38e4-4a40-98af-6b611847c97f.png">

so, `getById` looks so far correct when i use `useDLE` but when i use it with `const { fetch } = useController()`
the response is `any` ( bug ?)

<img width="574" alt="image" src="https://user-images.githubusercontent.com/47380084/195668707-28b7f344-0ce3-4f76-86c9-d1465e10b940.png">

and the `create` endpoint seems not to recognise the entity
<img width="793" alt="image" src="https://user-images.githubusercontent.com/47380084/195668911-580b23f3-601e-421b-843b-e71d07d6a9f7.png">

also tried this but this didn't worked too
```ts
const create = getById.extend({
  method: 'POST',
  body: TestEntity
})
```

but this works

```ts
const create = getById.extend({
  method: 'POST',
  body: {} as {
    id: string
    value1?: boolean
    value2?: Array<string> | null
  }
})
```

**Comment by andreas-soroko** [comment]
Thank you for your really good and fast answer. 
I already tried some of your solutions und would prefer the `body: TestEntity.fromJS({})` but it looks like that this is also not working.

> Usually people don't have id in the create urlpath, so maybe you actually want to override that as well?

My misstake, copied the wrong exampe - should be an `update` -  `PUT`. 

## Code sharing
the url prefix in our project is quite dynamically (can be changed at runtime to choose a different edge), so this solution does not fit for us

## Suggestion - Resources: collections of endpoints
saw this already and we have some endpoints where we can use it but we have also some endpoints where the list endpoints returns a smaller model (sub-set) and the `*/:id` use the full one (the reason why i am playing around with the `RestEndpoint` class) - but thanks!

**Comment by ntucker** [comment]
# RestEndpoint @rest-hooks/rest@6

Released a new version with 'body' typing change, and 'process' typing change that I had done previously. With 6.0.1 you'll be able to:

- Extend with body-only and it will inherit the 'path' part of the function
- Set return type with [process()](https://resthooks.io/rest/api/RestEndpoint#process)

```ts
const create = getById.extend({
  method: 'PUT',
  body: TestEntity.fromJS({}),
  process(value): EntityInterface { return value; }
})

// we don't want to say 'pk()' is a member
interface EntityInterface {
  id = ''
  value1?: boolean
  value2?: Array<string> | null
}
```

# Resources

If your url is dynamic, you could try updating the url() member of RestEndpoint 

```ts
class MyEndpoint<O extends RestGenerics> extends RestEndpoint<O> {
  url(urlParams) {
    return getDynamicPrefix() + super.url(urlParams);
  }
}
```

Then create a resource using the new Endpoint:

```ts
const TestResource = createResource({
  urlPrefix: 'https://some.url',
  path: 'api/v2/data/:id',
  schema: TestEntity,
  Endpoint: MyEndpoint
});
```

And if you have the summary/detail entity like you mentioned for validation, simply override the list endpoint like so:

```ts
const BaseTestResource = createResource({
  urlPrefix: 'https://some.url',
  path: 'api/v2/data/:id',
  schema: TestEntity,
  Endpoint: MyEndpoint
});
export const TestResource = {
  ...BaseTestResource,
  getList: BaseTestResource.getList.extend({ schema: SummaryEntity }),
}
```

# Docs updates to come

I added some references to typing in the [RestEndpoint](https://resthooks.io/rest/api/RestEndpoint) page, but I'll add some additional docs for both 'typing endpoints' as well as 'extending resources' like I just posted above.
