### ISSUE TITLE
v6 migration guide

### ISSUE THREAD

**Issue by stufisher** [coinbase/rest-hooks#2246]
Hi! Thanks for the nice project. 

I have just come across the major update to v6 and i am struggling to see how to migrate my existing resource to this new api. Sorry if this is an obvious question but i struggle with some of the technicalities of rest-hooks!

In my current project i have a series of inheritable resources: `BaseResource` (with custom base url), `Authenticated` (token), and `Paginated` (schema structure). This makes it very easy to create new paginated (or not) authenticated resources. With the new API i don't quite understand how i can inherit the paginated schema:

Existing `Paginated`:
```js
export default abstract class PaginatedResource extends AuthenticatedResource {
  static list<T extends typeof Resource>(this: T) {
    return super.list().extend({
      schema: { results: [this], total: 0, limit: 0, skip: 0 },
    });
  }
}
```

Now i create a paginated resource:
```js
export class MyResource extends PaginatedResource {
  readonly id: number | undefined = undefined;

  pk() {
    return this.id?.toString();
  }
  static urlRoot = 'url/to/resource';
}
```

then:
```js
const resource = useSuspense(MyResource.list(), {})
console.log(resource.results, resource.total)
```

How do i do this with the new API? I see the example:
```js
const BaseArticleResource = createResource({
  urlPrefix: 'http://test.com',
  path: '/article/:id',
  schema: Article,
});
export const ArticleResource = {
  ...BaseArticleResource,
  getList: BaseArticleResource.getList.extend({
    schema: { results: [Article], nextPage: '', prevPage: '' },
  }),
};
```

But i don't want to copy and paste this pattern into each of my resources, how can i make this behaviour inheritable? The docs mention extending the `Endpoint` (https://resthooks.io/rest/guides/pagination#code-organization) but i don't quite understand how to apply this to the schema. I guess i need a custom `createResource`?

**Comment by ntucker** [comment]
Yup, you can see a similar example in the github app https://stackblitz.com/github/coinbase/rest-hooks/tree/master/examples/github-app?file=src%2Fresources%2FBase.ts

The only thing I'd suggest is adding more options to customize and just spreading the extra props to the createResource call.

**Comment by stufisher** [comment]
Excellent, thanks a lot!

**Comment by ntucker** [comment]
Added mentions of this pattern:
- [Rest v6 Announcement blog post](https://resthooks.io/blog/2022/10/23/Announcing-Rest-6#inheritance-patterns-for-code-sharing)
- [Inheritance Patterns in createResource](https://resthooks.io/rest/api/createResource#function-inheritance-patterns) docs page

Thanks for the report, hopefully these docs will make this more clear to others!
