### ISSUE TITLE
Add updateParams to function returned from useFetcher deleteShape()

### ISSUE THREAD

**Issue by veeralpatel** [coinbase/rest-hooks#225]
**Is your feature request related to a problem? Please describe.**
When I delete a specific entry by ID, I get the following error "Resource not found in cache GET /users/:id".

**Describe the solution you'd like**
I'd like a solution similar to the updateParams available in useFetcher createShape(). Instead of appending the newly created object, I'd like to filter out the newly deleted object.

**Describe alternatives you've considered**
Adding a new state variable to not fetch my resource if it has recently been deleted

**Comment by kreftk** [comment]
@veeralpatel Can you elaborate on how you handled this error after deleting a specific entry?
