### ISSUE TITLE
Incorrect types in published 4.1.0 package

### ISSUE THREAD

**Issue by skoging** [coinbase/rest-hooks#231]
**React version** (e.g., 16.8.5)
16.11.0

**Concurrent mode** yes/no
no

**Describe the bug**

Seems like there's been an issue when building the 4.1.0 package (not in any of the 4.0.x packages). The type definitions in the d.ts files do not match the source code.

These files reference superagent:
https://cdn.jsdelivr.net/npm/rest-hooks@4.1.0/lib/index.d.ts
https://cdn.jsdelivr.net/npm/rest-hooks@4.1.0/lib/resource/Resource.d.ts

Resource is missing definition for `fetchResponse()`

**Expected behavior**
Type definition in published d.ts files should match the source code.

**Additional context**
Typescript version 3.7.3

**Comment by skoging** [comment]
Looking through the source code I don't see any reason why `fetchResponse()` is missing from the compiled Respource.d.ts type definition.

**Comment by skoging** [comment]
Seems like there's been an issue when building the 4.1.0 package (and probably other 4.x packages). The type definitions in the d.ts files do not match the source code.

`lib/index.d.ts` and `lib/resource/Resource.d.ts` contain references to superagent, which is not used since 3.x

https://cdn.jsdelivr.net/npm/rest-hooks@4.1.0/lib/index.d.ts
https://cdn.jsdelivr.net/npm/rest-hooks@4.1.0/lib/resource/Resource.d.ts

**Comment by ntucker** [comment]
Quite strange. All local-rebuilds worked correctly so I'm just republishing a new version now and hopefully it will have the right stuff.

**Comment by ntucker** [comment]
New version 4.1.1 seems to have correct typings now:

https://cdn.jsdelivr.net/npm/rest-hooks@4.1.1/lib/index.d.ts
https://cdn.jsdelivr.net/npm/rest-hooks@4.1.1/lib/resource/Resource.d.ts
