### ISSUE TITLE
Pagination with infinite scroll example

### ISSUE THREAD

**Issue by uxxman** [coinbase/rest-hooks#2353]
**React version**:  18.1.0

**TypeScript version** 4.6.3

**Rest Hooks version**: rest-hooks/react: 7.1.3, rest-hooks/rest: 6.2.4

**Package manager version**: npm: 8.19.2

**Environment version**: react-native: 0.70.5

**Node version**: 16.13.2

**Describe the bug**
I am using the code example from tests, the list is getting updated (new items are appended) properly but meta (paging) information is only from first page.

```javascript
// Entity
export class PaginatedArticle extends Entity {
  readonly id: number | undefined = undefined;
  readonly title: string = '';

  pk() {
    return this.id?.toString();
  }
}

// Shared resource
function createPaginatableResource<U extends string, S extends Schema>({
  path,
  schema,
  Endpoint = RestEndpoint,
}: {
  readonly path: U;
  readonly schema: S;
  readonly Endpoint?: typeof RestEndpoint;
}) {
  const baseResource = createResource({ path, schema, Endpoint });

  const getList = baseResource.getList.extend({
    schema: { nextPage: null, items: [PaginatedArticle] }
  });

  const getNextPage = getList.paginated((v: { page: number | undefined }) => []);

  return {
    ...baseResource,
    getList,
    getNextPage,
  };
}

// Resource
const PaginatedArticleResource = createPaginatableResource({
  path: 'http://api/articles/:id',
  schema: PaginatedArticle,
});

// Component
export default function ArticlesList() {
  const { fetch } = useController();
  const { items, nextPage } = useSuspense(PaginatedArticleResource.getList);
  console.log(items, nextPage);

  const loadMore = useCallback(async () => {
    fetch(PaginatedArticleResource.getNextPage, { page: nextPage });
  }, [nextPage]);

  return (
    <FlatList
        data={items}
        renderItem={renderItem}
        onEndReached={loadMore}
        keyExtractor={item => item.id}
        onEndReachedThreshold={0.5}
      />
  );
}
```

From the ***console.log(items, nextPage)***, the items get updated with first and second page, but the ***nextPage*** values always remains 2, never goes to next page. Use to work with "@rest-hooks/rest": "5.2.0" with the old usePagintor hook example

**Comment by ntucker** [comment]
Thanks for the report. I'll look into this as soon as my flight lands back home.

**Comment by ntucker** [comment]
Haha, was able to figure it out during my layover. My colleague to review might be asleep now tho so could be a day before it gets released

**Comment by uxxman** [comment]
That was quick 😱 as always 😄 

No worries, looking at the linked PR, its a small fix I can try it out on local fork until this gets released. n again have a nice next flight 😆
