### ISSUE TITLE
Could not find react-redux context value

### ISSUE THREAD

**Issue by thebiltheory** [coinbase/rest-hooks#242]
**React version** (e.g., 16.12.0)

**Concurrent mode** no

**State Management**: Redux-toolkit

**Describe the bug**
After wrapping `<App><Router /></App>` with `<ExternalCacheProvider store={store} selector={selector}>` I got the following Error. 

```jsx
could not find react-redux context value; 
please ensure the component is wrapped in a <Provider>
```
```jsx
const selector = (state: any) => state;

const App: React.FC<AppInterface> = () => (
  <ExternalCacheProvider store={store} selector={selector}>
    <ErrorBoundary fallback={<div>💩</div>}>
      <ThemeProvider theme={theme}>
        <Header />
        <Sidebar />
        <Router>
          <Home path="/" />
        </Router>
      </ThemeProvider>
    </ErrorBoundary>
  </ExternalCacheProvider>
);
```

**To Reproduce**
1. Follow the install guide

**Expected behavior**
The app to render after rest-hooks guide.

**Additional context**
```
The above error occurred in the <LocationProvider> component:
    in LocationProvider (created by Context.Consumer)
    in Location (created by Context.Consumer)
    in Router (at router.tsx:6)
    in Router (at App.tsx:35)
    in ThemeProvider (created by ThemeProvider)
    in ThemeProvider (at App.tsx:26)
    in ErrorBoundary (at App.tsx:25)
    in ExternalCacheProvider (at App.tsx:24)
    in App (at src/index.tsx:7)
```

**Comment by thebiltheory** [comment]
I have an issue with your ~/path imports.
Somehow I cannot find any of your absolute paths with tildes.

**Comment by ntucker** [comment]
Can you paste locationprovider code? I think you're using react redux as well which needs it's own provider

**Comment by thebiltheory** [comment]
I think that's one of Reach/Router's components.

**Comment by ntucker** [comment]
For whatever reason it seems like that dependency you've included assumes react-redux usage. You can follow this: https://react-redux.js.org/introduction/quick-start and simply send in the same store you sent to <ExternalCacheProvider/> and it should work.

**Comment by ntucker** [comment]
Closing since this seems unrelated to Rest Hooks itself. Feel free to open a new ticket with new info!

**Comment by thebiltheory** [comment]
Well in this case, can I remove the `<ExternalCacheProvider>` ?

```javascript
  <Provider store={store}>
    <ExternalCacheProvider store={store} selector={selector}>
      <ErrorBoundary fallback={<div>Oops</div>}>
        <ThemeProvider theme={theme}>
          </Router>
        </ThemeProvider>
      </ErrorBoundary>
    </ExternalCacheProvider>
  </Provider>
````

**Comment by ntucker** [comment]
`<ExternalCacheProvider>` is used by rest-hooks, `<Provider>` is used by your other library. So you need both. They do different things.

You can see what ExternalCacheProvider is doing in the code https://github.com/coinbase/rest-hooks/blob/master/packages/rest-hooks/src/react-integration/provider/ExternalCacheProvider.tsx

It's using its own context, and also managing a few other things.

**Comment by axelboc** [comment]
I got confused about this as well. Might be worth adding Redux's `Provider` in the example on the [Redux integration](https://resthooks.io/docs/guides/redux) page?

**Comment by ntucker** [comment]
@axelboc Updated docs in https://github.com/coinbase/rest-hooks/commit/d88cb8021d8a233c8767000c722919b4065d7053
