### ISSUE TITLE
listShape lacks reference equality across rerenders

### ISSUE THREAD

**Issue by yunyu** [coinbase/rest-hooks#249]
**React version** 16.12.0

**Concurrent mode** no

**Describe the bug**
The return value of useResource(MyResource.listShape(), {}) is referentially different on every rerender, with some of the returned MyResource instances also being referentially different. This makes it difficult to optimize things.

**To Reproduce**
1. Make a resource
2. `const myResourceList = useResource(MyResource.listShape(), {});`
3. `useEffect(() => console.log(myResourceList), [myResourceList]);`
4. Trigger a rerender on that component (setting state, etc)
5. Observe `myResourceList` being logged 

**Expected behavior**
`myResourceList` should be referentially stable across renders if it is being pulled from cache.

**Additional context**
Any console errors? What does the networking inspector show?

**Comment by ntucker** [comment]
It looks like this is definitely sensitive to any entities changing, which means any network call could change it. Can you confirm if this also happens if there is no network traffic at all?

**Comment by ntucker** [comment]
Released in https://github.com/coinbase/rest-hooks/releases/tag/rest-hooks%404.3.0-beta.2

**Comment by yunyu** [comment]
Sorry for the lack of a response - just checked GitHub and I really appreciate you fixing this so quickly. I'll give the beta a try.
