### ISSUE TITLE
Module not found: Error: Can't resolve 'core-js/modules/*'

### ISSUE THREAD

**Issue by christophehurpeau** [coinbase/rest-hooks#25]
**React version** 16.8.5

**Concurrent mode** no

**Describe the bug**
Since the latest release and the update to corejs 3, storybook now fails to find corejs

A lot of errors like this one:

```
ERROR in ./node_modules/rest-hooks/lib/state/selectors.js
Module not found: Error: Can't resolve 'core-js/modules/web.dom-collections.iterator' in '/Users/chris/ornikar/sherwood-react/node_modules/rest-hooks/lib/state'
 @ ./node_modules/rest-hooks/lib/state/selectors.js 9:0-54
 @ ./node_modules/rest-hooks/lib/react-integration/hooks/useCache.js
 @ ./node_modules/rest-hooks/lib/react-integration/hooks/index.js
 @ ./node_modules/rest-hooks/lib/react-integration/index.js
 @ ./node_modules/rest-hooks/lib/index.js
 @ ./.storybook/mockUseResource.js
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js ./node_modules/webpack-hot-middleware/client.js?reload=true
```

It is present in rest-hooks's node_modules:

```
 ls node_modules/rest-hooks/node_modules/core-js/modules/web.*                                                                                                                   
node_modules/rest-hooks/node_modules/core-js/modules/web.dom-collections.for-each.js  node_modules/rest-hooks/node_modules/core-js/modules/web.timers.js
node_modules/rest-hooks/node_modules/core-js/modules/web.dom-collections.iterator.js  node_modules/rest-hooks/node_modules/core-js/modules/web.url-search-params.js
node_modules/rest-hooks/node_modules/core-js/modules/web.immediate.js                 node_modules/rest-hooks/node_modules/core-js/modules/web.url.js
node_modules/rest-hooks/node_modules/core-js/modules/web.queue-microtask.js           node_modules/rest-hooks/node_modules/core-js/modules/web.url.to-json.js
```

The issue is opened in storybook https://github.com/storybooks/storybook/issues/6204 but upgrading to 5.1 didn't fix the issue, probably because CRA uses core-js 2 and only rest-hooks uses 3

**Comment by ntucker** [comment]
does CRA try to compile node_modules directories? I thought the npm resolution algorithm would catch the core-js in rest-hooks directory. Hmm

**Comment by ntucker** [comment]
This was v5.1.0-alpha.18 of storybook with 1.1 of rest-hooks?

**Comment by ntucker** [comment]
If possible maybe setup a minimum github repo that reproduces this?

**Comment by ntucker** [comment]
Interesting. so yarn start is working just not yarn storybook.

**Comment by ntucker** [comment]
I suspect this may be an issue with their build configuration attempting to build node_modules; but haven't had time to fully look into it. You might try using a custom babel and/or webpack config

**Comment by ntucker** [comment]
Another possibility is to add an alias to refer rest-hooks to the unpkg path. Tho I haven't fully tested that option in interactions with storybook.

**Comment by christophehurpeau** [comment]
Temporary solution : https://github.com/storybooks/storybook/issues/6204#issuecomment-478998529
