### ISSUE TITLE
React-native URLSearchParams missing .sort() method causing error in `listUrl` method

### ISSUE THREAD

**Issue by jan-rodriguez** [coinbase/rest-hooks#260]
**React version** 16.9.0
**React-native version** 0.61.5

**Concurrent mode** No idea

**Describe the bug**
When overriding the `listUrl` method for a `Resource` an error is thrown on line: https://github.com/coinbase/rest-hooks/blob/master/packages/rest-hooks/src/resource/SimpleResource.ts#L70

Since it appears that the URLSearchParams does not implement the `.sort` in ReactNative and throw an exception.

**To Reproduce**

1. Make react-native app
2. Use the `listShape` of any resource
3. Watch the fireworks

**Expected behavior**

**Additional context**
Any console errors? What does the networking inspector show?
```
URL.js:90 Uncaught Error: not implemented
    at URLSearchParams.sort (URL.js:90)
    at eval (eval at listUrl (BaseResource.ts:16), <anonymous>:1:8)
    at Function.listUrl (BaseResource.ts:16)
    at Function.listUrl (PricesResource.ts:22)
    at getFetchKey (index.cjs.js:484)
    at useDenormalized (index.cjs.js:2242)
    at index.cjs.js:2738
    at Array.map (<anonymous>)
    at useManyResources (index.cjs.js:2734)
    at useResource (index.cjs.js:2790)
```

Also, looking at the included `URL.js` libabry on react-native the sort method is just:
```javascript
sort() {
    throw new Error('not implemented');
  }
```

**Comment by ntucker** [comment]
Thanks for the report. I've released a version 4.4.0-beta.0 that should have this fixed. @jan-rodriguez can you verify that it works?
