### ISSUE TITLE
[docs] Invalidate/Refresh Example

### ISSUE THREAD

**Issue by johnsoncode** [coinbase/rest-hooks#264]
I was wondering if you have an example of how to invalidate and refresh a resource where the fetch data is in one component and the invalidate/refresh logic is in another component?

The two prime examples to this question is, less common but I feel like it's more complex to deal with, a search page where you have a form component that uses something like Formik, and when you submit and it comes back with a success, I need to refresh the datagrid component.
```html
<div>
    <SearchForm />
    <SearchResultGrid />
</div>
```

More common, at least for me is, editing data on the screen via clicking a button that launches a dialog, and when the data has been updated, again using something like Formik, refresh the underlying data outside the dialog.

I would greatly appreciate your feedback on this. Thank you so much!

**Comment by ntucker** [comment]
https://resthooks.io/docs/api/useInvalidator should work. If it does, I'm curious about feedback on how to make that more easily findable. It is only under api, and there's no guide, but not sure of a great example there. Perhaps your use-case will be a good example and you might provide a PR to add it to the guides section? :)

**Comment by johnsoncode** [comment]
So in the example of a search form and grid, to invalidate, I will need to use the previous filter params when calling `useInvalidator` for the cache engine to know what key to invalidate correct? If so, how would the grid know to refresh based off of the new filters? Or am I completely off and it only uses the base url for caching? It's not immediately apparent to me which way it goes or how it fully works. On top of that, once we get to a point where the cache gets invalidated, the `useResource` hook should then make a new request automatically?

**Comment by ntucker** [comment]
When you say 'previous filter' is this part of the network response? If you could provide some specifics about those apis it might help me understand the flow.

If you simply want to update the data without suspending again, you can [useFetcher()](https://resthooks.io/docs/api/useFetcher) instead

**Comment by johnsoncode** [comment]
Previous Mindset:
Trying to get rid of Redux in favor of this library.

Potential Use Case Setup:
A search page that only has search criteria inputs, a search button, and a list of results below that. The search criteria and the results could be in separate components.

Potential Use Case:
1) Navigate to search page, and the user types in some criteria, hits the search button.
2) The list component should somehow see this result set.
3) User decides to search on something else, and the results should reflect the new response.

It is in this 3rd step that things get a little hazy for me. What params do you use for `useInvalidator`? Do you use the first request from step 1? If so, how does the list component know of these new changes? Hope this makes a little more sense. I very well could not be understanding the "proper" way to approach the library. This same approach above can also be related to the same paradigm of clicking a button on an element to edit something but it instead opens a dialog where you edit it and upon save need to refresh data. Both are valid use cases.

**Comment by ntucker** [comment]
Let's say you have a list component that takes as a prop what the user is searching for. You can control that however you want, but when the prop changes you want different results.

```tsx
import { useResource } from 'rest-hooks';

function ListComponent({ results }: { results: string }) {
  const list = useResource(MyResource.listShape(), { q: results } );
  //...
}
```

Setting the params of the useResource() will shape what url is hit (something like myurl.com/list?q=mysearch+string). Nothing special is needed - any changes to results props results in refetching and re-suspending of the component.

**Comment by ntucker** [comment]
Did this work for you @johnsoncode ? I'm not 100% sure I understood what you're trying to do, so I hope this can be resolved :)

**Comment by johnsoncode** [comment]
We can close it for now. I'll need to work at it more to know for sure if this works. Thank you for the help! Greatly appreciate it!
