### ISSUE TITLE
Fetching ArrayBuffer via Resource

### ISSUE THREAD

**Issue by kreftk** [coinbase/rest-hooks#266]
This is more of a question than necessarily a bug.

I stumbled across fetching a photo for a specific user which is send as an `ArrayBuffer`.
The endpoint to request the photo is: `/users/{userId}/photo`.

I created a separate `UserPhotoResource` additional to my `UserResource` due to problems with missing keys that are not present on the photo return etc.
The `UserPhotoResource` looks like this:

```typescript
import { Resource } from 'rest-hooks';

export default class UserPhotoResource extends Resource {
  pk() {
    return 'user_photo';
  }

  static url<T extends typeof Resource>(
    this: T,
    urlParams: { userId: string },
  ): string {
    if (urlParams) {
      return `/users/${urlParams.userId}/photo`;
    }

    throw new Error('UserPhoto requires userId to retrieve');
  }

  static photoShape<T extends typeof Resource>(this: T) {
    return {
      ...this.detailShape(),
      getFetchKey: ({
        userId,
      }: {
        userId: string;
      }) => {
        return `/users/${userId}/photo`;
      },
      fetch: async ({
        userId,
      }: {
        userId: string;
      }) => {
        const response = await fetch(
          `/users/${userId}/photo`,
        );
        const photoArrayBuffer = await response.arrayBuffer();

        return photoArrayBuffer;
      },
    };
  }
}
```

If I call it like this:
```typescript
const userPhoto = useResource(UserPhotoResource.photoShape(), {
  userId,
});

console.log(userPhoto);
```
It logs:
```
UserPhotoResource {_unq: "0.608616043130813", __ownerID: 1337, Symbol(Defined Members): Array(0)}
```

It would be super helpful if you could lead me in the right direction how to fetch a `ArrayBuffer` resource or even explain how to integrate the `/photo` endpoint in the `UserResource` so i don't need a additional `UserPhotoResource`

**Comment by ntucker** [comment]
Try this instead:

```typescript
const photoShape = {
  type: 'read',
  schema: new ArrayBuffer(0),
  getFetchKey({
        userId,
      }: {
        userId: string;
      }) => {
        return `/users/${userId}/photo`;
      },
      fetch: async ({
        userId,
      }: {
        userId: string;
      }) => {
        const response = await fetch(
          `/users/${userId}/photo`,
        );
        const photoArrayBuffer = await response.arrayBuffer();

        return photoArrayBuffer;
      },
    };
}
```

```tsx
const userPhoto = useResource(photoShape , { userId });
```

[Resources](https://resthooks.io/docs/api/resource) are really meant for key -> value maps.

**Comment by kreftk** [comment]
Thanks for your quick response. Your suggestion definitely makes sense.
Unfortunately, now the `userPhoto` only contains an empty object `{}`. If I debug the `photoArrayBuffer` in the fetch method it logs the correct `ArrayBuffer` before returning it.

Could this be a bug with fetching `ArrayBuffers`?

**Comment by ntucker** [comment]
Updated the above example changing schema. Haven't really used this for arraybuffer case so didn't have details worked out.

**Comment by ntucker** [comment]
Released in 4.5.0-beta.1

docs: https://resthooks.io/docs/next/guides/binary-fetches

**Comment by ntucker** [comment]
Please tell me if this works for you!

**Comment by kreftk** [comment]
Awesome! It works like a charm!
