### ISSUE TITLE
Request for more examples: Adding authentication header to every request

### ISSUE THREAD

**Issue by arabold** [coinbase/rest-hooks#273]
I'm new to Rest Hooks, so please forgive me if I'm overlooking something obvious. I'm trying to figure out what's the best way of enhancing all requests (fetch, mutations, etc.) with a custom `Authorization-Token` header. 

I have an `<AuthenticationProvider>` context provider that works with a `useAuthContext` hook like this:
```ts
const MyApp = () => (
  <AuthenticationProvider>
    <CacheProvider>
      ... // the app
    </CacheProvider>
  </AuthenticationProvider>
);
```

And then in one of my screens I can access the session and access token like this:
```ts
const MyScreen = ({ id }: { id: number }) => {
  const { session } = useAuthContext();
  const fetchUser = useResource(PostResource.detailShape(), { id });
  return ( ... );
}
```

I'm having trouble understanding how I can pass the `sesion.accessToken` to my resource on every fetch. I've walked through the documentation and found various pointers such as writing a custom `Manager`, using `fetchOptionsPlugin` or implementing a custom `Resource`. I also considered creating my own `useAuthResource()` hook. However, I fail to understand how all these pieces exactly fit together to achieve what I'm trying to do: Set an `Access-Token` HTTP header on all outgoing requests based on the value of `session.accessToken`.

**Describe the solution you'd like**
Ideally I would want to configure the `CacheProvider` (or create my own implementation if necessary) that is aware of the authentication context and automatically sets the `Access-Token` HTTP header if logged in.

It would be great if there would be some additional examples for how to use `rest-hooks` in real-world applications. Overall the documentation is good and helpful, but I simply don't see how everything fits together yet.

**Comment by ntucker** [comment]
One approach could be trying to set your own [Manager](https://resthooks.io/docs/api/Manager) like the NetworkManager provided by default. However - that would apply the alterations to every request - so if you wanted to interact with APIs that don't share the same auth credentials you wouldn't be able to.

Instead, I would recommend focusing on the shape functions. If you make these hooks you can easily generate a [FetchShape](https://resthooks.io/docs/api/FetchShape) whose fetch function customizes the fetch headers.

For example, this is the provided `detailShape()`

```typescript
  /** Shape to get a single entity */
  static detailShape<T extends typeof SimpleResource>(
    this: T,
  ): ReadShape<SchemaDetail<Readonly<AbstractInstanceType<T>>>> {
    const getFetchKey = (params: Readonly<object>) => {
      return 'GET ' + this.url(params);
    };
    const options = this.getFetchOptions();
    return {
      type: 'read',
      schema: this.asSchema(),
      options,
      getFetchKey,
      fetch: (params: Readonly<object>) => {
        return this.fetch('get', this.url(params));
      },
    };
  }
```

So a simply overriding the fetch function will get you what you want:

```typescript
  /** Shape to get a single entity */
  static useDetailShape<T extends typeof SimpleResource>(
    this: T,
  ): ReadShape<SchemaDetail<Readonly<AbstractInstanceType<T>>>> {
    const { session } = useAuthContext();
    return {
      ...super.detailShape(),
      fetch: (params: Readonly<object>) => {
        const url = this.url(params);
        // do the rest of your fetch here. You can't use `this.fetch` since it doesn't accept
        // auth session, unless of course you modify it (you should!)
      },
    };
  }
```

**Comment by ntucker** [comment]
Actually probably the simplest way is just realizing that if you're calling the FetchShapes only in component context, you can just use hooks inside. So using fetchOptionsPlugin works just fine:

```typescript
/** A function to mutate all request options for fetch */
static fetchOptionsPlugin = (options: RequestInit) => {
  const { session } = useAuthContext();
  return {
    ...options,
    headers: {
      ...options.headers,
      'Access-Token': session,
    }
  }
}
```

**Comment by ntucker** [comment]
New docs: https://resthooks.io/docs/guides/auth#auth-headers-from-react-context

**Comment by arabold** [comment]
Thank you for your help! I've ended up using a custom Resource that extends `fetch` with a `session` parameter (your "alternative" solution from the first post). It works well for my use case though I find it a little bit cumbersome having to pass the session on every instance of `createShape`, `detailShape`, etc.

Creating a simple `fetchOptionsPlugin` seems actually easier but I'm worried that we (eventually) might break the [Rules of Hooks](https://reactjs.org/docs/hooks-rules.html) in React once internals of `rest-hooks` change in future. 

I've nearly achieved what I wanted before when trying to write my own `Manager` implementation as I can control when and how that manager would be instantiated. That would have been safe to use inside of React and outside, but eventually I failed being able to pass extended HTTP headers to the shapes.

**Comment by ntucker** [comment]
If you're concerned about the rules of hooks, simply rename all your name functions to have 'use' at the beginning.

**Comment by arabold** [comment]
Ah, now I see!

**Comment by GrzegorzWidla** [comment]
> Why would rest hooks internals ever break the rules of hooks?

@ntucker well, I can't really get it running at all due to: ```Error: Invalid hook call. Hooks can only be called inside of the body of a function component.```

Here is the code I wrote. I tried many other hooks, including `useContext`, to check if it isn't anything related to selectors or React Redux but I generally agree with the error React is throwing; just following rest-hooks documentation.

```tsx
import { Resource } from 'rest-hooks';
import { selectUserToken } from '../../actions';
import { useSelector } from 'react-redux';

export abstract class TokenResource extends Resource {
  static fetchOptionsPlugin = (options: RequestInit) => {
    try {
      const token = useSelector(selectUserToken);

      if (!token) {
        throw new Error('Token not available');
      }

      return {
        ...options,
        headers: {
          ...options.headers,
          Authorization: 'Bearer ' + token
        }
      };
    } catch (error) {
      return options;
    }
  };
}
```

**Comment by ntucker** [comment]
Where are you using it though? That's the key. Can you find the next level of the stack trace?

**Comment by GrzegorzWidla** [comment]
> Where are you using it though? That's the key. Can you find the next level of the stack trace?

@ntucker I have a component which is wrapped in `Suspense` and `NetworkErrorBoundary` and is responsible for fetching the data:

```tsx
import React from 'react';
import { useResource } from 'rest-hooks';
import { CurrentCustomerResource } from '../../../lib';

export const OrderPadData: React.SFC = (props) => {
  const currentCustomer = useResource(
    CurrentCustomerResource.currentShape(),
    {}
  );

  return <h1>Order Pad</h1>;
};
```

And the resource is defined as such:

```ts
import { TokenResource } from './token.resource';

export class CurrentCustomerResource extends TokenResource {
  static currentShape<T extends typeof TokenResource>(this: T) {
    const path = '/current-customer/';

    return {
      ...this.detailShape(),
      getFetchKey: () => {
        return path;
      },
      fetch: (params: {}, body?: Readonly<object | string>) => {
        return this.fetch('get', process.env.apiBaseUrl + path, body);
      }
    };
  }

  pk() { // PK is needed as extended Resource class has it defined as abstract
    return undefined; // I tried other options
  }
}
```

Stack trace:
```
    at Object.throwInvalidHookError (react-dom.development.js:16178)
    at useContext (react.development.js:1615)
    at useReduxContext (useReduxContext.js:21)
    at useSelector (useSelector.js:99)
    at Function.fetchOptionsPlugin (token.resource.tsx:8)
    at Function.fetchResponse (Resource.js:29)
    at Function.fetch (Resource.js:50)
    at fetch (current-customer.resource.tsx:13)
    at payload (useFetcher.js:64)
    at deferedFetch (NetworkManager.js:94)
    at Object.timeout (NetworkManager.js:174)
```

**Comment by ntucker** [comment]
Oh hmm... yes this is fetchOptionsPlugin is called from fetch, rather than the shape. I had this all wrong. You'll need to call it from the shape function itself. You'll need to pass in the options to fetch then. Making this easy for everyone will require a bit of a rework, but to workaround for now you can just override your own fetch.

```typescript
  static currentShape<T extends typeof TokenResource>(this: T) {
    const path = '/current-customer/';
    const options = this.fetchOptionsPlugin({});

    return {
      ...this.detailShape(),
      getFetchKey: () => {
        return path;
      },
      fetch: (params: {}, body?: Readonly<object | string>) => {
        // we added a third arg to send in options
        return this.fetch('get', process.env.apiBaseUrl + path, body, options);
      }
    };
  }
```

**Comment by GrzegorzWidla** [comment]
@ntucker Thanks for help. In the end I've decided to follow with simpler approach; I've extended `SimpleResource` and created my own `TokenResource` that's nearly identical to the one `rest-hooks` provides. In `static fetchResponse` method I've pulled the token asynchronously from the local storage as it's also saved there on top of Redux store (though I would have preferred to use Context).

```ts
  /** Perform network request and resolve with HTTP Response */
  static fetchResponse(
    method: Method,
    url: string,
    body?: Readonly<object | string>
  ) {
    let options: RequestInit = {
      method: method.toUpperCase(),
      headers: {
        'Content-Type': 'application/json'
        // "Content-Type": "application/x-www-form-urlencoded",  -- maybe use this if typeof body is FormData ?
      }
    };
    if (this.fetchOptionsPlugin) options = this.fetchOptionsPlugin(options);
    if (body) options.body = JSON.stringify(body);

    // CHANGED: Get token from local storage
    return localForage.getItem<string>(LOCALSTORAGE_TOKEN_KEY).then((token) => {
      if (token) {
        const auth = {
          Authorization: 'Bearer ' + token
        };

        options = {
          ...options,
          headers: {
            ...options.headers,
            ...auth
          } 
        };
      }

      return fetch(url, options)
        .then((response) => {
          if (!response.ok) {
            throw new NetworkError(response);
          }
          return response;
        })
        .catch((error) => {
          // ensure CORS, network down, and parse errors are still caught by NetworkErrorBoundary
          if (error instanceof TypeError) {
            (error as any).status = 400;
          }
          throw error;
        });
    });
  }
```

I've also created my own `NetworkError` and `NetworkErrorBoundary` component so I can handle errors in a way which suits the UI of the app.

https://github.com/coinbase/rest-hooks/blob/master/packages/rest-hooks/src/react-integration/NetworkErrorBoundary.tsx

**Comment by Bettelstab** [comment]
I had the same problem. Here is another solution specific to cases where the session is stored in redux is to call the redux API directly:

```
import { Resource } from 'rest-hooks';

import store from 'library/redux';

export default abstract class AuthenticatedResource extends Resource {
  static fetchOptionsPlugin = (options: RequestInit) => {
    const token = store.getState().oidc.user?.access_token; // Depending on how your redux state looks like

    return {
      ...options,
      credentials: 'include' as 'include',
      mode: 'cors' as 'cors',
      headers: {
        ...options.headers,
        Authorization: `Bearer ${token}`,
      },
    };
  };
}
```

**Comment by stbn694** [comment]
@ntucker I'm a bit lost in the thread xD. Is there a recommended way to do this? I followed the docs but doesn't work.

**Comment by ntucker** [comment]
@stbn694 https://resthooks.io/docs/guides/auth#auth-headers-from-react-context didn't work? What exactly did you observe? Your auth token is stored in react context, right?

**Comment by stbn694** [comment]
@ntucker Yes, I have the token in a context. The problem is that `fetchOptionsPlugin` is never being called.

**Comment by stbn694** [comment]
@ntucker Sorry, I found the problem. I have overridden the fetch function to use axios, and that's where it should be called, right?

But now I get the problem mentioned in https://github.com/coinbase/rest-hooks/issues/273#issuecomment-590570168, the hook is called outside of a component.

Should I call `fetchOptionsPlugin` in every shape and pass it to my fetch function?

**Comment by ntucker** [comment]
@stbn694 Yes, you can try https://github.com/coinbase/rest-hooks/issues/273#issuecomment-590570168 to solve this. If you do this in a base class, it shouldn't be too much repetition as each of your resources will then get the same capability by extending it.

**Comment by stbn694** [comment]
@ntucker OK, I did that, and it works perfectly. Thanks!

Also, I need to call a function of the same context when any request returns a specific code, so I have once more the same problem. Should I pass that function to `fetch` the same way I do with options or is there a more elegant solution?

**Comment by stbn694** [comment]
@ntucker Hi, I tried https://github.com/coinbase/rest-hooks/issues/273#issuecomment-590570168 in my AuthResource, so that all my other resources extend from it. It works fine on simple cases, but if I try to override de fetch function in a child resource, I get the error again. Like this:

```javascript
// AuthResource
static listShape() {
  const options = this.fetchOptionsPlugin({});
  return {
    ...super.listShape(),
    fetch: params =>
      this.fetch('get', this.listUrl(params), undefined, options)
  };
}

// ChildResource
static listShape() {
  const options = this.fetchOptionsPlugin({});
  return {
    ...super.listShape(),
    fetch: () =>
      super.listShape().fetch({
          defaultParam: 0
      })
  };
}
```

Any idea how to solve this?

**Comment by ntucker** [comment]
What error do you get @stbn694 ?

**Comment by stbn694** [comment]
@ntucker The same as before:
`Error: Invalid hook call. Hooks can only be called inside of the body of a function component.`

**Comment by ntucker** [comment]
sounds like you're calling these shapes outside your components. you could try renaming the shapes to have a prefix of 'use' - which with the latest rules of hooks eslint rules will statically analyze it for you to ensure this doesn't happen.

keep in mind, if you're trying to use these outside the context of react - that means you necessarily won't have access to that auth information.

**Comment by stbn694** [comment]
@ntucker Maybe I didn't explain very well.

I created an AuthResource, from which all the other resources extend. In this AuthResource, as agreed on https://github.com/coinbase/rest-hooks/issues/273#issuecomment-625288497, I overrode every shape so that they get the options from `fetchOptionsPlugin`, where I use the hook.

Now, this works well if my other resources just extend AuthResource, but if I want to override a shape in any of those resources, like my example in my previous comment, the error shows again.

**Comment by ntucker** [comment]
Ah, I see the problem now

In the override you are calling the super shape inside the fetch call (which is not done in render function).

```ts
static listShape() {
  const options = this.fetchOptionsPlugin({});
  return {
    ...super.listShape(),
    fetch: () =>
      super.listShape().fetch({
          defaultParam: 0
      })
  };
}
```

Change it to

```ts
static listShape() {
  // this is in the stack frame of the render
  const superShape = super.listShape();
  return {
    ...superShape ,
    fetch: () =>
      superShape.fetch({
          defaultParam: 0
      })
  };
}
```

**Comment by stbn694** [comment]
@ntucker It almost works. I get the error again only if I use the `updateParams` in the fetch function of the `useFecther`, i.e.:

```javascript
const update = useFetcher(ChildResource.listShape(), true);
...
update({}, {}, [[ChildResource.listShape(), {}, ChildResource.appendElements]]);
```

**Comment by mikestaub** [comment]
`fetchOptionsPlugin` is synchronous, what if we have to get the authentication headers asynchronously? ( like with Auth0 hooks )

**Comment by wprk** [comment]
@stbn694 Would it be possible for you to share here / link to your final solution. It sounds like you managed to get it to work using useContext and not trigger the `Error: Invalid hook call. Hooks can only be called inside of the body of a function component` error but I've been trying for a couple of days and haven't managed to get it to work. I'll happily raise a PR to add a working example to the docs for others afterwards too.

**Comment by soulchild** [comment]
I'm banging my head against this as well:

`Error: Invalid hook call. Hooks can only be called inside of the body of a function component.`

Here are my base and child resources:

#### AuthBaseResource

```typescript
import useStore from '../hooks/useStore';
import { Resource } from 'rest-hooks';

export default abstract class AuthBaseResource extends Resource {
  static fetchOptionsPlugin = (options: RequestInit) => {
    // useStore() is just a wrapper around useContext() - I'm not using Redux
    const [store] = useStore();

    return {
      ...options,
      headers: {
        ...options.headers,
        Authorization: `Bearer ${store.currentUser?.token}`,
      },
    };
  };
}
```

#### ProfileResource

```typescript
import AuthBaseResource from './AuthBaseResource';

export default class ProfileResource extends AuthBaseResource {
  readonly id: string | undefined = undefined;
  readonly firstName: string = '';
  readonly lastName: string = '';
  readonly email: string = '';

  pk() {
    return 'profile';
  }

  static currentShape<T extends typeof ProfileResource>(this: T) {
    return {
      ...this.detailShape(),
      getFetchKey: () => {
        return '/profile/';
      },
      fetch: () => {
        return this.fetch(
          'get',
          `${process.env.REACT_APP_API_BASE_URL}/api/v1/profile`,
        );
      },
    };
  }
}
```

The suggested [solution](https://github.com/coinbase/rest-hooks/issues/273#issuecomment-590570168) passes a fourth option parameter to the `this.fetch()` call, but `fetch()` only [accepts three parameters](https://github.com/coinbase/rest-hooks/blob/rest-hooks%404.4.0/packages/rest-hooks/src/resource/Resource.ts#L56). Am I missing something here?

**Comment by ntucker** [comment]
@soulchild The current SimpleResource/Resource interfaces don't support this pattern as they dont' accept that extra argument. I'll make a PR to rework fetch to match the existing fetch browser interface so this is easier. Otherwise you can fully customize that behavior by either defining your own fetch, or just customize resource in general. Resource just provides the CRUD endpoint definitions.

One thing I'm struggling on is handling body. I'd like to automatically JSON.strigify() any body passed, but also support things like FormData which can do more than just JSON payloads. Thinking about how to detect if i should stringify.

**Comment by ntucker** [comment]
@soulchild @wprk 

Breaking change that would make this easy: https://github.com/coinbase/rest-hooks/pull/362

**Comment by soulchild** [comment]
> The current SimpleResource/Resource interfaces don't support this pattern as they dont' accept that extra argument.

Ah, that was the missing piece. I'll go ahead and implement my own `fetch()` method for now. Looking forward to using your modified version soon. ;-) Thanks for the work!

**Comment by soulchild** [comment]
Ok, so I tried out the latest 5.0.0-delta release, but I was unable to have my Resource inherit from a custom BaseResource so that the Resource's custom endpoint automatically gets the `Authorization` header added.

### BaseAuthdResource

```ts
export default abstract class BaseAuthdResource extends BaseResource {
  static getFetchInit = (init: RequestInit): RequestInit => {
    const [store] = useStore();
    const { currentUser } = store;
    return {
      ...init,
      headers: {
        ...init.headers,
        Authorization: `Bearer ${currentUser?.token}`,
      },
    };
  };
}
```

### UserResource

```ts
export default class CurrentUserResource extends BaseAuthdResource {
  static profileShape<T extends typeof CurrentUserResource>(this: T) {
    return {
      ...this.detailShape(),

      getFetchKey: () => {
        return '/me/';
      },

      fetch: () => {
        return this.fetch(`${process.env.REACT_APP_API_BASE_URL}/api/v1/me`, {
          method: 'get',
        });
      },
    };
  }
}
```

I can see `getFetchInit()` getting called and generating the correct headers:

```json
{
  "method": "GET",
  "headers": {
    "Authorization": "Bearer $bearerToken"
  }
}
```

But the actual request is missing the `Authorization` header.

Any hints? Thx!

**Comment by soulchild** [comment]
Well, it turns out I need to call and pass `getFetchInit()` manually in all custom endpoints:

```ts
static profileShape<T extends typeof CurrentUserResource>(this: T) {
    const init = this.getFetchInit({ method: 'GET' });

    return {
      ...this.detailShape(),

      getFetchKey: () => {
        return '/me/';
      },

      fetch: () => {
        return this.fetch(
          `${process.env.REACT_APP_API_BASE_URL}/api/v1/me`,
          init,
        );
      },
    };
  }
```

Is there a better way to avoid having to do this explicitly in every custom endpoint?

**Comment by ntucker** [comment]
@soulchild 

The constraints are
- hook must be called in stack frame of shape function
- return value of hook must be used to alter fetch function

I'm open to suggestions, but it seems unavoidable to have to repeat that if fetch is customized. Perhaps a helper could be created if you're just customizing the url.

```typescript
const fetch = this.makeFetch(`${process.env.REACT_APP_API_BASE_URL}/api/v1/me`);
return {
  ...this.detailShape(),
  fetch,
}
```

**Comment by ntucker** [comment]
https://github.com/coinbase/rest-hooks/pull/391 adds a test for this very case. Using the latest `@rest-hooks/rest` package will give you easy support for this pattern.

See more here: https://resthooks.io/docs/next/guides/auth#auth-headers-from-react-context
