### ISSUE TITLE
Parallel useResource should support more than 5 args

### ISSUE THREAD

**Issue by yunyu** [coinbase/rest-hooks#280]
**React version** (e.g., 16.8.5) 16.12

**Concurrent mode** no

**Describe the bug**
If useResource is called with >5 args in TS, it fails to compile. This is a bit of a dumb request, but I think this should be supported up to something higher (like 16).

**Comment by ntucker** [comment]
Good point. Adding more # of args is tiresome of I make them completely specific. Would it be acceptable to make the types slightly weaker just for those types past the first five?

**Comment by yunyu** [comment]
I'll submit a PR to add up to 10 later, I think the specificity is good

**Comment by ntucker** [comment]
I'm curious about your use case.

I think of useResource() as a way to co-locate data dependencies. So it seems odd that one might want to use 10 data dependencies in one component. Splitting into sibling components will still keep parallelism. Also, for fetching up-front (when you don't need the data), useRetrieve() is sufficient.

**Comment by yunyu** [comment]
For various reasons, we are using the output of several (legacy) resources as the initial state for a form library - as such, it's impossible to properly split this up.
