### ISSUE TITLE
Invalidate Media

### ISSUE THREAD

**Issue by kreftk** [coinbase/rest-hooks#286]
It seems like `useInvalidator` is not working when the `schema` of a `ReadShape` is set to `null as ArrayBuffer | null`.

Like in the [example](https://resthooks.io/docs/guides/binary-fetches):
```typescript
export const photoShape = {
  type: 'read' as const,
  schema: null as ArrayBuffer | null,
  getFetchKey({ userId }: { userId: string }) {
    return `/users/${userId}/photo`;
  },
  fetch: async ({ userId }: { userId: string }) => {
    const response = await fetch(`/users/${userId}/photo`);
    const photoArrayBuffer = await response.arrayBuffer();

    return photoArrayBuffer;
  },
};
```

I tried to work around that problem by using `useFetcher` and refetch manually but the same issue persists.

**Comment by ntucker** [comment]
Thanks for reporting this issue! To help solve this, can you help me understand a bit more about the scenario?

What are the before/after results you get, and what are the after results you expect? For instance, do you have some result before, and then after expect it to go away, or simply update to a new result?

**Comment by kreftk** [comment]
I honestly don't know what I did yesterday that it didn't work. I just retested it and everything works fine with `useInvalidator`.

The only issue left is that  `useInvalidator` complains about incompatible types:

```
Argument of type '{ type: "read"; schema: ArrayBuffer | null; getFetchKey: () => string; fetch: () => Promise<ArrayBuffer>; }' is not assignable to parameter of type 'ReadShape<Schema, object>'.
  Types of property 'schema' are incompatible.
    Type 'ArrayBuffer | null' is not assignable to type 'Schema'.
      Type 'null' is not assignable to type 'Schema'.
```

It works just fine but it would be really nice to get rid of that `@ts-ignore`.

The scenario was to invalidate the cached user image when the user uploads a new one.
