### ISSUE TITLE
Create/Update handle 422 Unprocessable Entity error

### ISSUE THREAD

**Issue by uxxman** [coinbase/rest-hooks#287]
**React version** 16.12.0

**Concurrent mode** no

**Describe the bug**
I am using the basic createShape example given in the getting started example and submitting the form to my API server (in Rails). The server returns 422 error with json errors if the form fields are invalid. This error response doesn't get caught in the NetworkErrorBoundary.

Also if, I wrap the the create request inside my own try/catch block, I still cannot get the the json errors sent by the server.

Can you provide an example to show flow for 422 error responses during create/update. Thank you for the great tool :)

**Comment by ntucker** [comment]
For imperative effects (things run from callbacks/eventhandlers) you'll need to handle errors in an imperative way as well. NetworkErrorBoundary is only intended to be used for declarative data dependencies (useRetrieve or useResource) as it catches errors thrown in render functions.

Thanks for bringing this up and I'll try to update the intro guide to have some examples for this! Just including a quick explanation here in case this unblocks you.

**Comment by uxman-sherwani** [comment]
Thank you for the quick response. Yes, I thought so too that imperative call should go in my own try/catch block, but still I cannot get the json error response in this case. Error response body is not being set by rest-hooks. 

Yes, having this example in docs would be great since it is a really basic case 👍🏻

**Comment by maxbureac** [comment]
+1 here have the same issue as @uxman-sherwani. In rest great tool! Thanks a lot!

**Comment by graphan** [comment]
Hi @ntucker, it would be very helpful if you could add also an example of how to imperatively handle errors based on status code.

We tried your example with the latest version of rest-hooks released 4.5.9 and an error seems to be just a string, whether it would be useful to have an object where we could get the status from.

Cheers and thanks a lot! 👍
