### ISSUE TITLE
Network Error Boundary for already rendered and cached resource.

### ISSUE THREAD

**Issue by uxxman** [coinbase/rest-hooks#288]
**React version** 16.12.0

**Concurrent mode** no

**Describe the bug**
NetworkErrorBoundary doesn't catch exceptions for already rendered resources. E.g. my API uses JWT tokens for authentication and they expire after one hour.  So, if I have a posts page already rendered when the JWT was valid, when it expires after sometime and I go back to posts pages again later, previously cached posts are shown and a request is also being sent which gets 403 (FORBIDDEN) rejected but the error is not thrown to NetworkErrorBoundary, instead an uncaught exception is raised by Resource.ts.

The exception is thrown properly to NetworkErrorBoundary for uncached endpoints.

**To Reproduce**
1. Go to ArticleList resource page with valid JWT. List gets rendered
2. After sometime, go to ArticleList resource page again with invalid JWT. uncaught exception raises.

**Expected behavior**
Exception should be thrown to NetworkErrorBoundary in case of cached data as well, so that I can handle logging user out.

**Additional context**
<img width="615" alt="Screen Shot 2020-03-10 at 21 20 30" src="https://user-images.githubusercontent.com/3153380/76356380-24706f00-6316-11ea-8e23-aa6e8b7f3007.png">

**Comment by ntucker** [comment]
Thanks for the report! This is intended behavior, but perhaps it should change.

For reference: https://github.com/coinbase/rest-hooks/blob/master/packages/rest-hooks/src/react-integration/hooks/useError.ts
If the data is available and an error shows it, it doesn't throw. The *intention* (quite likely incorrect) is to be robust against transient failures. For instance, if you're polling a resource and the network goes down for a short while, it would be nice just to keep the old data and not interrupt the whole experience.

I can think of possibly two solutions. One is that there is a configuration option for the FetchShape to describe how to handle conditions like this. The other is to do what you expect, but somehow handling polling slightly differently. We should also possibly think about how to incorporate online/offline detection so people can continue using the cache when the network goes down. Perhaps one way might be a function to detect whether the error is considered transient or should fail. That could be the configuration option. Perhaps we could have one by default that ignores 5xx (considered transient) but will pass the fail on 4xx.

Would love to hear your thoughts on these design choices!

**Comment by ntucker** [comment]
As a side note, the way we handle auth is by overriding the root fetch function and triggering a global transition (we also use JWT at Coinbase). If it's feasible this might be a workaround for the time being.

**Comment by uxman-sherwani** [comment]
Thanks for the response. Yes, I agree with your point that for errors like server down or 500, showing the cached data will make the user experience more pleasant. But for severe errors like 403, 401, 404 this approach would mean that user keeps seeing data which he is not allowed to see anymore or the data doesn't exist anymore. That will be problematic.

From the developers perspective, I think this would be the most ideal case for new users of this awesome library "to have a config by default that ignores 5xx (considered transient) but will pass the fail on 4xx.".

It could also be configurable by having an option something like
"**alwaysRaiseNetworkErrorFor: [401, 403, 404]**"
If this list is empty, show cached data, if not, raise errors for the listed type of errors. (Just a suggestion)

**Comment by uxman-sherwani** [comment]
> As a side note, the way we handle auth is by overriding the root fetch function and triggering a global transition (we also use JWT at Coinbase). If it's feasible this might be a workaround for the time being.

Can you provide an example for this? Thank you

**Comment by mprobber** [comment]
> It could also be configurable by having an option something like
> "**alwaysRaiseNetworkErrorFor: [401, 403, 404]**"
> If this list is empty, show cached data, if not, raise errors for the listed type of errors. (Just a suggestion)

+1 on this - I'd be opposed to changing the current behavior as it would be a breaking change, but I'm all for being able to configure a set of network errors that would invalidate the cache and trigger a `NetworkErrorBoundary`.

**Comment by ntucker** [comment]
New design thoughts:

- function attached to endpoints that takes error (users can look at error.status)
- possible policies
  - always throw
  - throw if stale
  - only throw if no results
- should retries be a possibility? if so what would dictate the retry policy

**Comment by uxxman** [comment]
Retrying would not be much useful for errors that should be thrown .i.e 404, 401, 403. Error handlers should catch and handle them accordingly.

500 (server reachability) errors can make use of retries, since they can keep showing the old stale data.

**Comment by ntucker** [comment]
Ya I imagine the default policy would be 4xx -> throw, 5xx -> retry x times then try to use stale data.

Also now that I think a bit more it might be best to just have this be defined at NetworkManager level

**Comment by uxxman** [comment]
> Ya I imagine the default policy would be 4xx -> throw, 5xx -> retry x times then try to use stale data.

Sounds good 😌

**Comment by uxxman** [comment]
Thanks and great work as always :) will surely try it out

**Comment by ntucker** [comment]
6.0.0 final was released last night. Working on migration guide and release post. In meantime, summary is https://github.com/coinbase/rest-hooks/releases/tag/rest-hooks%406.0.0
