### ISSUE TITLE
Storybook mocking not working

### ISSUE THREAD

**Issue by Bettelstab** [coinbase/rest-hooks#290]
React version: 16.13.0
Concurrent mode: I don't think so
rest-hooks 4.5.6, @rest-hooks/test 1.0.15

**Describe the bug**
I try to follow the example on https://resthooks.io/docs/guides/storybook. As already described in #storybook, I get
```A React component suspended while rendering, but no fallback UI was specified.

Add a <Suspense fallback=...> component higher in the tree to provide a loading indicator or placeholder to display.
```
Adding `<Suspense>` leads me to a state where always the fallback is rendered. Changing the selected knob value results in the following error:
```Cannot read property 'listUrl' of undefined
TypeError: Cannot read property 'listUrl' of undefined
    at eval (eval at result (http://localhost:9009/vendors~main.11082f74550b145b3892.bundle.js:140614:17), <anonymous>:1:34)
    at getFetchKey (http://localhost:9009/vendors~main.11082f74550b145b3892.bundle.js:140615:18)
    at http://localhost:9009/vendors~main.11082f74550b145b3892.bundle.js:2517:17
    at Array.reduce (<anonymous>)
    at mockInitialState (http://localhost:9009/vendors~main.11082f74550b145b3892.bundle.js:2508:29)
    at MockProvider (http://localhost:9009/vendors~main.11082f74550b145b3892.bundle.js:2600:17)
    at renderWithHooks (http://localhost:9009/vendors~main.11082f74550b145b3892.bundle.js:93979:18)
    at updateFunctionComponent (http://localhost:9009/vendors~main.11082f74550b145b3892.bundle.js:96212:20)
    at beginWork (http://localhost:9009/vendors~main.11082f74550b145b3892.bundle.js:97797:16)
    at HTMLUnknownElement.callCallback (http://localhost:9009/vendors~main.11082f74550b145b3892.bundle.js:79342:14)
```

**To Reproduce**

My `fixtures.ts looks like this:
```
import BloggerResource from 'models/BloggerResource';
import ProductResource from 'models/ProductResource';

export default {
  full: [
    {
      request: BloggerResource.listShape(),
      params: { maxResults: 10 },
      result: [
        {
          id: 5,
          profileName: 'yao_yao',
          products: [],
        },
        {
          id: 23,
          profileName: 'miss_summer',
          products: [5],
        },
      ],
    },
    {
      request: ProductResource.listShape(),
      params: { maxResults: 10 },
      result: [
        {
          id: 5,
          reference: '007H223',
          name: 'Schmuckes Top',
          description: 'Ein ganz tolles Top, ein top Top sogar.',
          shortDescription: 'Tiptop Top',
          quantity: 1,
          price: 14.99,
          imageUrls: [''],
          blogger: 23,
        },
      ],
    },
  ],
  empty: [
    {
      request: BloggerResource.listShape(),
      params: { maxResults: 10 },
      result: [],
    },
    {
      request: ProductResource.listShape(),
      params: { maxResults: 10 },
      result: [],
    },
  ],
  loading: [],
};
```

**Expected behavior**
Story should work as intended.

**Additional context**
- There is also this error message in the browser console:
```It appears you are trying to use Rest Hooks without a provider.
Follow instructions: https://resthooks.io/docs/getting-started/installation#add-provider-at-top-level-component
(anonymous) @ context.js:7
```

- I had to change one line from the example:
```const defaultValue = fixtures.full```
According to https://github.com/storybookjs/storybook/tree/master/addons/knobs section about select, that should be correct.

**Comment by ntucker** [comment]
Thanks for the report. I'll see what I can do to help or fix the issues.

Can you provide your Resource definitions? I think there may be something related to the `listUrl()` you're seeing.

For these two: `Add a <Suspense fallback=...> component` and `Follow instructions: https://resthooks.io/docs/getting-started/installation#add-provider-at-top-level-component` it seems to not be picking up the provider context. One of the reasons this could be is that your hooks and MockProvider are not pulling from the same context. With that in mind, can you verify there's only one copy of rest-hooks installed by looking for entries in your yarn.lock or npm-lock.json files? Another thing I can think of is that there is an issue with commonjs builds, which we mostly only use in node. Do you know whether your storybook environment is configured to use es6 modules or not?

**Comment by Bettelstab** [comment]
Thank you for the quick response, and for this nice project in general :)

My Resource definitions:
```
import { Resource } from 'rest-hooks';

import config from 'config';
import ProductResource from './ProductResource';

export default class BloggerResource extends Resource {
  readonly id: number | undefined = undefined;
  readonly profileName: string = '';
  readonly instagram: string = '';
  readonly description: string | null = '';
  readonly facebook: string | null = '';
  readonly youtube: string | null = '';
  readonly memberSince: string = '';
  readonly products: number[] = [];

  pk() {
    return this.id?.toString();
  }

  static urlRoot = `${config.api_root}/public/blogger`;

  static schema = {
    products: [ProductResource.asSchema()],
  };
}

ProductResource.schema = {
  blogger: BloggerResource.asSchema(),
};
```
```
import { Resource } from 'rest-hooks';

import config from 'config';

export default class ProductResource extends Resource {
  readonly id: number | undefined = undefined;
  readonly name: string = '';
  readonly reference: string = '';
  readonly description: string = '';
  readonly shortDescription: string = '';
  readonly price: number = 0;
  readonly quantity: number = 0;
  readonly imageUrls: string[] = [];
  readonly blogger: number | null = 0;

  pk() {
    return this.id?.toString();
  }

  static urlRoot = `${config.api_root}/public/product`;

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  static schema: any;
}
```

I checked that there is only one version of rest-hooks in my yarn.lock.
My storybook configuration is the standard configuration with `preset-create-react-app`. I could not find out how to configure which module version to use. I found the following variation of the missing provider error in the browser console:
```index.js:47 TypeError: Cannot read property 'listUrl' of undefined
    at eval (eval at result (index.js:310), <anonymous>:1:34)
    at getFetchKey (index.js:311)
    at index.cjs.js:99
    at Array.reduce (<anonymous>)
    at mockInitialState (index.cjs.js:90)
    at MockProvider (index.cjs.js:182)
    at renderWithHooks (react-dom.development.js:14825)
    at updateFunctionComponent (react-dom.development.js:17058)
    at beginWork (react-dom.development.js:18643)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
...
```
so it seems commonjs (index.cjs) is used?

**Comment by ntucker** [comment]
For listUrl thing...can you also share the story itself? https://github.com/coinbase/rest-hooks/blob/master/packages/rest-hooks/src/resource/SimpleResource.ts#L136 seems to be the offending line, which means maybe you're passing your listShape method somewhere and calling that rather than having BloggerResource.listShape().

```js
const BloggerListShape = BloggerResource.listShape;
BloggerListShape() // will throw, because 'this' is undefined.
```

I'll look into the commonjs issue.

**Comment by Bettelstab** [comment]
I created a minimal failing example story:
``
import React from 'react';
import StoryRouter from 'storybook-react-router';

import withReduxStore from 'stories/withReduxStore';
import withRestHooks from 'stories/withRestHooks';
import BloggerResource from 'models/BloggerResource';
import { useResource } from 'rest-hooks';

export default { title: 'BloggerList', decorators: [withRestHooks] };

export const BloggerList = () => {
  const bloggers = useResource(BloggerResource.listShape(), {});

  return (
    <>
      {bloggers.map(b => (
        <div>{b.profileName}</div>
      ))}
      ;
    </>
  );
};
```

withRestHooks.ts:
```
import React, { Suspense } from 'react';
import { MockProvider } from '@rest-hooks/test';
import { NetworkErrorBoundary } from 'rest-hooks';
import { select } from '@storybook/addon-knobs';

import fixtures from './fixtures';

const label = 'Data';
const defaultValue = fixtures.full;
const groupId = 'GROUP-ID1';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export default (Story: any) => {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const results = select<any>(label, fixtures, defaultValue, groupId);

  return (
    <MockProvider results={results}>
      <Suspense fallback={<div>Lade...</div>}>
        <NetworkErrorBoundary>
          <Story />
        </NetworkErrorBoundary>
      </Suspense>
    </MockProvider>
  );
};
```

I tried it without decorator and it doesn't make any difference:
```
import React, { Suspense } from 'react';
import { useResource, NetworkErrorBoundary } from 'rest-hooks';
import { MockProvider } from '@rest-hooks/test';
import { select } from '@storybook/addon-knobs';

import BloggerResource from 'models/BloggerResource';
import fixtures from 'stories/fixtures';

const label = 'Data';
const defaultValue = fixtures.full;
const groupId = 'GROUP-ID1';

export default { title: 'BloggerList (no decorator)' };

const BloggerList = () => {
  const bloggers = useResource(BloggerResource.listShape(), {});

  return (
    <>
      {bloggers.map(b => (
        <div>{b.profileName}</div>
      ))}
    </>
  );
};

export const WrappedBloggerList = () => {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const results = select<any>(label, fixtures, defaultValue, groupId);

  return (
    <MockProvider results={results}>
      <Suspense fallback={<div>Lade...</div>}>
        <NetworkErrorBoundary>
          <BloggerList />
        </NetworkErrorBoundary>
      </Suspense>
    </MockProvider>
  );
};
```

**Comment by ntucker** [comment]
Found the problem - your params are mismatched on your fixtures with your usage. you'll need { maxResults: 10 } as the second arg for it to work.

probably just want to change your fixture to have empty params {}

**Comment by Bettelstab** [comment]
🤦‍♂ Everything works, no more errors. Thank you so much :D

**Comment by ntucker** [comment]
Closing for now. Would love some ideas on how to detect these sorts of things and give helpful suggestions
