### ISSUE TITLE
[docs] Schema level computed property

### ISSUE THREAD

**Issue by johnsoncode** [coinbase/rest-hooks#298]
I'm not sure if it's entirely doable or not, but is there a way to have a schema level computed property? My case is that I have a paged list and want to be able to bubble up some commonly used properties to the schema object. Is this doable? See my example below, the `hasResults` property, I want to do a check if `results` has anything.

```javascript
export default abstract class PaginatedResource extends Resource {
    static listShape<T extends typeof Resource>(this: T) {
        return {
            ...super.listShape(),
            schema: {
                results: [this.asSchema()],
                hasResults: undefined,    // <----- ????
                currentPage: undefined,
                pageSize: undefined,
            },
        };
    }
}
````

**Comment by ntucker** [comment]
https://resthooks.io/docs/guides/network-transform#case-of-the-missing-id

You can do this by overriding the fetch member of your FetchShape. Compute whatever you want there and add fields. The linked example above adds a 'username ' field to the entity itself, but you have control of the entire response, so you can just as well add new things to stuff that only exists in the 'schema' part.

**Comment by johnsoncode** [comment]
Thank you for pointing that out, I totally overlooked that part of the documentation. That should work perfectly.

**Comment by ntucker** [comment]
You can now use SimpleRecord for this case. Replace the top level object and add a getter to your SimpleRecord class. @johnsoncode
