### ISSUE TITLE
[docs] Immutability

### ISSUE THREAD

**Issue by johnsoncode** [coinbase/rest-hooks#301]
I noticed that there isn't much documentation, at least that I could find, that details how one might use immutability with a 3rd party library, i.e. immutable-js. Is there a way to intercept the data coming back from the hook or should I just create a wrapper around the hook calls?

**Comment by ntucker** [comment]
I believe if you return immutable structures from fetch it should give you them back.

**Comment by johnsoncode** [comment]
When I tried that before, it returned an error with the schema normalizr.

**Comment by ntucker** [comment]
Hmm, can you share the error? We haven't been using that at Coinbase, so I haven't spent time ensuring the functionality

**Comment by ntucker** [comment]
We're also happy to accept PRs :)

**Comment by johnsoncode** [comment]
The error that I was referring to is, `Missing usable resource key when normalizing response.` That's appears to be coming from the `Entity.ts` file. That's when I try to convert the result of the fetch in the promise to immutablejs before the schema has had a chance to normalize the result. So, in thinking about this and also trying to keep the library agnostic, I'm wondering if an option needs to be handled further up the stack, like in the `CacheProvider` or something. Going to think about this more, but am also open to any input you might have/suggest. Trying to keep my entire app immutable.

**Comment by ntucker** [comment]
Did you do a deep conversion via fromJS()?

**Comment by ntucker** [comment]
You may need to change your pk function.

```
pk() {
return ImmutableUtils.isImmutable(this)
    ? this.get(idAttribute)
    : this[idAttribute]
}
```

**Comment by johnsoncode** [comment]
Funny you should suggest that. That was going to be the next thing I was going to try after thinking about it more today, but haven't had time to test that out. If that does work in a resource, correct me if I'm wrong, but it wouldn't necessarily work if using a shape directly, as that is not a resource.

**Comment by johnsoncode** [comment]
What's the best practice you guys use in house? Is everything that's CRUD a resource, and "everything" else a shape that you just use in the appropriate hooks? Naturally, I use the word, everything, loosely.

**Comment by ntucker** [comment]
Anything that can possibly define a unique primary key (pk) would be an Entity, of which Resources are one type. Now, technically that isn't absolutely required, but the whole purpose is to have a single source of truth, so your UI is consistent, and performance optimizations can occur.

If you have time, adding a unit test for immutable cases would probably help a lot of other people and ensure compatibility doesn't get lost.
