### ISSUE TITLE
Add optimistic update for delete operations

### ISSUE THREAD

**Issue by AndrewPrifer** [coinbase/rest-hooks#317]
**Is your feature request related to a problem? Please describe.**
Can't optimistically remove resources.

**Describe the solution you'd like**
There is already logic to delete the item from the cache upon completion of the request, I think the only thing to do is to do this immediately and put it back upon an unsuccessful request.

**Comment by ntucker** [comment]
Do you mean immediate updates? https://resthooks.io/docs/guides/immediate-updates#delete I only ask because 'update function' *sounds* like immediate mutate updates. Vs the "optimisticUpdate" function for [optimistic updates](https://resthooks.io/docs/guides/optimistic-updates).

In any case, being able to make deletes optimistic not just immediate, is probably a good idea. :)

**Comment by AndrewPrifer** [comment]
@ntucker oh wait, I indeed mixed things up. Yes, I meant optimistic. Considering there is already logic to delete the item from the cache upon completion of the request, I think the only difficulty is rolling back the change upon an unsuccessful request, right?

**Comment by ntucker** [comment]
Yup! This can be done. Put it on my list, tho we welcome PRs as well!

**Comment by AndrewPrifer** [comment]
@ntucker cool! Can't promise anything but since I wanted to look into how the cache works anyway, I'll send a PR if I can figure out how. I'm guessing there would be multiple ways to go about this. I can see there is an optimisticUpdates array on in the cache, would it be wise to use that with some form of a `deleted` flag to temporarily save the deleted item? Or what would be the most idiomatic way to do this?

**Comment by ntucker** [comment]
https://github.com/coinbase/rest-hooks/blob/master/packages/rest-hooks/src/react-integration/provider/CacheProvider.tsx#L33

applies optimistic state to update. This PR would actually be super easy and you'd just need a mechanism to simulate responses of deleteshapes. The hardest part would be finessing the types and such together.

**Comment by ntucker** [comment]
Actually, looking at the code I think this should already work.

You'll just need to return whatever the delete does, which is likely just nothing: modifying https://resthooks.io/docs/guides/optimistic-updates#optimistic-create-with-instant-updates
```ts
        optimisticUpdate: (
          params: Readonly<object>,
          body: Readonly<object | string> | void,
        ) => '',
```

So really this is more of a docs update

**Comment by AndrewPrifer** [comment]
@ntucker thank you, I will look at this as soon as I have the time! :)

**Comment by ntucker** [comment]
New location of recommended way of doing this: https://resthooks.io/rest/guides/optimistic-updates#optimistic-deletes
