### ISSUE TITLE
Request for example: AbortController and fetchOptionsPlugin

### ISSUE THREAD

**Issue by graphan** [coinbase/rest-hooks#337]
**Is your feature request related to a problem? Please describe.**
I need to apply AbortController to makes fetch requests cancelable.

**Describe the solution you'd like**
`abort` function is accessible from `useResource` hook result.

**Comment by ntucker** [comment]
Thanks for the feature request!

I'd love to learn more about your use case to better be able to support it. Since `useResource` is declarative, it isn't immediately obvious to me under what conditions you would want to abort. Perhaps if the component is unmounted or offscreen? Would love clarification, thanks!

**Comment by graphan** [comment]
@ntucker Thanks for the quick response!

Use cases:

- we cancel requests which were triggered by a component when we navigate from a page away
- we debounce requests after typing inside an input, when we type again we cancel the currently pending requests

**Comment by ntucker** [comment]
I'm not sure of the best approach for deep integration into rest-hooks core yet, but this would be pretty easy to do in user-land:

Have you fetch shape methods take in an abortcontroller as an arg. This would be used by their fetch functions to hook it into native fetch.

```ts
detailShape(signal: AbortController['signal']) {
  return {
    // other stuff
    fetch(params, body) {
      // do stuff
     return fetch(url, { method, signal });
    }
  }
}
```

Now your FetchShapes can be aborted in any context - then all you need to do is add general hooks for handling the lifecycles you suggested:

```ts
function useAbortController() {
  const controllerRef = useRef(null);
  if (!controllerRef) controllerRef.current = new AbortController();
  return controllerRef.current;
}
```

```ts
function useAbortOnUnmount() {
  useEffect(() => () => controller.abort(), []);
}
```

```ts
function useAbortOnChange(params: any) {
  useMemo(() => controller.abort(), [params]);
}
```

Then if you want to do both all the time, create a specialization

```ts
function useAborting(params) {
  const controller = useAbortController();
  useAbortOnUnmount(controller);
  useAbortOnChange(params);
  return controller.signal;
}
```

Then in your component:

```tsx
function MyComponent({ id }) {
  // this should have === return value - not including the code as this is pretty universally available
  const debouncedParams = useDebounce({ id }, 250);
  const value = useResource(detailShape(useAborting(debouncedParams)), debouncedParams);
  // do what you want with value
}
```

**Comment by ntucker** [comment]
My implementation assumes you can reuse abort controllers for multiple requests. I'm not completely sure if this is the case. Does this work for you?

**Comment by ntucker** [comment]
@graphan Did this work?
