### ISSUE TITLE
Issue with Normalizr

### ISSUE THREAD

**Issue by supernoir** [coinbase/rest-hooks#341]
**React version** 16.13.1
**React Hooks version** 4.5.9

**Concurrent mode** no

**Describe the bug**

I am building a web app using CRA with TypeScript and am really excited about Rest Hooks to replace my current axios & build-in hooks set-up.

I have the following REST endpoint I'd like to poll through React Hooks:
```
{
features: [ "a feature"],
id: "1f0b4ede-90fe-42bb-b5a1-3fe7f9h66cd4",
link: "https: //test.com",
make: "ExampleMake",
model: "ExampleModel",
type: "sometype"
}

```
This is the Resource I created to match with the endpoint:

```
export default class SomeResource extends Resource {
  readonly features: string[] = [];
  readonly id: string = "";
  readonly link: string = "";
  readonly make: string = "";
  readonly model: string = "";
  readonly type: string = "";

  pk() {
    return this.id;
  }

  static urlRoot = 'http://myapi.com:8080/someroute/getDetailItem';
}
```
And this is how I plan to use the Resource in my functional component (Detail View, id is given through props):

```
  const article = useResource(
    SomeResource.detailShape(),
    { id }
  );
```

 to be used as e.g. `article.make` in the JSX.

However I only get the following error in the Browser:
`Error: Unexpected input given to normalize. Expected type to be "object", found "string".`

- I have tried many different variations of defining the resource, with no change
- The endpoint is available and returns an object
- The Resource seems to work, the issue occurs only when I use the useResource in the Functional Component
- I do not have normalizr installed as a dependency
- I did install the CRA polyfill
- I have added Suspense and NetworkErrorBoundary in my root component

Please let me know how I can fix this! Thank you

**Comment by ntucker** [comment]
Hi supernoir! Thanks for reporting this issue.

Let's see if we can figure out why normalize is getting a string. Can you add this to your Resource class?

```
  static detailShape<T extends typeof SimpleResource>(
    this: T,
  ): ReadShape<SchemaDetail<Readonly<AbstractInstanceType<T>>>> {
    const shape = super.detailShape();
    return {
        ...shape,
        fetch: async (params, body) => {
          const ret = shape.fetch(params, body);
          console.log(ret, typeof ret);
          return ret;
        }
    };
  }
```

Then you should get a console log of the value that is eventually sent to normalize. I suspect maybe there's something weird with the data being parsed into an actual object - like application/json header missing. This is the first step to tell what's going on.

**Comment by supernoir** [comment]
Okay cool, will try it out and get back to you!

**Comment by supernoir** [comment]
Got a type error for fetch (see Screenshot). When I removed body from the async function. When i removed the "body" parameter the type error vanished, but the console printed only a pending Promise as content and typeof (`Promise { <state>: "pending" }
 object`).

<img width="889" alt="Screenshot 2020-05-15 at 17 52 08" src="https://user-images.githubusercontent.com/13038195/82070772-82824f80-96d5-11ea-9e67-05ba6cb90096.png">

**Comment by ntucker** [comment]
oops, my bad! Updated the example. You'll need to await the fetch as well

**Comment by supernoir** [comment]
Okay cool thanks. Wow, I get the payload as a long string instead of a JSON/object in the response... Do I set the request headers in react-hooks? And if so, where?

**Comment by ntucker** [comment]
Take a screenshot of your network inspector

**Comment by supernoir** [comment]
<img width="1386" alt="Screenshot 2020-05-15 at 18 47 23" src="https://user-images.githubusercontent.com/13038195/82075466-92516200-96dc-11ea-8f95-4d4149fe2e3e.png">

**Comment by ntucker** [comment]
What's under the 'response' tab?

**Comment by supernoir** [comment]
By the way when I wrap "ret" with JSON.parse it works, I can render the data. But I suppose that needs to be done somewhere else, like in a BaseResource or something. So far I am just extending my specific SampleResource with the abstract Resource built into REST hooks, haven't written a BaseResource, I thought with my endpoint being shaped in a way that is exactly like the sample given in the docs, it wasn't necessary.

**Comment by supernoir** [comment]
<img width="468" alt="Screenshot 2020-05-15 at 19 06 28" src="https://user-images.githubusercontent.com/13038195/82077149-3805d080-96df-11ea-9812-7d2f4d40cc16.png">

Response tab: A valid JSON (!)

**Comment by ntucker** [comment]
What is the console log? is it what you expect just the wrong type?

**Comment by supernoir** [comment]
> What is the console log? is it what you expect just the wrong type?

Exactly. the console.log is the response but type string, not object. That's why it works when I cast it as `JSON.parse(ret as string)`

**Comment by ntucker** [comment]
Okay, I can tell you exactly what's going on.

https://github.com/coinbase/rest-hooks/blob/master/packages/rest-hooks/src/resource/Resource.ts#L58 we check for content-type json. People might be sending non-json data - and we don't want to throw an error if this is the case and we can't parse. So in this case it returns text.

We can see from the network tab that there is no content-type header in the response, so it returns text. This is the most typical behavior for APIs, so if you have control that's probably the best approach is to modify the header. However, if you don't want to or cannot do that, simply overriding the fetch function in a base class will get you what you need.

What we can do to make this easier to detect for other users: First off, we can expand a bit more information into the error thrown in the case users are in dev mode. This should give enough information to tell what's going on. Secondly, if we encounter this specific case (where object is expected but string is sent) in dev mode - we can attempt parsing it - and if this works, then we can throw an error that explains exactly what I wrote here.

**Comment by supernoir** [comment]
I see, so I need to enforce content-type in the response header. That should be possible. Thanks so much! I'll let you know if the issue remains, but it looks like that's all there's to it.

Yes! It would be great if the errors were a bit more descriptive in this case or if you'd mention this issue in an FAQ or "common gotcha". Again thanks @ntucker
