### ISSUE TITLE
QueryString conversion not handling objects

### ISSUE THREAD

**Issue by uxxman** [coinbase/rest-hooks#348]
**React version** (e.g., 16.12.0)

**Concurrent mode** no

**Describe the bug**
Search params which are converted to query string are not handling objects. So, for example if I use the following, the server gets proper values,
```javascript
const { items } = useResource(CategoryResource.listShape(), {
  per_page: 100,
  search: 'mobile'
});
```

But if I use something like this,
```javascript
const { items } = useResource(CategoryResource.listShape(), {
  per_page: 100,
  search: {
    name: 'mobile',
    parent_id: 1
  }
});
```
The server gets this,
<img width="440" alt="Screen Shot 2020-05-22 at 12 22 07" src="https://user-images.githubusercontent.com/3153380/82658208-e30a1300-9c26-11ea-8794-33fb69050cf3.png">

**Additional context**
While debugging, I found the following line that causes the porblem
<img width="1057" alt="Screen Shot 2020-05-21 at 23 58 02" src="https://user-images.githubusercontent.com/3153380/82658501-60ce1e80-9c27-11ea-938f-f73735fc675a.png">
But this is coming from URL.js. May be we can use https://github.com/ljharb/qs which handles objects properly
```javascript
assert.equal(qs.stringify({ a: 'b' }), 'a=b');
assert.equal(qs.stringify({ a: { b: 'c' } }), 'a%5Bb%5D=c');
```

**Comment by ntucker** [comment]
Totally understand your use case. For now I think the best thing is to simply override the listUrl method - this is default code:

```ts
export default function paramsToString(
  searchParams: Readonly<Record<string, string | number>>,
) {
  const params = new URLSearchParams(searchParams as any);
  params.sort();
  return params.toString();
}


  static listUrl(
    searchParams: Readonly<Record<string, string | number>> = {},
  ): string {
    if (Object.keys(searchParams).length) {
      return `${this.urlRoot}?${paramsToString(searchParams)}`;
    }
    return this.urlRoot;
  }
```

I'm wary of including additional libraries for cases not everyone will need when it's easy to customize yourself.

**Comment by ntucker** [comment]
For now will close as won't fix, however if this ends up being super common that may change.

**Comment by ntucker** [comment]
Would love a docs addition for this use case though!

**Comment by uxxman** [comment]
@ntucker thanks for update and suggested solution. Yes, it should be included in docs cause it's quite common to have search and order filters to have nested hashes in query strings. Widely used react-admin also has nested objects in query string
<img width="834" alt="Screen Shot 2020-05-26 at 12 44 41" src="https://user-images.githubusercontent.com/3153380/82891886-c8011100-9f4e-11ea-8930-5b830d40411d.png">

**Comment by ntucker** [comment]
I don't think I understand this encoding. `a%5Bb%5D=c` means `a[b]=c` - how does that represent `{ a: { b: 'c' } }`

**Comment by uxxman** [comment]
Inside JavaScript we will have filters object like ```a: { b: 'c' } }```, but when making **HTTP GET** request we have to convert them as query string parameters and sent them with the url. I just used the example provided by qs npm package

<img width="727" alt="Screen Shot 2020-05-26 at 17 32 14" src="https://user-images.githubusercontent.com/3153380/82919904-eaa72000-9f76-11ea-9cf3-96ea69e230ff.png">

**Comment by uxxman** [comment]
@ntucker a lot has changed since we last visited this 🫣 was finally able to update all to latest data-client lib just this issue is left. Previously overriding listUrl was the solution but now there is no listUrl, how to resolve this with the latest version of this lib?

**Comment by ntucker** [comment]
@uxxman [Override ](https://dataclient.io/rest/api/RestEndpoint#inheritance) [RestEndpoint.url](https://dataclient.io/rest/api/RestEndpoint#url)


```ts
import { RestEndpoint, RestGenerics } from '@data-client/rest';

class MyEndpoint<O extends RestGenerics = any> extends RestEndpoint<O> {
  url(urlParams = {}) {
    const urlBase = getUrlBase(this.path)(urlParams);
    const tokens = getUrlTokens(this.path);
    const searchParams = {};
    Object.keys(urlParams).forEach(k => {
      if (!tokens.has(k)) {
        searchParams[k] = urlParams[k];
      }
    });
    if (Object.keys(searchParams).length) {
      return `${this.urlPrefix}${urlBase}?${qs.stringify(searchParams)}`;
    }
    return `${this.urlPrefix}${urlBase}`;
  }
}
```

**Comment by uxxman** [comment]
@ntucker but to override this we need *** getUrlBase*** and *** getUrlTokens***  as well which aren't exported by @data-client/rest

**Comment by ntucker** [comment]
Ah, good point. Can you open a new issue for this case - it will require actual code change.

**Comment by uxxman** [comment]
sure added https://github.com/reactive/data-client/issues/2917
