### ISSUE TITLE
Refetch Resource with useStatefulResource

### ISSUE THREAD

**Issue by mxmtsk** [coinbase/rest-hooks#356]
**Is your feature request related to a problem? Please describe.**
I'm in a React Native environment and want to fetch data in my component and display it in a `ScrollView`. A common UX in Scroll Views is pull to refresh, made possible by the `refreshControl` property.

So when the user pulls down it should refetch the data but I don't see a way to do it. I'm using the legacy implementation so that I already get the `loading` property for the `RefreshControl` component. (see: https://reactnative.dev/docs/refreshcontrol)

**Describe the solution you'd like**
Ideally there is a refetch method available somehow that sets the `loading` prop to true and actually fetches from the server again.

Something like that _maybe_:
```javascript
  const {data, loading, error, refetch } = useStatefulResource(
    CountryResource.listShape(),
    {},
  );

  return (
    <ScrollView
      refreshControl={
        <RefreshControl refreshing={loading} onRefresh={refetch} />
      }
    >
      <Text>lorem ipsum</Text>
    </ScrollView>
  );
```

**Describe alternatives you've considered**
I didn't consider any alternatives, I don't see any way to do it currently - correct me if I'm wrong.

**Comment by ntucker** [comment]
Thanks for the report @mxmtsk ! We have same use case at Coinbase! :)

Try https://resthooks.io/docs/api/useFetcher

"Using it with a ReadShape like detailShape() can be done to force a refresh imperatively."

Please tell me if this works for you!

**Comment by mxmtsk** [comment]
@ntucker Thanks for the quick reply.

The refetching works fine now but the `loading` property from `useStatefulResource` is not updated when using it this way, so the refresh control won't stay after pulling down. Am I missing something?

**Comment by ntucker** [comment]
Ah gotcha. We found it was actually easier to just track that local state by using the promise returned from the fetch.


```ts
const [fetch, loading] = useLoadTracking(useFetcher(Whatever));
```

**Comment by mxmtsk** [comment]
@ntucker Alright, that works for me as well. Thanks for the quick help :)
