### ISSUE TITLE
deleteShape() breaks compilation in 5.0.0-gamma.0

### ISSUE THREAD

**Issue by soulchild** [coinbase/rest-hooks#363]
**React version** (e.g., 16.13.1)

**Rest Hooks version** 5.0.0-delta.0

**Concurrent mode** no

**Describe the bug**

Using `deleteShape()` breaks compilation: 

> TypeError: ___WEBPACK_IMPORTED_MODULE_3__.schemas.Delete is not a constructor

**To Reproduce**

```ts
const deleteDocument = useFetcher(DocumentResource.deleteShape());
```

**Expected behavior**

Should compile ;-)

**Additional context**

The stacktrace shows line 241 of `SimpleResource.ts` as the cause. This seems to have changed between version [4.5.9](https://github.com/coinbase/rest-hooks/blob/rest-hooks%404.5.9/packages/rest-hooks/src/resource/SimpleResource.ts#L232) and [5.0](https://github.com/coinbase/rest-hooks/blob/master/packages/rest-hooks/src/resource/SimpleResource.ts#L241).

```
Function.deleteShape
src/resource/SimpleResource.ts:241

  238 | const init = this.getFetchInit({ method: 'DELETE' });
  239 | return {
  240 |   type: 'mutate',
  241 |   schema: new schemas.Delete(this),
  242 |   options,
  243 |   getFetchKey: (params: object) => {
  244 |     return 'DELETE ' + this.url(params);
```

**Comment by ntucker** [comment]
Can you try forcing @rest-hooks/core to 1.0.0-gamma.0 in yarn.lock? Apparently there's something I misunderstood about resolutions and delta is considered a higher version on same line as gamma

**Comment by soulchild** [comment]
Looks like I'm already using `1.0.0-gamma.0` of `@rest-hooks/core`:

```bash
$ npm ls @rest-hooks/core
└─┬ rest-hooks@5.0.0-delta.0
  └── @rest-hooks/core@1.0.0-gamma.0
```

**Comment by ntucker** [comment]
Ya, gamma is the old version. It's like greek letters: alpha, beta, gamma, delta, epsilon...etc.

**Comment by ntucker** [comment]
I used https://semver.npmjs.com/ and figured out it's just by the first letter, so I'll release an 'h' version that should be above everything.

**Comment by ntucker** [comment]
@soulchild Okay, published https://www.npmjs.com/package/rest-hooks/v/5.0.0-h.0

Can you confirm that it works?

**Comment by soulchild** [comment]
Yeah, `delta` definitely should come after `gamma` ;-) Good to know how these prerelease tags work.`5.0.0-h.0` has indeed fixed the compilation error. Thanks!
