### ISSUE TITLE
useCache on nested array property

### ISSUE THREAD

**Issue by LentnerStefan** [coinbase/rest-hooks#37]
**React version** (e.g., 16.8.5)
16.8.4

**Concurrent mode** yes/no
No

**Describe the bug**
This is more a question on how to handle this kind of use.

Let's say I have a Learner Resource : 

```
export default class LearnerResource extends Resource {
  readonly id: number = 0;
  readonly firstname: string = '';
  readonly lastname: string = '';
  pk() {
    return this.id;
  }
}
```
Learners are never fetched directly, but are a property of a Teacher Resource.
TeacherResource : 

```
export default class TeacherResource extends Resource {
  readonly id: number = 0;
  readonly firstname: string = '';
  readonly lastname: string = '';
  readonly learners: LearnerResource[]= [];
  pk() {
    return this.id;
  }
  static getEntitySchema() {
     cont schema = super.getEntitySchema();
     schema.define({
       learners: [LearnerResource.getEntitySchema()]
     )}
    return schema;
  }
}
```
The component which displays the Teacher : 
```
export default function Teacher({id}): React.ReactElement {
  const teacher = useResource(TeacherResource.singleRequest(), {
    id,
  });
  return (
   <div>
     {teacher.firstname}
     <LearnerList learners={teacher.learners} />
   </div>
  )
```

My question is, how am I supposed to retrieve the learners in the LearnerList  with useCache ? 

```  
export default function LearnerList({learners}): React.ReactElement {
  const learners = useCache(?);
  return (
   <Table dataSource={learners}/>
  )
```

I can't make a Learner Component which could retrieve a single Learner. The component library I use forces me to give the whole data array as a prop.

Thank you !

**Comment by ntucker** [comment]
Great question! This seems like an important use case, which unfortunately doesn't have a good solution yet in code.

However, it would be pretty easy to add something like:

```typescript
// learners = [5, 30, 23];
const learners = useCache(LearnerResource.listRequest(), learners);
``

There's already a special case for single results to select entities even when they don't have actual url results (which you alluded too), we simply need to add another case for passing an array of keys in.

The code is in https://github.com/coinbase/rest-hooks/blob/master/src/state/selectors.ts if you want to take a shot as I probably won't be able to get to this for at least another 2 days as we're doing a hackathon at work right now.

**Comment by LentnerStefan** [comment]
Hi, thanks for your response ! 

I'll take some time to look into it some time later this week. Good luck with your hackathon :)

**Comment by ntucker** [comment]
I think I have a solution to this now. Working on writing it up.

**Comment by ntucker** [comment]
OK! So I'm not certain of exactly if I really want to change useCache right now as there are some alternatives for this and other use cases that are much better probably (like actually denormalizing these). So for now I exposed a lower-level hook called `useSelectionUnstable()` that will enable a simple workaround for this case. I used your example provided to build my own example with this usage:

```tsx
import { useSelectionUnstable, State } from 'rest-hooks';

function selectByPk(state: State<unknown>, pks: any[]) {
  const entitySchema = LearnerResource.getEntitySchema();
  const entities = state.entities[entitySchema.key];
  return pks.map(pk => entities[pk]).filter(entity => entity);
}

export default function LearnerList({learners}): React.ReactElement {
  const learnerResources = useSelectionUnstable(selectByPk, learners, (pks: any[]) => pks.join(','));
  return (
   <Table dataSource={learnerResources}/>
  )
}
```

This is available in 1.4.0-beta.5 however there's a slight typescript bug with the second param expected in the selector function (you can use 'as any' to get around this). The typescript will be fixed shortly as well.

**Comment by ntucker** [comment]
Does this work for you for now? I'm hesitant to introduce a new API surface area when I'm not completely certain of the implications of its implementation.

**Comment by LentnerStefan** [comment]
Hi ! I was off for the week, sorry for the late response. 

I just tried your solution and it does work as expected :) 
However, `State` is not exported by rest-hooks, but it's only for typing so it's not a big problem.

Thank you for taking the time to look into this, and good job on the new documentation !
