### ISSUE TITLE
Force refetch for resources that dont conform to rest standards.

### ISSUE THREAD

**Issue by jjordy** [coinbase/rest-hooks#38]
**React version** (e.g., 16.8.5)
16.8.6
**Concurrent mode** yes/no
yes
**Describe the bug**

Hey this is more of a question than a bug, Is there currently a way to force a re-fetch of a resource say after some mutation? I have some rest endpoints that don't return anything besides a 200 after a put / post Id like to

Incase my question isnt clear heres an example of what im doing currently which works but isnt ideal because sometimes i dont know how to update the resource myself and this is kind of a hack.

```
// Component
     const addCard = useFetcher(BillingResource.createCard());
      <EditCardForm
        billingProfile={billingProfile}
        stripe={{}}
        done={(token: stripe.Token) => {
          const cardId = get(token, "card.id", "New Card");
         // create the updated cache myself
          const updatedProfile = produce(billingProfile, draftState => {
            if (draftState.result && draftState.result.cards) {
              draftState.result.cards[cardId] = `New card added (${moment(
                new Date()
              ).format(
                "MM/DD/YYYY"
              )}) - Details will be updated next time you load the page.`;
            }
          });
        // pass the updated cache as the first argument of the mutation
          addCard(updatedProfile, { token: token.id, applicationName })
            .then(() => {
              setMessage({
                theme: "success",
                message: "Your new credit card information has been saved"
              });
              history.goBack();
            })
            .catch(err => {
              setMessage({ theme: "error", message: "Something went wrong" });
            });
        }}
      />


// RESOURCE
 // Fetch is overriden and in the case of no jsonResponse it just returns the body which is my
 // updated cache in the case of the component above.
  static async fetch<T extends typeof Resource>(
    this: T,
    method: Method = "get",
    url: string,
    body?: Readonly<object>
  ) {
    const jsonResponse = await super.fetch(method, url, body);
    // this looks like a detail response, so let's add the data
    if (jsonResponse && "result" in jsonResponse) {
      jsonResponse.id =
        jsonResponse.result.customerId || jsonResponse.result.tenantId;
    }
    if (!jsonResponse) {
      return body;
    }
    return jsonResponse;
  }

```

Is there a better way to do this have you thought about this??

This library is bad to the bone by the way thanks for everything you have done so far.

**Comment by ntucker** [comment]
https://github.com/coinbase/rest-hooks/blob/master/docs/api/useFetcher.md should do the trick.

It creates a function you can use to imperatively do any fetch.

**Comment by jjordy** [comment]
@ntucker yeh I have been using that a ton for mutations I tried to use it for a read request and I thought it wasn't meant for that as I couldn't get it to work, But if you say that it should work like that let me give it another try. Thanks for the super quick response!

**Comment by jjordy** [comment]
@ntucker Works perfectly not sure what issue I ran into before when i tried that method. Thanks for your help. Will try to contribute something about that in the documentation when I have some time.

**Comment by ntucker** [comment]
It could be that the data is not considered stale yet. Changing the expiry period can help workaround. Commuting to work now but I can give a more detailed explanation when I get into work
