### ISSUE TITLE
Docs for combination of custom list and partial update 

### ISSUE THREAD

**Issue by uxxman** [coinbase/rest-hooks#386]
**Is your feature request related to a problem? Please describe.** No

**Context**
I have a scenario where I have side-by-side two Tabs,
* All Posts (Shows a list of all posts) (/posts)
* My Favorite Posts (Shows a list of posts marked as favorite by the user) (/posts/favorites)

I have used listShape for all Posts and [Custom Lists](https://resthooks.io/docs/guides/endpoints#custom-list-shapes) for displaying data for the Favorite Posts tab. Next I am using [RPC](https://resthooks.io/docs/guides/endpoints#rpc) example to make requests for marking a post as Favorite/Unfavorite.

Now the issue when a user marks a post as favorite, I need two cache updates, one is partialUpdate for **All Posts** and the other is createShape for **My Favorite Posts**. Similarly for unfavorite, one is partial update for **All Posts** and the other is delete shape for **My Favorite Posts**.

Great work by the way 👍

**Comment by ntucker** [comment]
What is the response of your favorite/unfavorite api? Ideally it will return whatever objects are updated.

**Comment by uxxman** [comment]
> What is the response of your favorite/unfavorite api? Ideally it will return whatever objects are updated.

Yes, the response is the post that is being favorited/unfavorited and the optimistic update works as expected. The issue regarding adding and deleting related post from the list of favorites

**Comment by ntucker** [comment]
https://resthooks.io/docs/api/useFetcher#updateparams-destshape-destparams-updatefunction is what you want. Admittedly it's a not the easiest to follow now. We plan on changing the interface to be a big more clear in the future.

**Comment by uxxman** [comment]
> https://resthooks.io/docs/api/useFetcher#updateparams-destshape-destparams-updatefunction is what you want. Admittedly it's a not the easiest to follow now. We plan on changing the interface to be a big more clear in the future.

I have tried it already, when I use this approach 'Favorite Posts' work fine but 'All Posts' is broken since it tries to add and delete posts. When I use partialUpdate, 'All Posts' work fine but the 'Favorite Posts' doesn't add and remove posts.

**Comment by ntucker** [comment]
```typescript
const appendPost = (newArticleID: string, articleIDs: string[] | undefined) => [
      ...(articleIDs || []),
      newArticleID,
    ];
const removePost = (newArticleID: string, articleIDs: string[] | undefined) => articleIDs.filter(id => id!== newArticleId);
//...
favorite({}, { id: 1 }, [
  [
    PostResource.listShape(),
    {},
    appendPost,
  ],
  [
    PostResource.listShape(),
    { filter: 'favorite' },
    appendPost,
  ],
]);

unfavorite({}, { id: 1 }, [
  [
    PostResource.listShape(),
    {},
    removePost,
  ],
  [
    PostResource.listShape(),
    { filter: 'favorite' },
    appendPost,
  ],
]);
```

**Comment by uxxman** [comment]
Thanks for looking into it. Could not make it work though. I decided to use **useInvalidator** to achieve a similar flow.
