### ISSUE TITLE
Attempted import error: 'AbstractInstanceType' is not exported

### ISSUE THREAD

**Issue by lucasdidur** [coinbase/rest-hooks#395]
I'm trying to use version 5.0.0-k.0 but o get this error when compile

Failed to compile.

./node_modules/@rest-hooks/endpoint/lib/index.js
Attempted import error: 'AbstractInstanceType' is not exported from '@rest-hooks/normalizr'.

**Comment by ntucker** [comment]
Hmm, can you check which version of `@rest-hooks/normalizr` was resolved in yarn.lock?

**Comment by lucasdidur** [comment]
```
"@rest-hooks/normalizr@^6.0.0-j.2":
  version "6.0.0-j.2"
  resolved "https://registry.yarnpkg.com/@rest-hooks/normalizr/-/normalizr-6.0.0-j.2.tgz#50116181bbf0296af8c447b3b6fc82b031b40f6b"
  integrity sha512-n/c5TGOYTi+rHhanaYGJebBLAK/6liDZg1weyrY1h0S/cDHwinxtLEpsNkJECO5xRlvG+3gu9G9rZv387YNn0Q==
  dependencies:
    "@babel/runtime" "^7.10.4"
```

**Comment by ntucker** [comment]
Oh, now i see the problem - it's with js trying to import a typescript thing. I'll get a fix out shortly. Oddly this wasn't triggering for me.

**Comment by ntucker** [comment]
@lucasdidur rest-hooks@5.0.0-k.1 released with fix.
