### ISSUE TITLE
Surprising behavior using `errorExpiryLength`

### ISSUE THREAD

**Issue by praxxis** [coinbase/rest-hooks#408]
We've been surprised by the behavior of network errors, specifically that they're cached. We thought we'd worked around a problem, described below, by using `errorExpiryLength` however it ended up working in a way that was surprising at first.

Our use case is basically:

1. We try and load a `list` using `useResource`
2. The list network fall fails for whatever reason
3. We show a helpful error, using `NetworkErrorBoundary`, and allow the user to try again.
4. We make the same `list` call, but the error is now cached and thus rethrown by `useResource`, so the `NetworkErrorBoundary` is rendered again.

We tried setting `errorExpiryLength` to `0`, with the thought that this would disable caching of errors. This didn't work, and looking at the source of `useError` seems to indicate that it doesn't have any interaction with `errorExpiryLength` at all - you can only invalidate the resource's error using `useInvalidator`. Setting `errorExpiryLength` does seem to cause the resource to re-fetch, but by then it has already thrown the error and we've rendered the error boundary.

This seems un-intuitive: our thought was that by setting `errorExpiryLength` errors would not be cached, but it doesn't look like there's any way to do that. Our current workaround is to call `useResetter` at the error boundary, completely nuking the cache, but ideally we could just have a way of configuring resources to not cache errors. Perhaps a counterpart to `invalidIfStale` for errors specifically?

**Comment by ntucker** [comment]
Thanks for the detailed report! Which version of rest hooks are you using in this case?

**Comment by praxxis** [comment]
oops, sorry!
```
"@rest-hooks/rest": "^0.4.0",
"rest-hooks": "^5.0.0-k.2",
```
This code didn't exist when we were using v4.5, so I can't say if it was a regression.

**Comment by ntucker** [comment]
The culprit is https://github.com/coinbase/rest-hooks/pull/360

I recall there was a weird edge case with infinite loop of refetching we wanted to avoid. However, we don't' seem to have a test case for it, so we need to add one for that as well as the scenario you described here.

**Comment by ntucker** [comment]
Released fix in https://github.com/coinbase/rest-hooks/releases/tag/rest-hooks%405.0.0-k.3

**Comment by praxxis** [comment]
confirmed fixed on our end, thanks for the quick turnaround!

**Comment by praxxis** [comment]
actually a followup question - what is the purpose of `errorExpiryLength`? In which circumstances are errors cached now?

**Comment by ntucker** [comment]
It's still cached based on that length. This is part of the tests:

https://github.com/coinbase/rest-hooks/pull/410/files#diff-c2f12fc07b2555552f74e1199479eb8dR383

The problem was before, it wouldn't suspend even when it was refetching if there was already an error
