### ISSUE TITLE
Return value from fromJS is reused

### ISSUE THREAD

**Issue by praxxis** [coinbase/rest-hooks#411]
**React version** 16.13.1

**Concurrent mode** no

**Describe the bug**
We were/are using `fromJS` to deserialize dates and other types coming back from our API, per [the docs](https://resthooks.io/docs/next/api/resource#static-fromjst-extends-typeof-resourcethis-t-props-partialabstractinstancetypet-abstractinstancetypet). We've found however that, with a normal workflow of "fetch list of resources" then "fetch resource detail", `fromJS` is called with the _already serialized_ data. I've created a [reproduction](https://codesandbox.io/s/vigorous-taussig-cpt73?file=/src/App.js) which is hopefully easier to understand. Open the console and you should see `fromJS` being called 3 times for the initial list, at which point the data passed in to `fromJS` is the date string returned from the API. When we go to get an individual resource, however, `fromJS` is called with the date as an actual `Date`.

Moving to version 5 it looks like the preferred way of serialization is now using `schema`, and if this is true the docs should probably mention the above behaviour at the  least.

**Additional context**
```
"rest-hooks": "^5.0.0-k.3",
"@rest-hooks/rest": "^0.4.0",
```

**Comment by ntucker** [comment]
https://github.com/coinbase/rest-hooks/pull/403 will lead to much more predictable and consistent behavior with regard to this. (the cache will have raw data, and fromJS() will be called in a denormalized cache).


You are correct that schema is the preferred way of deserialization now. Will update the fromJS() docs to reflect this.
