### ISSUE TITLE
`useResource` multi-fetch and null params leaves `undefined` element in array

### ISSUE THREAD

**Issue by praxxis** [coinbase/rest-hooks#414]
**React version** 16.13.1

**Concurrent mode** no

**Describe the bug**
I'm not sure if this is a bug or just a weird hooks thing that we'll have to work around, but when calling `useResource` with multiple resources and one resource is "disabled" via setting `params` to null, there is an element in the resulting array that is just `undefined`. That's a mouthfull, so I've made a reproduction [here](https://codesandbox.io/s/modest-cache-m2frd?file=/src/App.js:950-955) - note how the second element in the array is `undefined` in the console.

We're doing this because we have a list of resources we need to fetch, but sometimes that list is actually "no resources". Because of hooks, we can't just put the `useResource` call behind an `if`, so we have been using `null` `params` which per https://resthooks.io/docs/next/api/useresource at least doesn't fetch.

**Additional context**
```
"rest-hooks": "^5.0.0-k.3",
"@rest-hooks/rest": "^0.4.0",
```

**Comment by ntucker** [comment]
That is by design. Any hook call with null params will return the 'undefined' form of the response, which in this case is just `undefined` since there is no nesting of the schema. `useResource()` with list params is just like multiple `useResource()` calls, except they fetch in parallel.

I'm not sure what you expect to be the result? The null params should correspond to undefined in the returning list, so it should be easy to filter out any of those pieces. Can you describe what return value you expect to see?

**Comment by praxxis** [comment]
We were expecting nothing at all, but if `undefined` is by design that's fine. Like you said we can just filter it out. Or create Even More Components to filter stuff, which seems to be the answer for any and all hook problem...

**Comment by ntucker** [comment]
Yeah, I can see how that might make sense, but the intended design is to use array destructuring, so you wouldn't be able to do that if the number of results changed.

**Comment by praxxis** [comment]
Ah, OK,  in that context it's clearer. What we're doing is creating a list of resources to fetch based off another list, but the catch is that sometimes the second list is empty and there are _no_ resources to fetch. So we don't care about the order/wouldn't use destructuring. Like I said, a different combination of components is probably the most hookish solution for us long term.

**Comment by ntucker** [comment]
You could make your own custom hook for this use case, building off useRetrieve() and useCache() as useResource() also does.
