### ISSUE TITLE
Example: Unit test for useFetcher() and Resource.createShape()

### ISSUE THREAD

**Issue by graphan** [coinbase/rest-hooks#415]
**Is your feature request related to a problem? Please describe.**
You have a nice example on how to unit test `useResource()` together with `Resource.detailShape()`: https://resthooks.io/docs/api/makeRenderRestHook#example

There is no example on how to do it for `useFetcher()` and `Resource.createShape()`

**Describe the solution you'd like**
Similar example as mentioned above.

**Comment by kreftk** [comment]
I second this request. Would be nice to see an example of what's the right way to test and mock dispatching mutations and actions (like doing a login or creating a user).

**Comment by ntucker** [comment]
Will put this in the short queue.

**Comment by graphan** [comment]
@ntucker it would be awesome to have an example to make the solution more complete.
Do you have any update on this?

**Comment by ntucker** [comment]
I'll take a look at this within the next week

**Comment by ntucker** [comment]
@graphan I revisited this after usage, and ended up with https://github.com/coinbase/rest-hooks/pull/446. Would love to see feedback on its usage. (Includes docs updates that should make it clear.)

**Comment by ntucker** [comment]
@graphan  @kreftk https://resthooks.io/docs/next/guides/storybook you can now use [MockResolver](https://resthooks.io/docs/next/api/MockResolver) which should support this use case in [@rest-hooks/test@2.0.0-k.2](https://github.com/coinbase/rest-hooks/releases/tag/%40rest-hooks%2Ftest%402.0.0-k.2)
