### ISSUE TITLE
ERROR WITH REACT REDUX

### ISSUE THREAD

**Issue by RishardM** [coinbase/rest-hooks#417]
![image](https://user-images.githubusercontent.com/71266976/94130326-8152f300-fe2a-11ea-85fb-f8b427aeb70d.png)
![image](https://user-images.githubusercontent.com/71266976/94130396-97f94a00-fe2a-11ea-8a20-d847f89ad7d8.png)

**Comment by RishardM** [comment]
Please Help Very Time Dependant

**Comment by ntucker** [comment]
If you want to use react-redux outside the context of the Rest Hooks library, you'll need to use their provider as well: https://react-redux.js.org/introduction/quick-start#provider
