### ISSUE TITLE
Use useResource on a crud page

### ISSUE THREAD

**Issue by lucasdidur** [coinbase/rest-hooks#418]
I'm trying to create a crud page, so when I have an `id` at url param, I want to load that resource, end when not, use a empty object. But i'm getting error.

I'm using the same component to create and edit the entity.

```
/news/add       - create a new
/news/26588  - loads the resource
```

I get this error because he is trying to load the `/` resource of my rest api:

`Attempted to initialize NewsResource with substantially different than expected keys`

```typescript
const NewsForm = () => {
    const { id } = useParams();

    let entity = useResource(NewsResource.detail(), { id });
    
    const [doc, setDoc] = useState<NewsResource>(entity);

    return (<div></div>)
}
```

So how to load the resource if has the `id` variable?

**Comment by ntucker** [comment]
[useResource()](https://resthooks.io/docs/api/useresource) will do nothing is the second param is null.

If you're wanting to do optimistic updates, https://resthooks.io/docs/guides/optimistic-updates would be a good step as it guarantees consistency and eliminates race conditions. If not done carefully, different usages of the same data could be inconsistent, or if there is ever any server errors it could diverge.

```tsx
const NewsForm = () => {
    const { id } = useParams();

    let entity = useResource(NewsResource.detail(), id ? { id } : null);
   let setDoc = useFetcher(NewsResource.detail());

    return (<div></div>)
}
```

As far as the error you're seeing - that means your type definition doesn't match what is returned from the API response. We can look at the comparison here if you provide the Resource definition, as well as use the browser network inspector to show exactly what the API response is.

**Comment by lucasdidur** [comment]
Hello, thank you for help, I did get to work with

```typescript
    // load initial value if has hd
    let entity = useResource(NewsResource.detail(), id ? { id } : null);

    // set the initial value if has, otherwise inicialize with a empty object
    const [doc, setDoc] = useState<T>(entity ? entity : {} as any);
```

But i did not understand this code:
```typescript
let setDoc = useFetcher(NewsResource.detail());
```

Here's my full code

```typescript
import {useParams} from "react-router-dom";
import {useResource} from "rest-hooks";
import React, {useState} from "react";
import {get, set} from "lodash";
import {NewsResource} from "./resources";
import {FormInput} from "./components";

type Props = {
    path: string;
    label: string;
}

const NewsForm = (props) => {
    const {path, label} = props;
    const {id} = useParams();
    const entity = useResource(NewsResource.detail(), id ? {id} : null);
    const [doc, setDoc] = useState(entity ? entity : {} as any);

    const handleChange = (path: string, value: any) => {
        setDoc(set(doc, path, value));
        console.log(doc);
    }

    const getDefault = (path: string) => {
        let value = get(doc, path)

        if(!value)
            value = '';

        return value;
    }

    return (
        <FormInput
            initialValue={getDefault(path)}
            label={label}
            onChange={value => handleChange(path, value)}
        />
    )
}

export default NewsForm;
```

**Comment by lucasdidur** [comment]
When I use `useFetcher(NewsResource.partialUpdate());` i'm getting CORS error, GET is working normally.

**Comment by ntucker** [comment]
by default `partialUpdate` sends a PATCH. If CORS aren't set to allow that method it can be problematic. Do you know the network header your endpoint expects?

**Comment by lucasdidur** [comment]
Yes, the request that I capture from the browser is this.

```
curl --location --request PATCH 'http://localhost:5001/us-central1/webApi/api/v1/news/264002' \
--header 'Connection: keep-alive' \
--header 'Authorization: Bearer <token>' \
--header 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36' \
--header 'Content-Type: application/json' \
--header 'Accept: */*' \
--header 'Origin: http://localhost:3000' \
--header 'Sec-Fetch-Site: same-site' \
--header 'Sec-Fetch-Mode: cors' \
--header 'Sec-Fetch-Dest: empty' \
--header 'Referer: http://localhost:3000/' \
--header 'Accept-Language: pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7,gl;q=0.6,es;q=0.5' \
--data-raw '0.46806219285611994'
```

I don't know why the raw data is a number.

**Comment by ntucker** [comment]
CORS is sort of beyond the scope of this library. https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS should point you in the right direction for debugging. Just be sure to use the networking tab so you know what actual network requests are being initiated by rest hooks and then it should be the same for any library.

That said the simplest (and insecure) way to solve CORS errors is to just allow * on backend.

**Comment by ntucker** [comment]
@lucasdidur Were you able to figure this out?

**Comment by lucasdidur** [comment]
Helo, sorry but i  didn’t, others plugins dont get this error
