### ISSUE TITLE
Declarative way of mapping data shapes

### ISSUE THREAD

**Issue by webberwang** [coinbase/rest-hooks#420]
**Is your feature request related to a problem? Please describe.**

The database is returning `_id` instead of `id`, but the frontend requires `id`. Let's assume we don't have access to the server.

The concept of mapping data shapes isn't a first-class citizen. Would be helpful to enable API for mapping data.

**Describe the solution you'd like**

We could provide some kind of api to map the actual schema to the desired schema.

```typescript
export class UserResource extends Resource {
  // readonly id: string | undefined = undefined

  readonly id: string | undefined = {
   mapper: ['id', '_id'] // [desired, actual]
   default: undefined
  }
}
```
Then the data is magically mapped when we call the resource.

**Describe alternatives you've considered**

Currently from my understanding, we can modify the `fetch` block like so to solve the problem

```typescript
return {
  ...shape,
  fetch: async (params) => {
    const data = await shape.fetch(params)

    return {
      ...data,
      id: data._id,
    }
  },
}
```

**Additional context**

I looked into normalizr but that doesn't seem to deal with mapping data from my understanding.

Does this seem like too much overhead for not having to write a simple map function? Is the `fetch` block the appropriate place to put this logic or should I be handling it elsewhere?

Thanks!

**Comment by ntucker** [comment]
For mapping per-resource, you could try customizing [fromJS()](https://resthooks.io/docs/next/api/SimpleRecord#static-fromjst-extends-typeof-simplerecordthis-t-props-partialabstractinstancetypet-abstractinstancetypet).

```typescript
fromJS({_id, ...props}) {
  return super.fromJS({...props, id: _id });
}
```

**Comment by webberwang** [comment]
@ntucker 

Thanks for that, just confused about where would I call `ResourceNode.fromJS()`?

Currently like so:

```
const node = useResource(ResourceNode(), {}) as ResourceNode
```

Saw example here https://github.com/coinbase/rest-hooks/issues/185 but not much on where to call. Would I be calling `ResourceNode.fromJS()` inside the `fetch` block of `ResourceNode()`?

Very cool library but there aren't too many examples on the internet as it's only 2 years old. Thanks!

**Comment by ntucker** [comment]
@webberwang Just wanna make sure this was resolved for you and you didn't just give up. I got an email about another reply here but when I came to the thread it was just closed.

Just for more context - fromJS() is a factory method used instead of constructor (for various technical reasons). It's called during normalization to store data after it's returned from fetch.

**Comment by webberwang** [comment]
@ntucker Thanks for reaching back, I got it working but now that you mentioned it would be great to get a confirmation from you to see if the usage is correct. Also for any others in the future to see.


```
// inside react component
const node = useResource(ResourceNode.detailShape(), { id }) as ResourceNode 
```

```
 fetch: async (params: any) => {
  const data: any = await shape.fetch(params)
  // calling implemented method
  const result = this.fromJS<typeof SimpleRecord>(data)

  return result
},
```

We have to manually call it in the fetch block right?

**Comment by webberwang** [comment]
I suppose in this case I'll have to set pk to `_id`, then map `_id` to `id` in the `fromJS` block

**Comment by ntucker** [comment]
Ah yes, pk() gets called with data before fromJS() is called when first processed. This inconsistency is rather confusing and will be corrected in an upcoming breaking release.

unfortunately you'll need to check for both _id and id in your pk function as it runs on both pre and post-processing.
