### ISSUE TITLE
Governance and sustainability?

### ISSUE THREAD

**Issue by wwahammy** [coinbase/rest-hooks#421]
I just stumbled on this library and it looks absolutely amazing. I'm so excited to try it out.

As I'm evaluating it for company use, I was wondering what the governance and sustainability model is for this project. What is the process for making decisions about the long term goals of the project? Additionally, rest-hooks seems to have a pretty small number of contributors. That's always worrisome when it comes to a library to depend on. Is there any sort of plan for expanding the number of contributors and maintainers to increase long term sustainability?

Thanks again for this library, it really does seem to solve problems about hooks and REST APIs in an elegant way.

**Comment by ntucker** [comment]
Hi @wwahammy, great question!

Until recently we've been managing the direction and collaboration on projects within Coinbase via an internal group called the "Rest Hooks Council". There we would have meetings discussing the future of the group as well as having open reviews of "HEP"s (Hook Enhancement Proposals) for any major or breaking changes.

*However*, now @ljharb and me are working on opening the council. We'll likely be looking for some dedicated community members to join the council and at the very least, become involved in the reviews and community going forward. We'll have more to announce soon, until then we've setup a discord community and are currently getting that setup, etc.

[![Chat](https://img.shields.io/discord/768254430381735967.svg?style=flat-square&colorB=758ED3)](https://discord.gg/35nb8Mz)

**Comment by wwahammy** [comment]
Thanks @ntucker. That's all good to hear. I've joined the Discord.

Are you able to share a sense of how much Rest Hooks is used in Coinbase? Again, just want to know the likelihood that it will continue to be maintained, given that the community is still quite small. :smile:

**Comment by ntucker** [comment]
Currently used by 3 public product teams (consumer, commerce, custody), and 3+ internal tools teams, as well as across both web and react native.
