### ISSUE TITLE
Define a resource as a function

### ISSUE THREAD

**Issue by atefBB** [coinbase/rest-hooks#425]
Hi.
Thanks for the great work.
Excuse me if this doesn't make sense! but I feel more comfortable when using `functions` in `typescript` and `JS` in general (and especialy with `react`), so is there a possibility to define a `resource` as a function? Can I avoid using `readonly`/`static`/`extends` in my resources?
Thank you.

**Comment by ntucker** [comment]
Okay, so defining your endpoints outside the context of the class.

How about the example from https://resthooks.io/docs/next/api/Endpoint#schema-schema

```typescript
import { Entity } from '@rest-hooks/normalizr';
import { Endpoint } from '@rest-hooks/endpoint';

class User extends Entity {
  readonly id: string = '';
  readonly username: string = '';

  pk() { return this.id;}
}

const UserDetail = new Endpoint(
    ({ id }) ⇒ fetch(`/users/${id}`),
    { schema: User }
);
```

Here we're only using the class to define the members and endpoints are their own thing. (Note this requires using rest hooks 5, but a similar thing can be done with older versions.)

**Comment by atefBB** [comment]
Thanks a lot!
That's made more sense for me!
