### ISSUE TITLE
useFetcher callback?

### ISSUE THREAD

**Issue by Secretmapper** [coinbase/rest-hooks#426]
When using `createShape`, what is the recommended way of triggering a callback?

For example, when creating an article, we might want to redirect to the newly created article.

I think `updateParams` could be used but I don't think it's made for the purpose.

Addendum, is there a way to know the status of the fetcher? i.e. a loading indicator for an article being created

**Comment by ntucker** [comment]
Thanks for the question, @Secretmapper!

TL;DR) Chain promises from return value of useFetcher()

The function returned from [useFetcher()](https://resthooks.io/docs/getting-started/usage#dispatch-mutationdocsapiusefetcher)'s return value is a promise resolving to the response of the fetch.

Therefore, we can modify the example to chain something after the fetch is complete. We could also track some local state here if we wanted the status of that particular fetch. (There is a way to get this from the meta-data in state, but probably not recommended to use that now)

```typescript
const create = useFetcher(ArticleResource.createShape());
const submitHandler = useCallback(async (e) => {
  const res = await create({}, new FormData(e.target));
  // redirect here
  return res;
}, [create]);
```

**Comment by Secretmapper** [comment]
Thanks @ntucker! I didn't realize that `create` returned a promise. This works splendidly thank you!

**Comment by ntucker** [comment]
Hmm, what's the type of your createShape()? useFetcher() should have a very specific return type.
