### ISSUE TITLE
Showing Upload Progress

### ISSUE THREAD

**Issue by Secretmapper** [coinbase/rest-hooks#429]
**Is your feature request related to a problem? Please describe.**
In our app, we need to show the upload progress of a `File` in `FormData`, which creates a new entity.

**Describe the solution you'd like**
It would be great if this was supported, but since the callback needs to be passed in the network layer, this seems to be a problem (unless we pass it to the `FetchShape`?)

**Describe alternatives you've considered**
Right now, I simply created a custom method that would invalidate certain records (the file creation would affect certain entities).

I'm mostly interested in knowing what kind of solutions are recommended or the community thinks about. I understand it's a rare edge case that the workaround may be the best solution.

**Comment by ntucker** [comment]
https://resthooks.io/docs/guides/loading-state#loading-buttons does this cover your use case?

**Comment by ntucker** [comment]
Closing this since no reply for 14 days and it seems to be covered in docs. Feel free to open if you have suggestions for docs improvements or this doesn't cover your case!
