### ISSUE TITLE
useStatefulResource with pagination

### ISSUE THREAD

**Issue by ranyefet** [coinbase/rest-hooks#449]
Hello, 

I'm looking into integrating `rest-hooks` into my app. My first use case is fetch list of resources with pagination.

**React version** 16.13.1

**Concurrent mode** no

**Describe the bug**
I'm using `useStatefulResource` in order to access `loading` state.
I'm also using infinite scrolling pagination to load the next page.

On initial load of page, `loading` is set to `true` and everything works as expected.
When I reach the end of page, the next page data get's loaded correctly but `loading` is always `false`.

**Example code**
```js
export function useIssues() {
  const defaultParams = {
    sort: 'severity',
    order: 'desc',
    skip: 0,
    limit: 200,
  };

  const { queryParams } = useNavigation();

  const { data, loading, error } = useStatefulResource(IssueResource.listShape(), {
    ...defaultParams,
    ...queryParams,
  });

  const getNextPage = usePaginator(IssueResource.listShape(), {
    ...defaultParams,
    ...queryParams,
  });

  const { data: issues = [], pagination } = data;

  return {
    issues,
    loading,
    error,
    pagination: {
      ...pagination,
      hasNextPage: hasNextPage(pagination),
    },
    defaultParams,
    fetchMore: () => getNextPage(pagination),
  };
}
```

**Expected behavior**
I expect the `loading` will be set to `true` when calling `getNextPage`.

Am I missing anything? 
Thanks!

**Comment by ranyefet** [comment]
I've managed to get the `loading` state by wrapping the `fetchMore` function with `useLoadingFunction` described here:
https://resthooks.io/docs/guides/loading-state

It still feel a bit strange to get the loading state from two different places 🤷🏽‍♂️

**Comment by ntucker** [comment]
The reason for two distinct loading trackers is that it would be undesirable when loading 'more' data on a list to show a loading spinner for the whole list instead of just showing the existing items. Because of that two distinct experiences should be created for each case (loading the initial part, and loading more).
