### ISSUE TITLE
Pagination does not work for the third page

### ISSUE THREAD

**Issue by ranyefet** [coinbase/rest-hooks#454]
**React version** (e.g., 16.13.1)

**Concurrent mode** no

**Describe the bug**

Hello,

I followed the instruction on [Infinite Scrolling](https://resthooks.io/docs/guides/infinite-scrolling-pagination) page.
Everything appeared to work, but only for the first and second pages. When I keep asking for the next page, I keep getting the second page.

My API returns data in the shape of:

```js
{
  data: [{ id, title, whatever... }],
  pagination: {
    total: 100,
    skip: 0,
    limit: 4,
  }
}
```

I'm using the `pagination` object to calculate the next page. My issue is that it is not updated after the second page.

**Code example**

```js
// base-resource.js
import { Resource } from 'rest-hooks';

export class BaseResource extends Resource {
  static detailShape() {
    return {
      ...super.detailShape(),
      schema: { data: this.asSchema() },
    };
  }

  static listShape() {
    return {
      ...super.listShape(),
      schema: { data: [this.asSchema()], pagination: { skip: 0, limit: 0, total: 0 } },
    };
  }

  static appendList(newResponse, oldResponse) {
    // In case there are duplicates, Set will eliminate them.
    const set = new Set([...(oldResponse?.data ?? []), ...newResponse.data]);

    return {
      ...newResponse,
      data: [...set.values()],
    };
  }
}
```

```js
// use-paginator.js
import { useCallback } from 'react';
import { useFetcher } from 'rest-hooks';
import { BaseResource } from '../api/resources/base-resource';

export function usePaginator(fetchShape, params) {
  // the second argument here is really important - it indicates that requests should be deduped!
  const getNextPage = useFetcher(fetchShape, true);

  return useCallback(
    ({ skip, limit }) => { // pagination has old value <------ PROBLEM HERE
      // calculate the next "skip" value 
      return getNextPage({ ...params, skip: skip + limit }, undefined, [
        // this instructs Rest Hooks to update the cache results specified by the first two members
        // with the merge algorithm of the third.
        [fetchShape, params, BaseResource.appendList],
      ]);
      // "params && fetchShape.getFetchKey(params)" is a method to serialize params
    },
    [getNextPage, params && fetchShape.getFetchKey(params)]
  );
}
```

```js
// use-issues.js
const defaultParams = {
  sort: 'severity',
  order: 'desc',
  skip: 0,
  limit: 4,
};

export function useIssues() {
  const { queryParams } = useNavigation();

  const { data, loading, error } = useStatefulResource(IssueResource.listShape(), {
    ...defaultParams,
    ...queryParams,
  });

  const { data: issues = [], pagination = {} } = data; // pagination is updated

  const getNextPage = usePaginator(IssueResource.listShape(), {
    ...defaultParams,
    ...queryParams,
  });

  return {
    issues,
    loading,
    error,
    pagination: {
      ...pagination,
      hasNextPage: hasNextPage(pagination),
    },
    defaultParams,
    fetchMore: () => getNextPage(pagination), // pagination has old value
  };
}
```

**Expected behavior**
For some reason the `pagination` object is not updated when passed to `getNextPage`.

**Additional context**
When page load, the first request has the following query params:
```
/api/issues?limit=4&order=desc&skip=0&sort=severity
```

When I call `fetchMore` the 2nd request has the following query params:
```
/api/issues?limit=4&order=desc&skip=4&sort=severity
```

If I call `fetchMore` again. `skip` query param is not updated and still `4`, should be `8`.
It's not updated because the pagination object passed to `getNextPage` has:
```
{ skip: 0, limit 4 }
```

I even tried removing the `useCallback` from `usePaginator`, but still getting old `pagination` object.

Help is appreciated, 
Thanks!

**Comment by ntucker** [comment]
```
pagination: { skip: 0, limit: 0, total: 0 }
```

What is the skip, limit returned from the second result? Is it the 'current' or 'next'? Is it being updated?

PS) If you use v5 you can use debugging tool: https://resthooks.io/docs/next/guides/debugging

**Comment by ranyefet** [comment]
Hey Nathaniel, the pagination object is the current page.
So when page loads, the pagination in response is:
```
pagination: { skip: 0, limit: 4, total: 100 }
```

When I call fetchMore, the 2nd response pagination is: 
```
pagination: { skip: 4, limit: 4, total: 100 }
```

In order to calculate the next `skip` value  I’m adding the current `skip` + `limit`.

I used the debugger but didn't saw anything I haven't already saw in the network tab :(

**Comment by ntucker** [comment]
Can you trace what the values are in the line `// calculate the next "skip" value `?

And also after `const { data: issues = [], pagination = {} } = data; // pagination is updated` output `pagination`?

**Comment by ntucker** [comment]
If you want, I can walk through this with you in the discord channel https://discord.gg/uwaSvN3Y

**Comment by ranyefet** [comment]
@ntucker I appreciate the quick response and willingness to help 🥇
