### ISSUE TITLE
After cache is cleared, some resources are never re-fetched

### ISSUE THREAD

**Issue by michael-swarm** [coinbase/rest-hooks#467]
**React version** (e.g., 16.8.5)
16.13.1

**Concurrent mode** yes/no
no

**Rest Hooks version** (e.g., 4.5.9)
4.5.9

**Describe the bug**
After resetting the cache (using `useResetter()`), some resources get stuck in a state where they are never refetched, causing any component that depends on them (using `useResource()`) to be stuck in suspense mode.

**To Reproduce**
1. Attempt to load a slow-loading resource using `useResource()`.
2. While this resource is loading, reset the cache using `useResetter()`.
3. Attempt to load the same resource again.
4. Observe the component stuck in suspense.

**Expected behavior**
In step 3, the resource should be re-fetched.

**Additional context**
I'm guessing it has to do with [this line](https://github.com/coinbase/rest-hooks/blob/rest-hooks%404.5.9/packages/rest-hooks/src/state/NetworkManager.ts#L168). The promise is indeed already present in `this.fetched`, but it's rejected:
![context](https://user-images.githubusercontent.com/67399102/104669759-91b80380-568f-11eb-88a8-d0640803094a.png)

So I'm assuming something in the network manager cleanup should be removing this, or the line referenced above should be checking to see if the promise is still pending, not just if it's present.

Hopefully this is enough info to track down the bug (or tell me what I'm doing wrong), but if not I can try to create a minimal example to reproduce this.

Thanks for an awesome library!

**Comment by ntucker** [comment]
Can you try out the v5 rc? This should be fixed there.

**Comment by michael-swarm** [comment]
I tried to upgrade, but it appears to be a non-trivial effort to port my code. Any chance of a fix making into 4.5?

**Comment by ntucker** [comment]
Behavioral question: in 5 the inflight requests that are rejected show up as thrown errors in components (this way they don't have the suspense problem). I'm curious if this seems like a good behavior or if possibly some other behavior would be better? Perhaps it should restart the fetch instead?

**Comment by michael-swarm** [comment]
Yeah, restarting the fetch was what I was expecting here. Unless this is different in 5, I assume the error would be handled by a `NetworkErrorBoundary`, so it seems like clearing the cache would show that instead of `Suspense`, forcing the user to reload the page anyway.

Here's my use case, if it's helpful:
- I'm using the page visibility API to reset the cache whenever the page becomes visible. This is meant to prevent my app from displaying stale data if the page has been left open a while.
-  I've set up my `NetworkErrorBoundary` fallback to redirect to a login page if I get a 401 from the server. This generally happens when the session expires.
- If you bring the page to the front after the session expires, the cache is reset at the same time that new requests are being sent (and receiving 401s).

What I'd expect to happen in this case is to be redirected to login (this works) and then, upon logging in, have all new requests sent (this is what breaks).

In writing this, I realized the problem only occurs when I return to an expired session -- that is, where the requests had error responses.

**Comment by michael-swarm** [comment]
I should also mention that the login page is outside of the `CacheProvider`, so the `CacheProvider` is unmounted when redirecting to login.

**Comment by ntucker** [comment]
If CacheProvider is unmounted, how are you getting infinite suspense? Or are there two use cases you're describing here?

**Comment by michael-swarm** [comment]
The infinite suspense happens after logging back in. Which I suppose means it's a new `CacheProvider` instance, so now I'm really confused...

**Comment by michael-swarm** [comment]
Ah, ok I see -- the `NetworkManager` [is a singleton](https://github.com/coinbase/rest-hooks/blob/rest-hooks%404.5.9/packages/rest-hooks/src/react-integration/provider/CacheProvider.tsx#L58). Unmounting the `CacheProvider` [only calls `cleanup()` on it](https://github.com/coinbase/rest-hooks/blob/rest-hooks%404.5.9/packages/rest-hooks/src/react-integration/provider/CacheProvider.tsx#L42). This is the function that [generates the `CleanupErrors`](https://github.com/coinbase/rest-hooks/blob/rest-hooks%404.5.9/packages/rest-hooks/src/state/NetworkManager.ts#L81).

**Comment by ntucker** [comment]
You could manage the lifecycle of the managers yourself to solve this specific problem. However, I'd recommend instead persisting the CacheProvider after logout - and simply calling reset when that happens. If you change components that should avoid any issues.

Regarding v5: Final version recently released https://github.com/coinbase/rest-hooks/releases/tag/rest-hooks%405.0.0
Other than the new behaviors around invalidation+deletes, the only hard breaking change is the manager interfaces and some stricter types (that will find existing bugs). (I was able to do a quick migration for another project here: https://github.com/airbytehq/airbyte/pull/1736) Another thing I found was I accidentally relied on typescript 4 feature (named tuples). Will release a fix for that shortly.

I'm curious what challenges you ran into? Are you implementing customer managers. This can help me provide easier migration as well as write the migration guide.

## Design

Another question, is about this visibility mechanism...do you just want fresh data, or cannot show stale data? Because if you clear the cache the user is forced to see loading spinnies everytime they switch to the tab - even if they were just there. This might not be an ideal user experience. Would it be good if perhaps any *stale* data is refetched in teh background when the tab is visible? If so this might be added as a feature to rest-hooks itself.

**Comment by michael-swarm** [comment]
Congrats on the v5 release!! It seemed to have broken my overridden methods in my Resources, but that might just be due to the TypeScript changes. Thanks for the example, I'll give it another try now that it's official.

Personally, when I actually manually clear/reset the cache, I don't want to get any stale data after that. This use case is a good example why, actually -- if I'm using it to clear state on logout, and then the user logs in to a different account, I don't want them to see a flash of the data from the previous account.

**Comment by michael-swarm** [comment]
Actually you were right, it was pretty easy to switch to v5, and the bug is indeed fixed there! It was just TypeScript changes, including adding a `schema` to one of my shape overrides to get the type check to pass (which is already mentioned in the documentation). I did notice that the documentation all says `create()`, `delete()`, etc., but the functions still seem to be names `createShape()`, deleteShape()`, etc.

**Comment by ntucker** [comment]
Yup, once you're on v5 you can merrily migrate to the new Resource from `@rest-hooks/rest`. That's what all the new docs reference. The export from `rest-hooks` is just there for legacy reasons to make upgrades ez. :) That export will be deprecated in 5.1 probably.

**Comment by ntucker** [comment]
Regarding types - I have an explanation going up on docs site soon https://github.com/coinbase/rest-hooks/pull/486/files#diff-0ab0428a5fb5dbcd85cd942fb836a6f6ce5ff7b511a2fddd1e76230f55f3b72a

Use cases:
I was under the impression there were two use cases:
- Logout - where it should def reset cache
- Page becomes visible - where we want to get fresh data

**Comment by michael-swarm** [comment]
Yes, good point, the two use cases are different in that regard, the stale data might be better for the page visibility case. Maybe it could be an argument to the function? Something like `allowStale: false`.

**Comment by ntucker** [comment]
With 5.0.1 released fixing the holdups I'm gonna close this. Feel free to reopen with any other issues!
