### ISSUE TITLE
Make it possible to bypass expected keys check in v5

### ISSUE THREAD

**Issue by michael-swarm** [coinbase/rest-hooks#492]
**Is your feature request related to a problem? Please describe.**
Version 5 has [a new check](https://github.com/coinbase/rest-hooks/blob/rest-hooks%405.0.0/packages/normalizr/src/entities/Entity.ts#L69) in development builds that compares the response from the server against the corresponding Entity's schema. This is very helpful in general to find things like misspellings and unexpected responses, but there is no way to bypass it. Furthermore, there is no way to say that a field is expected to be missing.

In my case, I have a field that the server doesn't send at all if it isn't filled in (it's the last date an action occurred, if the action has never occurred the field is missing). This triggers the check and breaks my app. It was actually quite helpful information, but now I have no way to un-break the app in development short of commenting out that field (which is important when filled in).

**Describe the solution you'd like**
Instead of throwing an `Error` from this check, just log an error to the console. This would make the behavior of the library the same in development and production, and is in line with React's approach for strict-mode checks.

**Describe alternatives you've considered**
- Provide a way to mark a field as optional. I'm not sure how that would work though.
- Provide a way to dismiss this check. As in, you'd get an error once and could say "don't bug me about this again". Again, I'm not sure how that would work.
- Provide a way to disable this check completely (even in a development build). The disadvantage of this is that the check is quite helpful, and as soon as you had one response that isn't compatible with it, you'd have to turn it off for good.

**Comment by ntucker** [comment]
Thanks for the report! This is really helpful in tuning these dev warnings.

Question - for these optional fields, what do you have a default value? Currently the way we mark optional entities is via a null default. We could have undefined or null for any field work as optional potentially.

We could add some kind of property to disable for a given Entity/Resource like `disableSchemaValidation`. To make opt-out easy for the extreme cases - especially while it is tuned.

**Comment by ntucker** [comment]
Actually I'm curious if you could go into detail on where you have optional members. what kind of data do they have and what are their forms?

**Comment by michael-swarm** [comment]
> Thanks for the report! This is really helpful in tuning these dev warnings.

Thanks for the quick response!

> Question - for these optional fields, what do you have a default value? Currently the way we mark optional entities is via a null default. We could have undefined or null for any field work as optional potentially.

I was thinking along the same lines, until I realized you might actually want to be able to set a reasonable default in those cases. For example, perhaps "missing" means zero in some API (which isn't such a crazy example, [you can easily configure Jackson to do this](https://fasterxml.github.io/jackson-annotations/javadoc/2.7/com/fasterxml/jackson/annotation/JsonInclude.Include.html#NON_DEFAULT)).

> We could add some kind of property to disable for a given Entity/Resource like `disableSchemaValidation`. To make opt-out easy for the extreme cases - especially while it is tuned.

This would definitely unblock me, though it would be nice if the validation is still performed, but any issues are just logged as errors to the console. This way, the validation doesn't block development, but I also don't forget about it. For example, I might need to make some non-trivial changes to my code to handle a missing field, but I want to keep developing something else in the meantime. I'd still actually prefer it worked this way by default, but adding a property to my Resource superclass would be easy enough.

**Comment by michael-swarm** [comment]
> Actually I'm curious if you could go into detail on where you have optional members. what kind of data do they have and what are their forms?

Sorry, just saw this question after I sent my reply! The case I have is a date field, the date represents the time a device was last heard from. If the device is brand new and has never been activated, there is no such date, so the field is empty. Our API happens to represent this by leaving out the field from the response entirely. There are probably plenty of similar cases with dates (e.g. user's last login date).

More generally, as frontend developers we often have to work with APIs we can't change for one reason or another (as I'm sure you know), so I think having some flexibility to work with weird responses is important (like in the Jackson configuration example I gave above). The validation check is super useful for cases where the response was unexpected, but there will always be exceptions, so we need some flexible way to say they *are* expected.

**Comment by ntucker** [comment]
Looking over the code I'm realizing the missing fields case is only if you have 0 fields and 2 or more fields specified. That's probably not clear from the error. I'm curious if you actually have some fields being returned that you haven't set a default for.

**Comment by ntucker** [comment]
An idea I have for controls is three levels.

`static memberChecks: Error | Warn | Silent = Error`

**Comment by michael-swarm** [comment]
I double-checked, and everything has a default. I consistently get an error if I add a property that doesn't have a corresponding field in the response, even if it has a default. I have multiple "unexpected keys", which are just fields I don't care about, and those don't seem to ever trigger an error.

**Comment by michael-swarm** [comment]
OK, I see the problem actually after a closer read of the code. You're using > 50% of the keys being unexpected as a heuristic for a bad schema. I just happen to have exactly 50% (16 of 32) that I care about, so as soon as I add one more that doesn't match, or if any one of the fields is missing, it breaks.

This is actually pretty surprising behavior, especially since the error wasn't clear about why it was triggered (which I see you fixed in your PR, thanks!). It's actually a common use case for me as our API has a lot of extra data that isn't used in the frontend, so I just leave out the fields I don't use. And 50% seems pretty arbitrary. Not that I have a better suggestion. 😆

**Comment by ntucker** [comment]
Yeah this use case of fields you don't use is totally legit. What I'd really want is if all your fields are found you can have unlimited unexpected fields - but then optional members would break it. An insight I'm seeing here is that the more found members, the more confidence we have that we're matching something - so the more forgiving we can be with unexpected members. Added an *additional* requirement to trigger this mismatch `found.length ** 1.5 / 2 <= unexpected.length`. This means at 4 found members, 4 mismatches is enough, but at 16 (like yours), it requires 32 unexpected members.

**Comment by ntucker** [comment]
New heuristic for warning vs error - if at least 4 members are found, it will only warn.

**Comment by michael-swarm** [comment]
Nice! I think that's a good call.

**Comment by ntucker** [comment]
@michael-swarm released in 5.0.1!
