### ISSUE TITLE
Wrong stale data

### ISSUE THREAD

**Issue by ranyefet** [coinbase/rest-hooks#502]
**React version** 16.13.1

**Concurrent mode** no

**Rest Hooks version** 4.5.9

**Describe the bug**

Hey! 👋🏽

I'm getting wrong stale data when changing query parameters.

First request made to:  `/api/issues-filters?`
Returns response `A`.

Second request made to: `/api/issues-filters?severities%5B0%5D=critical`
Returns response `B`.

Third request is back to: `/api/issues-filters?`
There's no network request as expected. But the response I get back is `B` while I expected it to be `A`.

I'm using `useStatefulResource` to fetch data.

```js
const { data: newData, loading, error } = useStatefulResource(
    IssueFiltersResource.filtersShape(),
    queryParams
  );
```

The response

**To Reproduce**
1. Make request without params
2. Make another request with params
3. Make another request without params like first request

**Expected behavior**
Expected to get the correct cached response based on `getFetchKey`.  Actual result is getting the last cached response.

**Comment by ntucker** [comment]
Can you share what `IssueFiltersResource.filtersShape().getFetchKey()` is?

**Comment by ntucker** [comment]
PS) If you're able to get onto v5 - https://resthooks.io/docs/guides/debugging is really useful in figuring these things out.

**Comment by ranyefet** [comment]
This is `getFetchKey`. I'm using [qs](https://github.com/ljharb/qs) to stringify the query params.

```
getFetchKey: params => `api/issues-filters?${qs.stringify(params)}`,
```

I will try to upgrade to v5 and see if it helps.

**Comment by ranyefet** [comment]
Ok, I've upgraded to v5 and while upgrading i figured what was the issue.

I was caching the entities of `IssueFiltersResource` response while I should have just cache the entire response since it's a singleton endpoint.

Closing this, thanks!

**Comment by ntucker** [comment]
@ranyefet just for my curiosity, can you share a sample response from this endpoint?
