### ISSUE TITLE
Content-Type: application/json is for multipart form uploads

### ISSUE THREAD

**Issue by erik-stephens** [coinbase/rest-hooks#550]
**React version** (e.g., 16.8.5)

17.0.1

**Concurrent mode** yes/no

no

**Rest Hooks version** (e.g., 4.5.9)

5.0.4

**Describe the bug**

Incorrect Content-Type header when PUT'ing multipart form data - [looks to be hard-coded here](https://github.com/coinbase/rest-hooks/blob/28b79aea6d280aa74abeea1d4d2ab14678edf9de/packages/rest-hooks/src/resource/Resource.ts#L35).

**To Reproduce**

I defined a custom endpoint for uploading photos.  The only thing I overrode was `url()` to something like `/users/${id}/photo`.  I used:
```javascript
const addPhoto = useFetcher(User.addPhoto())
const form = new FormData()
form.append('photo', newPhoto)
await addPhoto({id}, form)
```

**Expected behavior**

Some options:

1. Don't specify Content-Type and let `fetch()` auto-detect.
2. Specify based on the payload.
3. Provide a way for users to specify in custom endpoints or when calling the fetcher.

I suspect option 3 is already available to us but I couldn't figure it out.  I know how to modify fetch headers per Resource but not per Endpoint or per fetch.

**Additional context**

The app server (expressjs w/multer for multipart handling) complains with "PayloadTooLargeError: request entity too large".  I'm using FormData for the payload.  When using rest-hooks, I see `Content-Type: application/json` in the request headers.  When using native fetch, I see `Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryK3OGAXCjDS0o4nMX` which works.  I did not have to specify Content-Type - it was auto-detected correctly.

Thank you!

**Comment by ntucker** [comment]
Would love to write a test for this to make sure it works. Could you help me by providing what the value of `newPhoto` is? Is it a binary blob?

**Comment by erik-stephens** [comment]
Yes, a binary blob.  I suspect can reproduce with any payload of multipart form data (not json) - I doubt the binary field is the key.  I forgot to mention in case this detail is important: it was the OPTIONS pre-flight request that was producing that "PayloadTooLargeError".

**Comment by ntucker** [comment]
Hmm, so I created a test for this only to discover that it was working fine before. I'm not testing OPTIONS though. The main request has `multipart/form-data; boundary=--------------------------562837534142693661170268`

Can you paste the *full* request for OPTIONS and the PUT? (including headers, etc.)

**Comment by ntucker** [comment]
In case this is an oddity in the fetch mocking in node, can you use this in your Resource and tell me if it changes anything:

```typescript
  /** Perform network request and resolve with HTTP Response */
  static fetchResponse(input: RequestInfo, init: RequestInit) {
    const options: RequestInit = init.body
      ? init
      : {
          ...init,
          headers: {
            'Content-Type': 'application/json',
            ...init.headers,
          },
        };
    console.log(input, options);
    return fetch(input, options)
      .then(response => {
        if (!response.ok) {
          throw new NetworkError(response);
        }
        return response;
      })
      .catch(error => {
        // ensure CORS, network down, and parse errors are still caught by NetworkErrorBoundary
        if (error instanceof TypeError) {
          (error as any).status = 400;
        }
        throw error;
      });
  }
```

**Comment by ntucker** [comment]
Tested this in browser and got the same behavior you did. Turns out the polyfill was bugged - updating it made the previous case fail. Will update the PR soon

**Comment by erik-stephens** [comment]
Thanks for looking into it!  I'll stand by for a release with #552 in it.  Let me know if you prefer me to try it out before cutting a new release.

**Comment by ntucker** [comment]
Published in https://github.com/coinbase/rest-hooks/releases/tag/%40rest-hooks%2Frest%401.0.3

**Comment by erik-stephens** [comment]
I updated to 1.0.3 and can confirm that it works.  Thanks again!
