### ISSUE TITLE
Type error when using Resource.detail() but not when using detailShape()

### ISSUE THREAD

**Issue by C94P** [coinbase/rest-hooks#569]
**React version** 17.0.1

**Concurrent mode** no

**Rest Hooks version** 5.0.5

**TypeScript version** 4.1.5

**Describe the bug**
I recieve a type error when using Resource.detail() but not when using detailShape(). The typings indicate that this method is deprecated but I am following along with the Getting Started guide. 

Apologies if I have missed this issue being raised already or something glaringly obvious. I did have a good hunt round for this on the Repo.

**To Reproduce**
1. Set up example on [getting started](https://resthooks.io/docs/getting-started/usage) using latest React and rest-hooks. 
2. Observe type error when using ```const article = useResource(ArticleResource.detail(), { id });```
3. Type error dissapears if method changed to ```const article = useResource(ArticleResource.detailShape(), { id });```

**Additional context**
TS error recieved

`(alias) class ArticleResource
import ArticleResource
No overload matches this call.
  Overload 1 of 17, '(v1: readonly [ReadShape<any, any, any>, any], v2: readonly [ReadShape<any, any, any>, any]): [any, any]', gave the following error.
    Argument of type 'Pick<{ schema: SchemaDetail<ArticleResource>; }, never> & Pick<EndpointInstance<(this: EndpointInstance<FetchFunction<any, any, any>, string | { ...; } | Schema[] | SchemaSimple<...> | Serializable<...>, true> & { ...; }, params: any) => Promise<...>, undefined, undefined> & { ...; }, "url" | ... 4 more ... | "getFe...' is not assignable to parameter of type 'readonly [ReadShape<any, any, any>, any]'.
  Overload 2 of 17, '(fetchShape: ReadShape<any, any, any>, params: { id: number; }): any', gave the following error.
    Argument of type 'Pick<{ schema: SchemaDetail<ArticleResource>; }, never> & Pick<EndpointInstance<(this: EndpointInstance<FetchFunction<any, any, any>, string | { ...; } | Schema[] | SchemaSimple<...> | Serializable<...>, true> & { ...; }, params: any) => Promise<...>, undefined, undefined> & { ...; }, "url" | ... 4 more ... | "getFe...' is not assignable to parameter of type 'ReadShape<any, any, any>'.
      Types of property 'type' are incompatible.
        Type '"mutate"' is not assignable to type '"read"'.ts(2769)`

**Comment by ntucker** [comment]
Can you share the implementation of ArticleResource - including import statements? Note, `import { Resource } from '@rest-hooks/rest'` in the docs - Resource importing from the @rest-hooks/rest library rather than 'rest-hooks' library.

**Comment by C94P** [comment]
Thanks a bunch for the prompt @ntucker, It's just copy and pasted from the article. I'll be able to get a codesandbox set up for you later today if that's alright with you. 

Here's my Article.ts:
```TypeScript
import { Resource } from '@rest-hooks/rest';

export default class ArticleResource extends Resource {
  readonly id: number | undefined = undefined;
  readonly title: string = '';
  readonly content: string = '';
  readonly author: number | null = null;
  readonly tags: string[] = [];

  pk() {
    return this.id?.toString();
  }

  static urlRoot = 'http://test.com/article/';
}
```

**Comment by ntucker** [comment]
That would be great, thanks @C94P ! Often a full reproduction example isn't needed because it's clear what the problem is - but in this case I just can't reproduce it myself so it would be helpful getting to the bottom of it.

**Comment by ntucker** [comment]
Also can you try the just publish @rest-hooks/rest@1.0.4 version and see if this is still a problem?

**Comment by C94P** [comment]
Gave the latest release a try and still no luck unfortunately. 
I have attempted to set up a [codesandbox here](https://codesandbox.io/s/rest-hooks-error-0onof) but it's throwing errors that the module doesn't exist. I'm afraid that's all I can provide at this point, it's set up exactly the same as my minimal test scenario.

Let me know if you have any other suggestions. Could it be related to the TS or Node version I'm running?

**Comment by ntucker** [comment]
I got this to work in runtime https://codesandbox.io/s/rest-hooks-error-forked-fn7hh?file=/src/resources/article.ts (the api is not real so it throws an error as expected)

However, somethings borked with codesandbox's typescript stuff so it doesn't really show whether typing works correctly.

**Comment by ntucker** [comment]
Can you try running https://github.com/ntucker/anansi/tree/master/examples/typescript ? This is an example that uses a real API.

**Comment by saaymeen** [comment]
I happened to come across the same typescript problem recently, with exactly the same symptoms as @C94P. I am on `@rest-hooks/rest@2.0.2` and `rest-hooks@5.0.13` with `typescript@4.2.3`. I tried to create a codesandbox, but it really seems like their typescript is weird anyway. My same setup on codesandbox could not reproduce this issue however.
I use the `useResource` hook provided in the `rest-hooks` package and the `Resource` implementation from `@rest-hooks/rest`. Maybe someone else has an idea since `detailShape()` does not produce any warning (except about the deprecation).

**Comment by ntucker** [comment]
@saaymeen Thanks for sharing! Do you think you can get a reproduction in a sample repo on github that we can clone instead? Maybe with one of the bad Resources and the tsconfig. Would love to be able to figure out what's going on, but I haven't been able to experience this myself so sort of at a loss for now.

Also if you could try using the same shape with [useCache()](https://resthooks.io/docs/api/useCache) and paste the error - this hook has more readable errors than [useResource()](https://resthooks.io/docs/api/useresource)

**Comment by ntucker** [comment]
I have a theory...please reopen if this doesn't work

**Comment by ntucker** [comment]
@saaymeen try upgrading to https://github.com/coinbase/rest-hooks/releases/tag/%40rest-hooks%2Fendpoint%401.0.8 and see if it persists

**Comment by ntucker** [comment]
@C94P @saaymeen - if you have time, can you validate release 5.0.15 of rest-hooks? 🙏

**Comment by saaymeen** [comment]
> @C94P @saaymeen - if you have time, can you validate release 5.0.15 of rest-hooks? pray

Does not seem to resolve the issue for me. I bumped the version on my [example repo](https://github.com/saaymeen/rest-hooks-shape-type-issue), but the issue persists. Changing `strict` to `true` in tsconfig.json removes the error, but leaving it on `false` will still trigger it.

**Comment by ntucker** [comment]
@saaymeen 5.0.16 seems to work on the repo now

**Comment by saaymeen** [comment]
> @saaymeen 5.0.16 seems to work on the repo now

I can confirm that 5.0.16 solves the issue. Thank you lots for your time and dedication!
