### ISSUE TITLE
Error: could not find react-redux context value; please ensure the component is wrapped in a <Provider>

### ISSUE THREAD

**Issue by brockjgriffin** [coinbase/rest-hooks#570]
import React from 'react';
import './App.css';
import Header from './Header';
import Sidebar from './Sidebar';
import { BrowserRouter as Router, Switch, Route, Link } from "react-router-dom";
import Mail from './Mail';
import EmailList from './EmailList';
import SendMail from './SendMail';
import { useSelector } from 'react-redux';
import { selectSendMessageIsOpen } from './features/mailSlice';

function App() {
  const sendMessageIsOpen = useSelector(selectSendMessageIsOpen);
  //The error is pointing the the line of code above 
  
  return (

    <Router>
    <div className="App">
    <Header />

    <div className='app_body'>
    <Sidebar />

  <Switch>
      <Route path='/mail'>
        <Mail />
      </Route>
        <Route path='/'>
          <EmailList />
        </Route>
      </Switch>
    </div>

      <SendMail />
  </div>
    </Router>
    
    
  );
}

export default App;

**Comment by ntucker** [comment]
I think you want to do this: https://react-redux.js.org/introduction/quick-start#provider

The repo for react-redux is here: https://github.com/reduxjs/react-redux
