### ISSUE TITLE
Attempted import error: 'DevToolsConfig' is not exported from './DevtoolsManager'.

### ISSUE THREAD

**Issue by skoging** [coinbase/rest-hooks#636]
**Rest Hooks version** (e.g., 4.5.9)
 rest-hooks: 5.0.8 and 5.0.9

v5.0.7 works as expected.

**Describe the bug**

```
Attempted import error: 'DevToolsConfig' is not exported from './DevtoolsManager'.
```

I think this is a problem with the build output, the source code looks good.

**Comment by ntucker** [comment]
Fixed in #619
