### ISSUE TITLE
Typings are broken 

### ISSUE THREAD

**Issue by sylvaingi** [coinbase/rest-hooks#68]
**React version** (e.g., 16.8.5) 16.8.6

**Concurrent mode** no

**Describe the bug**
Since 1.6.1 TypeScript fails to infer return type of `useResource`, it falls back to `any`:

<img width="538" alt="Capture d’écran 2019-05-27 à 17 38 51" src="https://user-images.githubusercontent.com/371494/58430218-c933ff80-80a8-11e9-8189-49ce0659eb96.png">

With tsc `traceResolution` flag, the compiler complains about unresolved modules within the typing files: `~/resource`, `~/types`, `~/state/NetworkManager`, etc.

Looks like the regression happened in https://github.com/coinbase/rest-hooks/commit/7aecc9a0cef49ab31f8cf895169a4b5538962e49.

**To Reproduce**
1. use `useResource` hook with version `1.6.1`. 

**Expected behavior**
Correct inference, like in versions < 1.6.1 :

<img width="573" alt="Capture d’écran 2019-05-27 à 17 38 23" src="https://user-images.githubusercontent.com/371494/58429902-a81edf00-80a7-11e9-85b4-06479f0f48cd.png">

**Comment by ntucker** [comment]
Good catch. Will look into this immediately. Thanks for the report!

**Comment by ntucker** [comment]
I need to find a workaround due to this https://github.com/Microsoft/TypeScript/issues/10866

**Comment by sylvaingi** [comment]
Due to this kind of issues I've always avoided using the `paths` compiler option in npm packaged libs. Besides plugging a transform like https://www.npmjs.com/package/@zerollup/ts-transform-paths, I don't see how tsc could output correct typings.

**Comment by ntucker** [comment]
Yeah, I just found that package. If it doesn't work out I'll just revert the commit. 1.6 should work for the time being, but I'll get out a 1.6.2 that fixes this today. :)

**Comment by ntucker** [comment]
Didn't work, filed a bug https://github.com/grrowl/ts-transformer-imports/issues/15. So for now I'll revert until there's resolution there.

**Comment by ntucker** [comment]
Fixed in e8add43108dbc9c417ee8027c41e693f1a299cf3

**Comment by ntucker** [comment]
https://github.com/coinbase/rest-hooks/releases/tag/1.6.2 live!
