### ISSUE TITLE
Cache isn't merging newly received data

### ISSUE THREAD

**Issue by lachiet** [coinbase/rest-hooks#680]
**React version** (e.g., 16.8.5)
16.13.1

**Concurrent mode** yes

**Rest Hooks version** (e.g., 4.5.9)
5.0.0-k.3 (also tested with latest version)

**Describe the bug**
Rest-hooks cache isn't merging newly received data. Specifically a boolean property.

The property that isn't being updated:
```ts
readonly rejected?: boolean = false;
```

This property is only returned from the API when `rejected:true`, otherwise it will be undefined. 

**To Reproduce**
1. Initially fetch a list of resources (no resources have the property "rejected" yet).
2. State change on the BE to update rejected=true.
3. Invalidate resource, re-fetch is triggered, new data is fetched and one resource on the list is displaying the "rejected" flag (works as expected).
4. State change on the BE to update rejected=false.
5. Invalidate resource, re-fetch is triggered, **BUT resource/item isn't updated and still displays rejected.**

**Expected behavior**
The newly fetched data should be merged in and take priority over the stale data in the cache.

**Additional context**
I've provided two things below: 1) everything I've attempted to fix/workaround the issue; and 2) debugging logs from rest-hooks.

**What I've attempted**
- useResource() + invalidate() (the optimal/expected way)
- Imperatively fetch data 
- Rendering - I modified and attempted all solutions with a refresh control in RN to ensure the list is rendered
- Updated how we declare rejected in the resource to be null/false/undefined. Also cleared storage + uninstalled the app, reinstalled to ensure it refreshed the schema.
- Invalidated every endpoint registered in the cache
- Removed any additional logic in getUrl() within resource so there wasn't any difference in cache keys
- Updated to the latest rest-hooks (the mergeDeepCopy functionality has additional logic in the later version).
- [Worked] useResetter() - deletes the rest-hooks state. I considered this as the absolute last resort BUT this proved that something was going wrong within rest-hooks and was the only thing that I tried which worked.

**Debugging rest-hooks**
The goal of logging in the rest-hooks lib was to understand at which point between HTTP response (with fresh data which we observed in the network requests) and the rest-hooks cache.
- [`SimpleRecord.merge()`](https://github.com/coinbase/rest-hooks/blob/master/packages/normalizr/src/entities/SimpleRecord.ts#L64-L74) when we pass the new "incoming" data (which actually has rejected:false), the rejected property/value gets stripped after passing it through `this.toObjectDefined()`. This is why when we merge the two we're using the existing "rejected:true" value.
- The difference between the existing and incoming objects in this func is DefinedMemberKeys ([here](https://github.com/coinbase/rest-hooks/blob/43d7d4245cea4bba5f286167d6f3b2a9d9d47677/packages/normalizr/src/entities/SimpleRecord.ts#L94)) - so somehow when we look up what the keys are and iterate through them, on the new object we don't have "rejected" in the defined keys (so actually a difference in length of 1 for these arrays - the rejected key).

**Comment by ntucker** [comment]
Can you provide your full Resource and Endpoint definition? Including any classes in the hierarchy that aren't from rest hooks itself?

**Comment by ntucker** [comment]
Have you tried https://resthooks.io/docs/guides/debugging if so can you screenshot the receive action for when you expect the update?

**Comment by ntucker** [comment]
>    SimpleRecord.merge() when we pass the new "incoming" data (which actually has rejected:false), the rejected property/value gets stripped after passing it through this.toObjectDefined(). This is why when we merge the two we're using the existing "rejected:true" value.
>   The difference between the existing and incoming objects in this func is DefinedMemberKeys (here) - so somehow when we look up what the keys are and iterate through them, on the new object we don't have "rejected" in the defined keys (so actually a difference in length of 1 for these arrays - the rejected key).

This sounds like the data being sent is not actually including the rejected, and thus if you use the default merge function it will persist the old one. If you simply want to replace the entire copy (which only works if you always return full data - never partial data), you can use the following merge function:

```typescript
  static merge<T extends typeof SimpleRecord>(
    this: T,
    existing: AbstractInstanceType<T>,
    incoming: AbstractInstanceType<T>,
  ) {
    return this.fromJS(incoming);
  }
```

**Comment by ntucker** [comment]
@lachiet did this approach work for you?

**Comment by ntucker** [comment]
Closing as no response indicates it worked. If this is not true please report new issue.
