### ISSUE TITLE
Publish usePaginator hook unit tested

### ISSUE THREAD

**Issue by graphan** [coinbase/rest-hooks#694]
**Is your feature request related to a problem? Please describe.**
You have a nice example in docs how to create a `usePaginator` hook: https://resthooks.io/docs/guides/infinite-scrolling-pagination#create-pagination-hook
It resolves a repetitive problem, so I think it would make sense to include it into rest-hooks and publish it unit-tested.

**Describe the solution you'd like**
Publish it as part of rest-hooks, unit- tested, covering all cases.

**Comment by ntucker** [comment]
Will have something soon.
