### ISSUE TITLE
schema.Values not denormalized

### ISSUE THREAD

**Issue by skoging** [coinbase/rest-hooks#722]
**React version** (e.g., 16.8.5)

**Concurrent mode** yes/no

**Rest Hooks version** (e.g., 4.5.9)

**Describe the bug**
I'm attempting to model an endpoint that returns a dictionary of resources. I've defined a custom endpoint on my resource where I override schema with `new schema.Values(this)`.

The normalization works as expected, but the output from `useResource` is not denormalized.

**To Reproduce**
https://codesandbox.io/s/peaceful-smoke-0ges9?file=/src/App.tsx

**Expected behavior**
I would expect denormalization of Values schema to work.

**Additional context**

**Comment by ntucker** [comment]
Really great example, thanks! Should make this much easier to solve

**Comment by skoging** [comment]
I'm still having some issues when testing this fix. Now the problem is that request is never triggered.

I think the issue has to do with handling of expiry time in `useDenormalized`. With no existing response, the call to [`denormalize`](https://github.com/coinbase/rest-hooks/blob/848e63f3f600ee639a7d941d855eb91047f51881/packages/core/src/state/selectors/useDenormalized.ts#L91) return `value: {}`, `found: true`, `deleted: false`, and `resolvedEntities: {}`. This causes `expiresAt` to be set to `Infinity` and the request is not triggered.

I'd make a repro for this as well, but it looks like this fix isn't published yet so I'm not sure how I'd go about that.

**Comment by ntucker** [comment]
This is good info - should be able to get to bottom of it with this. Thanks!

**Comment by ntucker** [comment]
@skoging Coming soon: https://github.com/coinbase/rest-hooks/pull/732

**Comment by skoging** [comment]
> @skoging Coming soon: #732

Great! That worked 👍
