### ISSUE TITLE
Compositional parallel suspense

### ISSUE THREAD

**Issue by ntucker** [coinbase/rest-hooks#731]
## useAll() - like Promise.all() for suspense

```ts
const [article, users, post] = useAll(
  () => useResource(CoolerArticleResource.detail(), id),
  () => useResource(UserResource.list()),
  () => useResource(Post.detail(), { id }),
);
```

### Why

Currently one can do parallel requests with useResource() by sending variable tuples of normal useResource() arguments.

```ts
const [article, users, post] = useResource(
  [CoolerArticleResource.detail(), id],
  [UserResource.list()],
  [Post.detail(), { id }],
);
```

This is problematic for various reasons
- Not very discoverable
- Makes typing arguments very complicated and obfuscates the errors when types are enforced
- Makes composition of useResource() very challenging
- Doesn't integrate with other suspense hooks one could potentially use - thereby reducing parallelism potential
- Isn't obvious that changing the number of arguments is not supported
- Polymorphic function calls can be confusing to developers, as well as compilers - potentially limiting optimizations.

### Legacy

We can continue supporting useResource() with multiargs, and simply update docs to suggest using this method instead until some long later date where we remove it.

Upgrading should be trivial since it can be fully done with a regex. Should be publish regex?

## Alternatives

Instead of wrapping suspending hooks, we could turn any `Suspendable` into suspense:

```ts
interface Suspendable<T> {
  then: (dat: T) => void;
  key(): string;
}
```

```ts
const [article, users, post] = useAwait(
  useResource(CoolerArticleResource.detail(), id),
  useResource(UserResource.list()),
  useResource(Post.detail(), { id }),
);
```

But useResource() will only return a promise, so to use it in singular case:

```ts
const article = useAwait(useResource(CoolerArticleResource.detail(), id));
```
Also allows suspending useRetrieve():

```ts
const article = useAwait(useRetrieve(CoolerArticleResource.detail(), id));
```

This could be specialized, but then can't have variable args:

```ts
const awaitResource = (...args) => useAwait(useResource(...args));

const article = awaitResource(CoolerArticleResource.detail(), id));
```

'await' prefix can be added to eslint rules of hooks so they are enforced

Pros:
- Allows easy usage with useRetrieve() to not subscribe to state
- Distinguishes suspense in a clear manner
- Interops with anything that can return a promise

Cons:
- Common case is more verbose
- Legacy is not as easy to support
- Doesn't interop with other suspending libraries

**Comment by ljharb** [comment]
This seems very prone to people accidentally breaking the rules of hooks.

**Comment by ntucker** [comment]
How so? It actually seems to solve that problem from what I've seen.

**Comment by ljharb** [comment]
I can’t come up with a concrete example - it certainly solves that problem in your examples - but i worry about otherwise-innocent refactors, especially if it’s implied that it follows Promise semantics.

**Comment by ntucker** [comment]
To be clear this would effectively have the same behavior, just be expressed in a better way. One of the biggest problems with the current approach is that if people change the number of arguments it breaks the rules of hooks - but that's not exposed because they are simply changing args. It's a dirty, dirty thing.

In this case, we expose the repetition nature with actual hooks so if they try to make the number of useResource() calls variable - they are obviously violating hooks in their own code.

**Comment by ljharb** [comment]
That's true; this seems like a strict improvement over the current approach.

**Comment by ntucker** [comment]
Given useAll is not operating on promises - it's sort of like promise.all + await.

Perhaps then the useAwait() concept would be more intuitive?

**Comment by ljharb** [comment]
I think `useAwait` implies promises semantics (which don't follow the rules of hooks consistently) way more strongly than `useAll`.

**Comment by ntucker** [comment]
promise semantics vs rules of hooks - I'm curious if you can think of any examples of contradictions here? Goal is obviously to make things not break expectations so the more clarity around specifics the better.

**Comment by ljharb** [comment]
Meaning, if it's promises, I expect `await` or `.then` usage, and to be able to use a hook after/inside those, which would violate the rules of hooks.

**Comment by ntucker** [comment]
In my experience using both await and .then() together is not very common. Matching await semantics would be consistent here. Using hooks after suspense is not a violation (even tho in a previous version of react it was reported as such, they have since removed that bug). Hence how [sequential](https://resthooks.io/docs/api/useresource#sequential) requests work

**Comment by ljharb** [comment]
`await fetch(…).then(x => x.json())` is quite a common pattern :-) but i'm not talking about mixing.

I did not realize that calling a hook after `await` was acceptable; i don't understand how that can possibly comply with the rules of hooks (ie, unconditionally calling the same hooks in the same order every time).

**Comment by ntucker** [comment]
Same order must be preserved, but hooks not previously caused due to suspense are allowed. I think this is not mentioned since suspense is still not 'officially supported' in the context of hooks. (Why mention something you don't want people to use in docs)

**Comment by ntucker** [comment]
For `await fetch(…).then(x => x.json())` - ya, that's why I was thinking the useAwait() case would seem to match your expectations more since you can do:

```ts
const [article, users, post] = useAwait(
  useResource(CoolerArticleResource.detail(), id).then(x => x.json()),
  useResource(UserResource.list()),
  useResource(Post.detail(), { id }),
);
```

**Comment by ljharb** [comment]
as long as nobody tries to nest a hook call inside the `.then`, or inside any callback, it'd ofc be fine - i'm mildly concerned that someone would be more likely to make such a refactor if they think of the arguments to `useAwait` as normal promises (as opposed to hook calls)

**Comment by ntucker** [comment]
hook calls inside *any* function, callback, etc (not top level) are not allowed. This is very obvious to see, and is just as easy to observe both as a human or computer as any other case.

**Comment by ntucker** [comment]
Given the new information, which do you prefer @ljharb - useAwait, useAll, something else?

**Comment by ljharb** [comment]
Either way, the hook would only work if the arguments passed to it were all hooks *that returned a promise*, or were synchronous?

**Comment by ntucker** [comment]
useAwait() takes promises (like await statement). Not a promise would throw an error.

useAll() takes suspending hooks. A hook that doesn't suspend wouldn't be noticed as its values would simply pass through. (after a hooks suspends, it doesn't. so a hook that never suspends is fine). Simply returns the values as a tuple from the arguments. Hmm, just realized we'd need to call it from within the hook...updating the example. Now this looks kinda ugly. I'm leaning towards useAwait() now.

**Comment by ljharb** [comment]
I like something taking promises; i don't think `useAwait` is a good name.

**Comment by ntucker** [comment]
Other name ideas? What don't you like about use await name?

**Comment by ljharb** [comment]
`await` implies that it operates on a single promise. this is multiple hooks, which don't actually return promises, they either suspend or don't.

`useSuspendingHooks`?

**Comment by ntucker** [comment]
err, I thought we were talking about the useAwait() - which takes a promise (or more). useAll() is the one that takes hooks that don't return promises.

**Comment by ljharb** [comment]
lol sorry, this is all a bit complex :-)

hooks aren't generally supposed to return promises, so it seems a bit weird to me to go with that approach.

**Comment by ntucker** [comment]
Closing this in favor of two things:

useSuspense() takes a single argument.

Endpoint.all() or something will turn multiple endpoints into one that can be sent there.

```tsx
const { user, article } = useSuspense(
  Endpoint.All({
    user: UserDetail,
    article: ArticleDetail,
  }),
  {user: {id: 10}, article: 10}
);
```
