### ISSUE TITLE
Consider adding a check for trailing slash in  `this.urlRoot`

### ISSUE THREAD

**Issue by maxencefrenette** [coinbase/rest-hooks#81]
**Is your feature request related to a problem? Please describe.**
The API I use doesn't accept trailing slashes. Thus, the default string concatenation in `url()` doesn't work for me.

https://github.com/coinbase/rest-hooks/blob/17bc481aa2b55ebe087d7fdecd663f6a528f0cf6/src/resource/Resource.ts#L174

**Describe the solution you'd like**
A simple if can check if the last character of `this.urlRoot` is a slash and act accordingly.

**Describe alternatives you've considered**
I'm currently overriding url as a workaround. I think my use case is common enough to be contributed upstream, as explained above.

I can provide a PR if there is interest.

**Comment by ntucker** [comment]
Sounds reasonable, I would love to see this PR. Thanks for the contribution :)
