### ISSUE TITLE
Demo sandbox is broken

### ISSUE THREAD

**Issue by k4rli** [coinbase/rest-hooks#831]
Demo sandbox doesn't exist.

"Sandbox not found"

**Comment by ntucker** [comment]
Dang, I'll try to see if I can get it back. In the meantime, here's a better demo for rest hooks itself: https://codesandbox.io/s/rest-hooks-todo-example-lwehp which is taken from https://github.com/Rest-Hooks/todo-example

I'll update the site to point to these
