### ISSUE TITLE
Axios as Custom Networking Library for V5

### ISSUE THREAD

**Issue by uxxman** [coinbase/rest-hooks#836]
Hi,

I am in process of upgrading awesome rest-hooks from v4 to v5 and based on the new docs, resource is imported as

```js
import { Resource } from '@rest-hooks/rest';
```

Since, I am using axios in my project, the example listed for axios still targets the old SimpleResource from 'rest-hooks'. Since the signature of fetch has changed, can you provide an updated example for this.

REF: https://resthooks.io/docs/guides/custom-networking#axios

**Comment by ntucker** [comment]
This should work:

```ts
export default abstract class AxiosResource extends SimpleResource {
  /** Perform network request and resolve with json body */
  static async fetch(
    input: RequestInfo, init: RequestInit
  ) {
    return await axios[init.method](input, init.body);
  }
}
```

Recovering from my 2nd COVID shot, so I'll have to update the docs later - but this should get you unblocked.

**Comment by uxxman** [comment]
@ntucker Thanks, helpful as always :)
