### ISSUE TITLE
question:  how to use immediate mutations in more DRY way?

### ISSUE THREAD

**Issue by SalttySugar** [coinbase/rest-hooks#888]
Hello everyone!
I have specific endpoint for entities amount retrieval and i am struggling to make immediate mutation changes in DRY way.
I have read the documentation and i know about updateParams but it in my case i will be forced to write it after every mutation

maybe there is a way to extend/override endpoints and make them reflect changes the way updateParams does?

**Comment by ntucker** [comment]
https://resthooks.io/docs/guides/immediate-updates has been updated to include information about how to use [Endpoint.update](https://resthooks.io/docs/api/Endpoint#update) in a reusable manner
