### ISSUE TITLE
How to deal with partial resources

### ISSUE THREAD

**Issue by skoging** [coinbase/rest-hooks#9]
As far as I can see, there isn't currently a robust way to handle requests that return partial resources.

In particular, I want to do a list request where I only want to request a couple of the fields of a resource. Then I will request the complete resource when I need it. This works as expected, where the detailed resource replaces the existing partial resource. The problem is that if I reverse the order of these requests. 
Say I'm at a detail page, and navigate back to the list page, if the list request is stale or not in the cache, the partial resources that are fetched will replace any complete resource that is already cached.

Are there any suggestions for how to deal with this? Or plans for improvements that will make this use case possible?

**Comment by skoging** [comment]
I did dome more testing, and it appears lodash merge deals with class instances differently to plain objects. 

https://runkit.com/skoging/5c866ccaa0922f0014c0835e

**Comment by ntucker** [comment]
Are you looking for more feedback, or just busy?

**Comment by skoging** [comment]
I've just been busy lately. I'll take another pass on this in the next
couple days.

**Comment by ntucker** [comment]
Closed in https://github.com/coinbase/rest-hooks/pull/10

**Comment by ntucker** [comment]
https://github.com/coinbase/rest-hooks/pull/10
