### ISSUE TITLE
Making a POST request to a specific resource action

### ISSUE THREAD

**Issue by stevewillard** [coinbase/rest-hooks#90]
This is a great library - thank you!

I have been looking through your docs, and I can't seem to find a good way to send a POST create to a specific resource that has an action.

As an example, if I had a `UserResource`, I want to:
```
POST /users/123/make_manager
```

The POST itself doesn't have a body. Any ideas on how this might be achieved? Thanks!

**Comment by ntucker** [comment]
So you want to send an empty body. What sort of response do you expect - should that be blank too?

**Comment by ntucker** [comment]
If you're still returning the main user:

```typescript
  static makeManagerRequest<T extends typeof Resource>(
    this: T
  ): MutateShape<
    SchemaBase<AbstractInstanceType<T>>,
    { id: number },
    {}
  > {
    return {
      ...super.createRequest(),
      getUrl({ id }: { id: number }) {
        return `/users/${id}/make_manager`
      },
    }
  }
```

If you want nothing in the response body:

```typescript
  static makeManagerRequest<T extends typeof Resource>(
    this: T
  ): MutateShape<
    {},
    { id: number },
    {}
  > {
    return {
      ...super.createRequest(),
      getUrl({ id }: { id: number }) {
        return `/users/${id}/make_manager`
      },
      schema: {},
    }
  }
```

**Comment by stevewillard** [comment]
Ah, perfect. Thank you! This is what I was looking for.
