### ISSUE TITLE
Delete discarding response?

### ISSUE THREAD

**Issue by careless10** [coinbase/rest-hooks#918]
**React version** 
16.13.1

**Concurrent mode**
no

**Rest Hooks version**
5.1.4

**Describe the bug**
When dealing with 'delete()' resource function, the response is discarded, so for example if the response is
```javascript
{
   message:'Resource is deleted'
}
```
i get the params that i sent as a response, this behavior seems to come 
```javascript
fetch(this: RestEndpoint, params: any) {
          return endpoint.fetch.call(this, params).then(() => params);
},
```
in the delete entity function

Now honestly im not quite sure how i am supposed to deal with the messages in the responses, because i need them to be shown in the UI while being sent from the backend, also they are not part of the resource itself.

**Expected behavior**
Response shouldn't be discarded so at least i can grab the message, but if there is another way to handle extra data
coming from the backend like the above 'message' example, i would appreciate if you share it

**Additional Context**
My way of dealing with this on 4.5 was something like
```javascript
const del = useFetcher(EntityResource.deleteShape());
del({entityId}).then(toastResponse);
```
with 'toastResponse' being the function that takes the response and extract the message and display it

Thanks alot

**Comment by ntucker** [comment]
### Background - this is the default delete (from https://github.com/coinbase/rest-hooks/blob/master/packages/rest/src/SimpleResource.ts#L272):

```ts
  /** Endpoint to delete an entity (delete) */
  static delete<T extends typeof SimpleResource>(
    this: T,
  ): RestEndpoint<
    (this: RestEndpoint, params: any) => Promise<any>,
    schema.Delete<T>,
    true
  > {
    const endpoint = this.endpointMutate();
    return this.memo('#delete', () =>
      endpoint.extend({
        fetch(this: RestEndpoint, params: any) {
          return endpoint.fetch.call(this, params).then(() => params);
        },
        method: 'DELETE',
        schema: new schema.Delete(this),
      }),
    );
  }
```

The [Delete schema](https://resthooks.io/docs/api/Delete) needs to know which entity to delete, so it requires the primary key (typically 'id') in the response. Many REST-like APIs don't even return a value on delete, so the default implementation just returns the parameters, which is typically what is needed for the API.

### Solution

You can still access message, so long as you provide the information rest hooks needs to lookup the entity to delete.

#### For example

```js
{
   entity: { id: 5 },
   message:'Resource is deleted'
}
```

This would give you access to both the id to delete, as well as the message you want. To consume this API you'd write something like this in your Resource:

```ts
static delete<T extends typeof Resource>(
    this: T,
): RestEndpoint<
    (this: RestEndpoint, params: any) => Promise<any>,
    schema.Delete<T>,
    true
  > {
  return this.endpointMutate().extend({
    schema: { entity: new schema.Delete(this), message: '' },
    method: 'DELETE'
  })
}
```

Setting the schema tells rest hooks how to find the id to delete, and by extending from `this.endpointMutate()` you don't use the custom fetch that delete did.

**Comment by careless10** [comment]
Thank you @ntucker , you been super helpful.
